package ktanesolver.module.modded.regular.krazytalk;

import java.util.*;import org.springframework.stereotype.Service;import ktanesolver.annotation.ModuleInfo;import ktanesolver.dto.ModuleCatalogDto;import ktanesolver.entity.*;import ktanesolver.enums.ModuleType;import ktanesolver.logic.*;

@Service @ModuleInfo(type=ModuleType.KRAZY_TALK,id="krazyTalk",name="Krazy Talk",category=ModuleCatalogDto.ModuleCategory.MODDED_REGULAR,description="Calculate when to hold a lit button and when to release it from its phrases.",tags={"phrases","timing","stages"})
public class KrazyTalkSolver extends AbstractModuleSolver<KrazyTalkSolver.Input,KrazyTalkSolver.Output>{
 public record Input(int button,String baseMessage,List<String> embellishments,String releaseMessage)implements ModuleInput{} public record Output(int completedButtons,int button,int holdDigit,int releaseDigit,String twitchCommand)implements ModuleOutput{} public record State(Set<Integer> buttons){public State(){this(new LinkedHashSet<>());}}
 private static final Map<String,Integer> VALUES=new HashMap<>(),WRAPPERS=new HashMap<>();static{
  add(WRAPPERS,"“[MESSAGE]”",4,"Quote: [MESSAGE] End quote.",3,"Quote... [MESSAGE] End quote.",6,"‘[MESSAGE]’",1,"It says, [MESSAGE]",7,"It says: [MESSAGE]",2,"It says comma [MESSAGE]",5,"Wait, never mind, [MESSAGE]",9,"Never mind, [MESSAGE]",8,"Start: [MESSAGE] Stop.",0,"Start. [MESSAGE] Stop.",3,"[MESSAGE] I think. It went by pretty fast.",7,"[MESSAGE] I think.",5,"[MESSAGE] Holy crap that was fast.",2,"[MESSAGE] Holy crap that went by fast.",8,"[MESSAGE] Fullstop.",6,"[MESSAGE] Stop.",1,"[MESSAGE] But spelled wrong.",9,"[MESSAGE] But spelled rong.",0,"[MESSAGE] In single quotes.",4,"[MESSAGE] In double quotes.",0);
  add(VALUES,"Quote.",0,"End quote.",1,"It says.",4,"Wait, never mind.",1,"Never mind.",8,"Wait, I think this is Regular Crazy Talk.",9,"Wait, I think this is Crazy Talk.",6,"Wait, I think this is Krazy Talk.",0,"It’s too fast, I can’t read this.",0,"It’s too fast, I can’t read this!",9,"Challenge; 3, 2, 1.",3,"What’d you say?",5,"What did you say?",6,"Crazy Talk, with a C.",7,"Krazy Talk, with a C.",7,"Krazy Talk, with a K.",2,"Crazy Talk, with a K.",8,"Crazy Talc, with a C.",8,"Crazy Talc, with a K.",2,"She shells sea sells by the sea shore.",4,"Sea sells she shells on the sea shore.",4,"Imagine a managed imaginary manager imagining a manager.",6,"It’s one from Crazy Talk.",3,"It’s one from Regular Crazy Talk.",7,"It literally just displays nothing.",4,"Exactly what it sas.",2,"Oh my god, someone’s in my house.",3,"Oh my god, my parents are here.",9,"Oh my god, the FBI are here.",5,"Oh my god, nobody’s here.",2,"Oh my god, somebody’s in my house.",7,"Oh my god, my house is gone.",3,"← → → ← → →",1,"This one is just arrow symbols, no words.",9,"We got a strike.",6,"I got a strike.",0,"That was wrong.",5,"That wasn’t right.",5,"[Phrase from Crazy Talk ]",1,"[Phrase from Regular Crazy Talk ]",8);
 }
 @Override protected SolveResult<Output> doSolve(RoundEntity r,BombEntity b,ModuleEntity m,Input in){if(in==null||in.button()<1||in.button()>4)return failure("Enter a button from 1 through 4");Integer base=get(VALUES,in.baseMessage()),release=get(VALUES,in.releaseMessage());if(base==null||release==null)return failure("Choose base and release messages from the manual table");int hold=base;for(String e:in.embellishments()==null?List.<String>of():in.embellishments()){Integer v=get(WRAPPERS,e);if(v==null)return failure("Unknown embellishment: "+e);hold+=v;}hold=Math.floorMod(hold,10);State s=m.getStateAs(State.class,State::new);Set<Integer> done=new LinkedHashSet<>(s.buttons());done.add(in.button());storeTypedState(m,new State(done));return success(new Output(done.size(),in.button(),hold,release,"hold "+in.button()+" on "+hold),done.size()>=3);}
 private static Integer get(Map<String,Integer>m,String s){if(s==null)return null;Integer v=m.get(s.trim());if(v!=null)return v;return m.get(s.trim().replace('\'','’'));}private static void add(Map<String,Integer>m,Object...x){for(int i=0;i<x.length;i+=2)m.put((String)x[i],(Integer)x[i+1]);}
}
