package ktanesolver.module.modded.regular.coffeebucks;
import java.util.*;import org.springframework.stereotype.Service;import ktanesolver.annotation.ModuleInfo;import ktanesolver.dto.ModuleCatalogDto;import ktanesolver.entity.*;import ktanesolver.enums.ModuleType;import ktanesolver.logic.*;import ktanesolver.module.modded.regular.coffeebucks.CoffeebucksInput.*;
@Service @ModuleInfo(type=ModuleType.COFFEEBUCKS,id="coffeebucks",name="Coffeebucks",category=ModuleCatalogDto.ModuleCategory.MODDED_REGULAR,description="Match each customer's four preferences to the best menu drinks and correct name-color quirk.",tags={"coffee","preferences","colors","multi-stage","audio"})
public class CoffeebucksSolver extends AbstractModuleSolver<CoffeebucksInput,CoffeebucksOutput>{
 private record Drink(String name,Sugar sugar,TimeOfDay time,Stress stress,Size size){}
 private static final List<Drink>DRINKS=List.of(
  new Drink("Twix Frappuccino",Sugar.DIABETIC_IN_WAITING,TimeOfDay.MORNING,Stress.CALM,Size.VENTI),new Drink("The Blue Drink",Sugar.JUST_A_BIT,TimeOfDay.AFTERNOON,Stress.AGITATED,Size.SHORT),new Drink("Matcha & Espresso Fusion",Sugar.SUGAR_IS_MURDER,TimeOfDay.EVENING,Stress.STRESSED,Size.TALL),new Drink("Caramel Snickerdoodle Macchiato",Sugar.LOADS,TimeOfDay.LUNCHTIME,Stress.MURDEROUS,Size.GRANDE),new Drink("Liquid Cocaine",Sugar.DIABETIC_IN_WAITING,TimeOfDay.EVENING,Stress.AGITATED,Size.GRANDE),new Drink("S’mores Hot Chocolate",Sugar.LOADS,TimeOfDay.MORNING,Stress.STRESSED,Size.TALL),new Drink("The Pink Drink",Sugar.JUST_A_BIT,TimeOfDay.AFTERNOON,Stress.CALM,Size.SHORT),new Drink("Grasshopper Frappuccino",Sugar.SUGAR_IS_MURDER,TimeOfDay.LUNCHTIME,Stress.MURDEROUS,Size.VENTI));
 @Override protected SolveResult<CoffeebucksOutput>doSolve(RoundEntity r,BombEntity b,ModuleEntity m,CoffeebucksInput i){if(i==null||i.customerName()==null||!i.customerName().matches("\\S+")||i.nameColor()==null||i.sugar()==null||i.timeOfDay()==null||i.stress()==null||i.size()==null)return failure("Enter the spoken one-word name, its color, and all four preferences");if(i.tipTotalCents()<0||i.currentTipCents()<50||i.currentTipCents()>999)return failure("Tip total must be non-negative and the current tip must be from $0.50 to $9.99");int best=DRINKS.stream().mapToInt(d->score(d,i)).max().orElse(0);List<String>drinks=DRINKS.stream().filter(d->score(d,i)==best).map(Drink::name).toList();String quirk=switch(i.nameColor()){case WHITE->null;case RED->"milk";case GREEN->"cream";case BLUE->"gluten";case PINK->"sprinkles";};int projected=i.tipTotalCents()+i.currentTipCents();storeState(m,Map.of("coffeebucksSugar",sugarAnswer(i.sugar()),"coffeebucksTime",display(i.timeOfDay()),"coffeebucksStress",i.stress()==Stress.STRESSED?"Stressed":display(i.stress()),"coffeebucksSize",display(i.size())));return success(new CoffeebucksOutput(i.customerName(),drinks,drinks.getFirst(),quirk,projected),projected>=1000);}
 static int score(Drink d,CoffeebucksInput i){return(d.sugar()==i.sugar()?1:0)+(d.time()==i.timeOfDay()?1:0)+(d.stress()==i.stress()?1:0)+(d.size()==i.size()?1:0);}private static String sugarAnswer(Sugar s){return switch(s){case DIABETIC_IN_WAITING->"Diabetic in-waiting";case JUST_A_BIT->"Just a bit";case SUGAR_IS_MURDER->"Sugar is murder";case LOADS->"Loads";};}private static String display(Enum<?>e){return Arrays.stream(e.name().toLowerCase().split("_")).map(x->Character.toUpperCase(x.charAt(0))+x.substring(1)).collect(java.util.stream.Collectors.joining(" "));}
}
