package ktanesolver.module.modded.regular.mahjong;
import java.util.*;import org.springframework.stereotype.Service;import ktanesolver.annotation.ModuleInfo;import ktanesolver.dto.ModuleCatalogDto;import ktanesolver.entity.*;import ktanesolver.enums.ModuleType;import ktanesolver.logic.*;
@Service@ModuleInfo(type=ModuleType.MAHJONG,id="MahjongModule",name="Mahjong",category=ModuleCatalogDto.ModuleCategory.MODDED_REGULAR,description="Modify the match rows and identify an available tile pair.",tags={"tiles","matching","serial","staged"})
public class MahjongSolver extends AbstractModuleSolver<MahjongInput,MahjongOutput>{
	public static final List<String>ROW1=List.of("Char 1","Bamboo 5","Wheel 5","Bamboo 8","Bamboo 2","Char 9","Red Dragon","Bamboo 6","Bamboo 4","Wheel 4","Char 6","Char 2","Wheel 2","Char 3"),ROW2=List.of("Wheel 9","Wheel 1","Char 8","Wheel 7","Bamboo 9","Bamboo 7","Char 7","White Dragon","Char 4","Bamboo 3","Wheel 8","Wheel 3","Wheel 6","Char 5"),COUNTING=List.of("Bamboo 1","Plum","Orchid","Chrysanthemum","Bamboo","Spring","Summer","Fall","Winter","North","East","South","West","Green Dragon"),ALL=all();
	@Override protected SolveResult<MahjongOutput>doSolve(RoundEntity round,BombEntity bomb,ModuleEntity module,MahjongInput input){if(input==null||input.countingTile()==null||input.availableTiles()==null||input.pairsRemoved()==null)return failure("Enter the bottom-left tile, all currently available tiles, and pairs already removed");if(input.pairsRemoved()<0||input.pairsRemoved()>13)return failure("Pairs already removed must be from 0 through 13");String counting=canonical(input.countingTile());if(counting==null||!COUNTING.contains(counting))return failure("The bottom-left tile must be one of the 14 Counting Row tiles");if(input.availableTiles().size()<2)return failure("Enter at least two currently available tiles");List<String>available=new ArrayList<>();for(String raw:input.availableTiles()){String tile=canonical(raw);if(tile==null)return failure("Every available tile name must match a Mahjong tile");available.add(tile);}if(new HashSet<>(available).size()!=available.size())return failure("Available tile names must be distinct");if(bomb==null||bomb.getSerialNumber()==null||bomb.getSerialNumber().length()!=6)return failure("Enter the six-character serial number");Rows rows;try{rows=rows(bomb.getSerialNumber(),counting);}catch(IllegalArgumentException exception){return failure(exception.getMessage());}Map<String,String>matches=new HashMap<>();for(int i=0;i<14;i++){matches.put(rows.first().get(i),rows.second().get(i));matches.put(rows.second().get(i),rows.first().get(i));}Set<String>availableSet=new HashSet<>(available);for(String tile:available){String mate=matches.get(tile);if(availableSet.contains(mate)){storeState(module,"mahjongCountingTile",counting);return success(new MahjongOutput(List.of(tile,mate),rows.first(),rows.second(),input.pairsRemoved()+1),input.pairsRemoved()==13);}}return failure("No valid pair exists among those available tiles; check that every currently available tile was entered");}
	static Rows rows(String serial,String counting){List<String>first=new ArrayList<>(ROW1),second=new ArrayList<>(ROW2);int[]positions=serial.toUpperCase(Locale.ROOT).chars().map(c->{if(Character.isDigit(c))return c-'0';if(c>='A'&&c<='Z')return(c-'A'+10)%14;throw new IllegalArgumentException("The serial number may contain only letters and digits");}).toArray();for(int i=0;i<3;i++){String tile=first.get(positions[2*i]);first.set(positions[2*i],second.get(positions[2*i+1]));second.set(positions[2*i+1],tile);}Collections.rotate(second,COUNTING.indexOf(counting));return new Rows(List.copyOf(first),List.copyOf(second));}
	private static String canonical(String raw){if(raw==null)return null;return ALL.stream().filter(tile->tile.equalsIgnoreCase(raw.trim())).findFirst().orElse(null);}private static List<String>all(){List<String>all=new ArrayList<>();all.addAll(ROW1);all.addAll(ROW2);all.addAll(COUNTING);return List.copyOf(all);}record Rows(List<String>first,List<String>second){}
}
