package ktanesolver.module.modded.regular.madmemory;

import java.util.*;import org.springframework.stereotype.Service;import ktanesolver.annotation.ModuleInfo;import ktanesolver.dto.ModuleCatalogDto;import ktanesolver.entity.*;import ktanesolver.enums.ModuleType;import ktanesolver.logic.*;

@Service @ModuleInfo(type=ModuleType.MAD_MEMORY,id="MadMemory",name="Mad Memory",category=ModuleCatalogDto.ModuleCategory.MODDED_REGULAR,description="Solve each of Mad Memory's four display and button-layout stages.",tags={"memory","stages","souvenir"})
public class MadMemorySolver extends AbstractModuleSolver<MadMemorySolver.Input,MadMemorySolver.Output>{
 public record Input(String display,List<Integer> labels)implements ModuleInput{} public record Output(int stage,List<Integer> pressPositions,List<Integer> pressLabels)implements ModuleOutput{} public record Past(String display,int type,int value,List<Integer> labels,List<Integer> positions){} public record State(List<Past> stages){public State(){this(new ArrayList<>());}}
 private static final List<String> DISPLAYS=List.of("1","2","3","4","01","02","03","04","ONE","TWO","THREE","FOUR","WON","TOO","TREE","FOR");
 @Override protected SolveResult<Output> doSolve(RoundEntity r,BombEntity b,ModuleEntity m,Input in){if(in==null||in.display()==null||in.labels()==null||in.labels().size()!=4||!new HashSet<>(in.labels()).equals(Set.of(1,2,3,4)))return failure("Enter a valid display and button labels 1 through 4 from left to right");int ix=DISPLAYS.indexOf(in.display().trim().toUpperCase());if(ix<0)return failure("Unknown display");int type=ix/4,value=ix%4+1;State state=m.getStateAs(State.class,State::new);if(state.stages().size()>=4)return failure("All four stages are already recorded");List<Integer> pos=switch(state.stages().size()){case 0->stage1(type,value,in.labels());case 1->stage2(in.display(),type,value,in.labels(),state.stages().get(0));case 2->stage3(in.display(),type,value,in.labels(),state.stages());default->stage4(type,value,in.labels(),state.stages());};pos=pos.stream().distinct().sorted().toList();List<Integer> selected=pos.stream().map(p->in.labels().get(p-1)).toList();List<Past> past=new ArrayList<>(state.stages());past.add(new Past(in.display().trim().toUpperCase(),type,value,List.copyOf(in.labels()),pos));storeTypedState(m,new State(past));storeState(m,"madMemoryDisplays",past.stream().map(Past::display).toList());return success(new Output(past.size(),pos,selected),past.size()>=4);}
 private static List<Integer> stage1(int t,int v,List<Integer> l){return distinct(List.of(t==0?3:t==1?2:t==2?position(l,2):position(l,1),v==1?4:v==2?position(l,3):v==3?position(l,4):1));}
 private static List<Integer> stage2(String d,int t,int v,List<Integer> l,Past p){if(d.equalsIgnoreCase(p.display()))return complement(p.positions());if(t==p.type())return positionsOfLabels(l,labelsAt(p));if(v==p.value())return positionsOfLabels(l,l.stream().filter(x->x<=p.display().length()).toList());return distinct(List.of(position(l,4),v));}
 private static List<Integer> stage3(String d,int t,int v,List<Integer> l,List<Past> p){Past a=p.get(0),q=p.get(1);if(d.equalsIgnoreCase(a.display())||d.equalsIgnoreCase(q.display()))return positionsOfLabels(l,labelsAt(q).stream().filter(x->!labelsAt(a).contains(x)).toList());if(t==q.type())return positionsOfLabels(l,labelsAt(a).stream().filter(x->!labelsAt(q).contains(x)).toList());if(v==a.value())return positionsOfLabels(l,List.of(v,q.display().length())).stream().filter(x->x>0).toList();Set<Integer> labels=new LinkedHashSet<>(List.of(1,2,3,4));labels.removeAll(labelsAt(a));labels.removeAll(labelsAt(q));List<Integer> out=new ArrayList<>(positionsOfLabels(l,labels));for(int x=1;x<=4;x++)if(!a.positions().contains(x)&&!q.positions().contains(x))out.add(x);return distinct(out);}
 private static List<Integer> stage4(int t,int v,List<Integer> l,List<Past> p){Set<Integer> values=new LinkedHashSet<>();p.forEach(x->values.add(x.value()));if(values.size()==3)return new ArrayList<>(values);Set<Integer> labels=new LinkedHashSet<>();p.forEach(x->labels.addAll(labelsAt(x)));if(labels.size()==3){Set<Integer> missing=new LinkedHashSet<>(Set.of(1,2,3,4));missing.removeAll(labels);return complement(List.of(missing.iterator().next()));}List<Integer> sameType=p.stream().filter(x->x.type()==t).map(Past::value).toList();if(!sameType.isEmpty())return positionsOfLabels(l,sameType);if(p.stream().anyMatch(x->x.value()==v))return List.of(v);List<Integer> out=new ArrayList<>();for(int x=1;x<=4;x++){int z=x;if(p.stream().noneMatch(q->q.positions().contains(z)))out.add(x);}return out;}
 private static int position(List<Integer> l,int x){return l.indexOf(x)+1;}private static List<Integer> labelsAt(Past p){return p.positions().stream().map(x->p.labels().get(x-1)).toList();}private static List<Integer> positionsOfLabels(List<Integer> l,Collection<Integer>x){return x.stream().filter(z->z>=1&&z<=4).map(z->position(l,z)).toList();}private static List<Integer> complement(Collection<Integer>x){List<Integer>r=new ArrayList<>();for(int i=1;i<=4;i++)if(!x.contains(i))r.add(i);return r;}private static List<Integer> distinct(Collection<Integer>x){return x.stream().filter(i->i>0).distinct().toList();}
}
