package ktanesolver.module.modded.regular.simonspins;
import java.util.*;import org.springframework.stereotype.Service;import ktanesolver.annotation.ModuleInfo;import ktanesolver.dto.ModuleCatalogDto;import ktanesolver.entity.*;import ktanesolver.enums.ModuleType;import ktanesolver.logic.*;
@Service@ModuleInfo(type=ModuleType.SIMON_SPINS,id="SimonSpinsModule",name="Simon Spins",category=ModuleCatalogDto.ModuleCategory.MODDED_REGULAR,description="Track the remembered paddle-property sequence across three to five rerandomized stages.",tags={"simon","properties","stages","memory","rule-seed"})
public class SimonSpinsSolver extends AbstractModuleSolver<SimonSpinsInput,SimonSpinsOutput>{
 static final List<String>PROPERTIES=List.of("LEVEL","FACE_COLOR","BACK_SYMBOL","PROTRUSION_PLACEMENT","SYMBOL_SPIN","SYMBOL_SIZE","SYMBOL_FILL","PADDLE_SPIN","ARM_COLOR","SYMBOL","SYMBOL_FLASH","PADDLE_FLIP","ARM_COUNT","FACE_STRIPE","BACK_SYMBOL_COLOR","ARM_LENGTH","BACK_SYMBOL_PATTERN","FRAME_COLOR","PADDLE_SHAPE","PROTRUSION_COUNT");
 static final int[][] ORDER={{2,1,0},{1,2,0},{1,2,0},{0,2,1},{1,2,0},{0,1,2},{1,2,0},{2,0,1},{1,2,0},{0,1,2},{2,1,0},{1,0,2},{2,1,0},{2,1,0},{0,1,2},{0,2,1},{1,0,2},{1,0,2},{1,0,2},{1,2,0}};
 static final Map<String,List<String>>VALUES=Map.ofEntries(
  Map.entry("LEVEL",List.of("BOTTOM","MIDDLE","TOP")),Map.entry("SYMBOL",List.of("I","X","Y")),Map.entry("SYMBOL_SIZE",List.of("LARGE","MEDIUM","SMALL")),Map.entry("SYMBOL_FILL",List.of("FILLED","HOLLOW","STRIPED")),Map.entry("SYMBOL_SPIN",List.of("CCW","NONE","CW")),Map.entry("SYMBOL_FLASH",List.of("NONE","ON_OFF","INVERTING")),Map.entry("PADDLE_SPIN",List.of("CCW","NONE","CW")),Map.entry("PADDLE_FLIP",List.of("LEFT","RIGHT","NONE")),Map.entry("FACE_COLOR",List.of("BLUE","RED","YELLOW")),Map.entry("FACE_STRIPE",List.of("ARM_ALIGNED","PERPENDICULAR_TO_ARM","NONE")),Map.entry("PADDLE_SHAPE",List.of("CIRCLE","PENTAGON","SQUARE")),Map.entry("FRAME_COLOR",List.of("BLUE","RED","YELLOW")),Map.entry("ARM_COLOR",List.of("BLUE","RED","YELLOW")),Map.entry("BACK_SYMBOL_PATTERN",List.of("SINGLE","ARM_ALIGNED","PERPENDICULAR_TO_ARM")),Map.entry("BACK_SYMBOL_COLOR",List.of("BLUE","RED","YELLOW")),Map.entry("BACK_SYMBOL",List.of("CIRCLE","SQUARE","STAR")),Map.entry("PROTRUSION_PLACEMENT",List.of("LEFT","OUTSIDE","RIGHT")),Map.entry("PROTRUSION_COUNT",List.of("1","2","3")),Map.entry("ARM_LENGTH",List.of("SHORT","MEDIUM","LONG")),Map.entry("ARM_COUNT",List.of("1","2","3")));
 private static final List<String>SHAPES=List.of("CIRCLE","PENTAGON","SQUARE");
 @Override protected SolveResult<SimonSpinsOutput>doSolve(RoundEntity round,BombEntity bomb,ModuleEntity module,SimonSpinsInput input){
  if(input==null)return failure("Enter the current stage paddle properties");SimonSpinsState state=module.getStateAs(SimonSpinsState.class,SimonSpinsState::new);
  if(Boolean.TRUE.equals(input.confirmSolved())){if(state.lastStage()<1)return failure("Solve at least one stage before confirming the module");return success(output(state.lastStage(),state.lastPresses(),state.remembered(),bomb,true));}
  if(input.stage()==null||input.stage()<1||input.stage()>5||input.properties()==null)return failure("Enter stage 1 through 5 and its required property rows");int start=startRow(bomb);if(start<0)return failure("Simon Spins requires a six-character serial with digits in positions 3 and 6");
  if(input.stage()>1&&state.lastStage()!=input.stage()-1)return failure("Enter stages in order, or restart from stage 1 after a strike");
  List<Integer>remembered=input.stage()==1?new ArrayList<>():new ArrayList<>(state.remembered());List<Integer>rows=requiredRows(start,input.stage());Map<String,int[]>observed=new HashMap<>();
  for(int row:rows){String property=PROPERTIES.get(row);List<String>raw=input.properties().get(property);if(raw==null)return failure("Enter "+property+" for circle, pentagon, and square");List<String>vals=raw.stream().map(SimonSpinsSolver::norm).toList();List<String>allowed=VALUES.get(property);if(vals.size()!=3||vals.stream().distinct().count()!=3||!new HashSet<>(vals).equals(new HashSet<>(allowed)))return failure(property+" must assign each value once across circle, pentagon, and square");observed.put(property,vals.stream().mapToInt(allowed::indexOf).toArray());}
  List<String>presses=new ArrayList<>();if(input.stage()==1){int row=start,paddle=indexOf(observed.get(PROPERTIES.get(row)),ORDER[row][0]);remembered.add(observed.get(PROPERTIES.get((start+1)%20))[paddle]);presses.add(SHAPES.get(paddle));}
  else{for(int i=0;i<remembered.size();i++){int row=(start+1+i)%20;presses.add(SHAPES.get(indexOf(observed.get(PROPERTIES.get(row)),remembered.get(i))));}int lastRow=(start+input.stage()-1)%20,old=remembered.getLast(),column=indexOf(ORDER[lastRow],old),next=ORDER[lastRow][(column+1)%3],paddle=indexOf(observed.get(PROPERTIES.get(lastRow)),next),nextRow=(lastRow+1)%20;remembered.add(observed.get(PROPERTIES.get(nextRow))[paddle]);presses.add(SHAPES.get(paddle));}
  SimonSpinsState next=new SimonSpinsState(input.stage(),remembered,presses);module.setState(next);return success(output(input.stage(),presses,remembered,bomb,false),false);
 }
 private static SimonSpinsOutput output(int stage,List<String>presses,List<Integer>remembered,BombEntity bomb,boolean solved){int start=startRow(bomb);List<String>labels=new ArrayList<>();for(int i=0;i<remembered.size();i++){int row=(start+1+i)%20;labels.add(PROPERTIES.get(row)+"="+VALUES.get(PROPERTIES.get(row)).get(remembered.get(i)));}List<String>next=solved||stage>=5?List.of():requiredRows(start,stage+1).stream().map(PROPERTIES::get).toList();return new SimonSpinsOutput(stage,presses,labels,next,solved);}
 static int startRow(BombEntity bomb){String s=bomb.getSerialNumber();return s!=null&&s.length()==6&&Character.isDigit(s.charAt(2))&&Character.isDigit(s.charAt(5))?s.charAt(2)-'0'+10*((s.charAt(5)-'0')%2):-1;}
 static List<Integer>requiredRows(int start,int stage){List<Integer>rows=new ArrayList<>();if(stage==1){rows.add(start);rows.add((start+1)%20);}else for(int i=1;i<=stage;i++)rows.add((start+i)%20);return rows;}
 private static int indexOf(int[]array,int value){for(int i=0;i<array.length;i++)if(array[i]==value)return i;return-1;}
 private static String norm(String s){return s==null?"":s.trim().toUpperCase(Locale.ROOT).replace("/","_").replace('-', '_').replace(' ','_');}
}
