package ktanesolver.module.modded.regular.lionsshare;
import java.util.*;import org.springframework.stereotype.Service;import ktanesolver.annotation.ModuleInfo;import ktanesolver.dto.ModuleCatalogDto;import ktanesolver.entity.*;import ktanesolver.enums.ModuleType;import ktanesolver.logic.*;import ktanesolver.module.modded.regular.lionsshare.LionsShareOutput.Portion;
@Service @ModuleInfo(type=ModuleType.LIONS_SHARE,id="LionsShareModule",name="Lion's Share",category=ModuleCatalogDto.ModuleCategory.MODDED_REGULAR,description="Apportion prey among the displayed pride members from their timeline status, family, and edgework bonuses.",tags={"lions","percentages","timeline","indicators","serial-number"})
public class LionsShareSolver extends AbstractModuleSolver<LionsShareInput,LionsShareOutput>{
 enum Status{NULL,UNBORN,CUB,ADULT,ABSENT,KING,DEAD,VISITING}private record Lion(String name,boolean male,String mother,String statuses){Status at(int year){return Status.values()[year<=statuses.length()?statuses.charAt(year-1)-'0':6];}}
 private static final List<Lion>PRIDE=Arrays.stream(("Taka,m,Uru,01223555555;Mufasa,m,Uru,12255;Uru,f,,333333;Ahadi,m,,335;Zama,f,,3333;Mohatu,m,,55;Kion,m,Nala,0000000000001225;Kiara,f,Nala,0000000000012233;Kopa,m,Nala,0000000000012;Kovu,m,Zira,0000000000122333;Vitani,f,Zira,0000000001223333;Nuka,m,Zira,0000000012233;Mheetu,m,Sarabi,0000012233344433;Zira,f,Sarafina,0000012233333;Nala,f,Sarafina,0000122333433333;Simba,m,Sarabi,000124444445555;Sarabi,f,,22333333333333;Sarafina,f,,223333333333").split(";")).map(x->x.split(",",-1)).map(x->new Lion(x[0],x[1].equals("m"),x[2],x[3])).toList();
 private static final Map<String,Boolean>VISITORS=visitorMap();public static final List<String>ALL_LIONS=java.util.stream.Stream.concat(PRIDE.stream().map(Lion::name),VISITORS.keySet().stream()).toList();
 @Override protected SolveResult<LionsShareOutput>doSolve(RoundEntity r,BombEntity b,ModuleEntity m,LionsShareInput i){if(i==null||i.year()<1||i.year()>16||i.lions()==null||i.lions().size()<2||i.lions().size()>8||i.leadHuntress()==null)return failure("Enter the year, 2 to 8 displayed lions, and lead huntress");if(new HashSet<>(i.lions()).size()!=i.lions().size()||i.lions().stream().anyMatch(x->!ALL_LIONS.contains(x))||!i.lions().contains(i.leadHuntress()))return failure("Lion names must be distinct known names and include the lead huntress");Map<String,Lion>shown=new LinkedHashMap<>();for(String name:i.lions()){Lion lion=PRIDE.stream().filter(x->x.name().equals(name)).findFirst().orElseGet(()->new Lion(name,VISITORS.get(name),"","7".repeat(16)));if(lion.at(i.year())==Status.NULL)return failure(name+" is not present in that year on the default timeline");shown.put(name,lion);}Lion lead=shown.get(i.leadHuntress());if(lead.male()||lead.at(i.year())!=Status.ADULT)return failure("The lead huntress must be a displayed adult female");String kingsMother=PRIDE.stream().filter(x->x.at(i.year())==Status.KING).map(Lion::mother).findFirst().orElse(null);int[]ent=new int[i.lions().size()];for(int x=0;x<i.lions().size();x++){Lion lion=shown.get(i.lions().get(x));Status status=lion.at(i.year());boolean sibling=!lion.mother().isEmpty()&&lion.mother().equals(kingsMother);ent[x]=switch(status){case KING->10;case ADULT->sibling?7:5;case CUB->sibling?4:3;case VISITING->1;default->0;};String upper=lion.name().toUpperCase();long inds=b.getIndicators().entrySet().stream().filter(e->Boolean.TRUE.equals(e.getValue())&&e.getKey().toUpperCase().indexOf(upper.charAt(0))>=0).count();ent[x]+=inds*(status==Status.KING?4:status==Status.ADULT&&sibling?3:lion.male()?2:1);ent[x]+=b.getSerialNumber().toUpperCase().chars().filter(Character::isLetter).filter(ch->upper.indexOf(ch)>=0).count();}for(Lion lion:shown.values())if(lion.at(i.year())==Status.UNBORN){int mother=i.lions().indexOf(lion.mother());if(mother<0)return failure("The unborn cub's mother must be displayed");ent[mother]++;}for(int x=0;x<i.lions().size();x++){Status status=shown.get(i.lions().get(x)).at(i.year());if(status==Status.UNBORN||status==Status.ABSENT||status==Status.DEAD)ent[x]=0;}int total=Arrays.stream(ent).sum();if(total<=0)return failure("At least two entitled lions must be displayed");int[]pct=Arrays.stream(ent).map(x->x*100/total).toArray();pct[i.lions().indexOf(i.leadHuntress())]+=100-Arrays.stream(pct).sum();List<Portion>portions=new ArrayList<>();List<String>removed=new ArrayList<>();for(int x=0;x<i.lions().size();x++){portions.add(new Portion(i.lions().get(x),pct[x],ent[x]));if(pct[x]==0)removed.add(i.lions().get(x));}storeState(m,Map.of("lionsShareYear",i.year(),"lionsShareRemovedLions",removed));return success(new LionsShareOutput(portions,total));}
 private static Map<String,Boolean>visitorMap(){Map<String,Boolean>m=new LinkedHashMap<>();for(String token:"Tojo,m;Chumvi,m;Malka,m;Askari,m;Tama,f;Rani,f;Zuri,f;Tiifu,f;Kula,f;Naanda,f;Ndona,f;Sheena,f;Diku,f;Boga,f;Sabini,f;Babu,f;Weena,f".split(";")){String[]x=token.split(",");m.put(x[0],x[1].equals("m"));}return m;}
}
