package ktanesolver.module.modded.regular.theradio;
import java.util.*;import org.springframework.stereotype.Service;import ktanesolver.annotation.ModuleInfo;import ktanesolver.dto.ModuleCatalogDto;import ktanesolver.entity.*;import ktanesolver.enums.ModuleType;import ktanesolver.logic.*;
@Service@ModuleInfo(type=ModuleType.THE_RADIO,id="KritRadio",name="The Radio",category=ModuleCatalogDto.ModuleCategory.MODDED_REGULAR,description="Tune the correct international radio channel and transmit at the required time.",tags={"radio","frequency","timing","barcode"})
public class TheRadioSolver extends AbstractModuleSolver<TheRadioInput,TheRadioOutput>{
	private static final List<Channel>CHANNELS=List.of(
		new Channel("German","Bayern 1",1,"88.9","BAYERN1"),new Channel("French","Radio Libertaire",2,"89.4",""),new Channel("French","Radio Nova",3,"89.8","NOVA"),new Channel("Dutch","NPO1",4,"91.8","NPO1"),new Channel("German","RTL Radio",5,"93.3","RTL"),new Channel("German","Klassik Radio",6,"96.0",""),new Channel("English","Rother FM",7,"96.1",""),new Channel("French","Skyrock",8,"97.5","SKYROCK"),new Channel("Dutch","Radio Veronica",9,"97.7","VERONICA"),new Channel("French","Radio FG",10,"98.2","FG"),new Channel("German","WDR 4",11,"99.5","WDR4"),new Channel("English","Classic FM",12,"99.9","CLASSICFM"),new Channel("French","Jazz Radio",13,"100.0","JAZZRADIO"),new Channel("Dutch","Q-Music",14,"100.7","QMUSIC"),new Channel("Dutch","Sky Radio",15,"101.9","SKYRADIO"),new Channel("Dutch","Radio538",16,"102.4",""),new Channel("English","Heart Radio",17,"102.7","HEART"),new Channel("German","Radio Hamburg",18,"103.6","HAMBURG"),new Channel("English","Radio X",19,"104.9","RADIOX"),new Channel("English","Magic 105.4 FM",20,"105.4","MAGIC105"));
	private static final Map<String,List<Integer>>COUNTRY_ORDER=Map.of("Dutch",List.of(4,14,15,9,16),"English",List.of(12,20,19,17,7),"German",List.of(5,1,11,18,6),"French",List.of(13,8,3,10,2));
	@Override protected SolveResult<TheRadioOutput>doSolve(RoundEntity round,BombEntity bomb,ModuleEntity module,TheRadioInput input){if(input==null||input.barcode()==null||input.startingChannel()==null||input.startingTransmission()==null)return failure("Enter the barcode, factory channel, and factory transmission");String barcode=input.barcode().trim().toUpperCase(Locale.ROOT).replace("RA-D-IO:","").trim();if(!barcode.matches("[A-UW]{3}\\d{2}"))return failure("The barcode must contain three generated letters followed by two digits");if(input.startingChannel()<1||input.startingChannel()>20)return failure("The factory channel must be from 1 through 20");String start=input.startingTransmission().trim().toUpperCase(Locale.ROOT);if(!start.equals("AM")&&!start.equals("FM"))return failure("The factory transmission must be AM or FM");if(bomb==null||bomb.getSerialNumber()==null||!bomb.getSerialNumber().matches("[A-Za-z0-9]{6}"))return failure("Enter the six-character serial number");List<Integer>serialDigits=bomb.getSerialNumber().chars().filter(Character::isDigit).map(c->c-'0').boxed().toList();if(serialDigits.isEmpty())return failure("The serial number must contain digits");int batteries=bomb.getBatteryCount();String country=country(batteries,bomb.getBatteryHolders());Channel channel=channel(country,barcode);String transmission=serialDigits.getFirst()>serialDigits.getLast()&&barcode.charAt(3)>barcode.charAt(4)?"FM":"AM";int target=country.equals("Dutch")?barcode.charAt(3)-'0':country.equals("English")?0:country.equals("German")?batteries%10:serialDigits.getLast();String at=country.equals("English")?"00":String.format("0%d",target);String timing=country.equals("English")?"Transmit when the two seconds digits match.":"Transmit when the two seconds digits add to "+target+".";List<String>commands=new ArrayList<>();commands.add("reset");int delta=channel.number()-input.startingChannel();if(delta>0)commands.add("channel up "+delta);else if(delta<0)commands.add("channel down "+-delta);if(!start.equals(transmission))commands.add("switch");commands.add("transmit at "+at);return success(new TheRadioOutput(country,channel.name(),channel.number(),channel.frequency(),transmission,at,timing,List.copyOf(commands)));}
	static String country(int batteries,int holders){if(List.of(3,5,7,11,13).contains(batteries))return"Dutch";if(batteries>0&&batteries==holders)return"English";return batteries%2==0?"German":"French";}
	static Channel channel(String country,String barcode){for(int number:COUNTRY_ORDER.get(country)){Channel channel=CHANNELS.get(number-1);if(channel.match().isEmpty()||channel.match().chars().anyMatch(ch->barcode.indexOf(ch)>=0))return channel;}throw new IllegalStateException();}
	record Channel(String country,String name,int number,String frequency,String match){}
}
