package ktanesolver.module.modded.regular.boggle;

import java.util.ArrayList;import java.util.HashSet;import java.util.List;import java.util.Locale;import java.util.Set;
import org.springframework.stereotype.Service;
import ktanesolver.annotation.ModuleInfo;import ktanesolver.dto.ModuleCatalogDto;import ktanesolver.entity.BombEntity;import ktanesolver.entity.ModuleEntity;import ktanesolver.entity.RoundEntity;import ktanesolver.enums.ModuleType;import ktanesolver.logic.AbstractModuleSolver;import ktanesolver.logic.SolveResult;

@Service
@ModuleInfo(type=ModuleType.BOGGLE,id="boggle",name="Boggle",category=ModuleCatalogDto.ModuleCategory.MODDED_REGULAR,description="Identify the hidden 4×4 board and submit dictionary-verified words worth at least five points.",tags={"words","grid","search","souvenir"})
public class BoggleSolver extends AbstractModuleSolver<BoggleInput,BoggleOutput>{
	static final String[] MASTER={"ISHNFYETRT","PWTETEITRA","OOQEAWXAME","CAHRZRCHDR","MPJEKDWSOO","USODTDETIH","ISIAELURMO","LEDEOCOGTU","RNCEAYNBIN","ATELBATWSQ"};
	static final String[] PLANS={"hoopster","requote","enterate","eyewater","atwixt+cattie","extrait","tartrate","requote","requote","reheard","crater+krater","atwixt+crate","extrados","aerodart","rhapsode","rhapsode","reheard","crazed+earded","warded+scraw","hoisted","erotise","rhapsode","rhapsode","iodated","deleted","detrude","choired","moisture","disposed","disposed","cleated","cleated","decoloured","couldest","moisture","silenced","deadness","ideated","clouded","coloured","congrued","nitrite","antecedes","beedies","debacle","beacon+belace","batboy+boucle","corgis+lurgis","intron+obsign"};
	@Override protected SolveResult<BoggleOutput> doSolve(RoundEntity round,BombEntity bomb,ModuleEntity module,BoggleInput input){if(input==null||input.visible()==null||input.visible().size()!=4)return failure("Enter the four initially visible cells and letters");List<Obs>obs=new ArrayList<>();Set<String>cells=new HashSet<>();for(BoggleInput.VisibleCell v:input.visible()){if(v==null||v.cell()==null||v.letter()==null)return failure("Every visible letter needs a cell");String cell=v.cell().trim().toUpperCase(Locale.ROOT),letter=v.letter().trim().toUpperCase(Locale.ROOT);if(!cell.matches("[A-D][1-4]")||!letter.matches("[A-Z]")||!cells.add(cell))return failure("Visible cells must be four distinct A1–D4 coordinates with one letter each");obs.add(new Obs(cell.charAt(1)-'1',cell.charAt(0)-'A',letter.charAt(0)));}
		List<int[]>matches=new ArrayList<>();for(int vr=0;vr<7;vr++)for(int hc=0;hc<7;hc++){boolean ok=true;for(Obs o:obs)if(MASTER[vr+o.r()].charAt(hc+o.c())!=o.letter())ok=false;if(ok)matches.add(new int[]{vr,hc});}if(matches.size()!=1)return failure(matches.isEmpty()?"Those visible letters do not match the manual grid":"Those observations match more than one board; reveal/check another distinguishing cell");int vr=matches.get(0)[0],hc=matches.get(0)[1];BoggleOutput out=plan(vr,hc);storeState(module,"visibleLetters",obs.stream().map(o->String.valueOf(o.letter())).toList());storeState(module,"board",out.board());return success(out);}
	static BoggleOutput plan(int vr,int hc){List<String>board=new ArrayList<>();for(int r=0;r<4;r++)board.add(MASTER[vr+r].substring(hc,hc+4));List<BoggleOutput.Play>plays=new ArrayList<>();int total=0;for(String word:PLANS[vr*7+hc].split("\\+")){List<String>path=find(board,word);if(path==null)throw new IllegalStateException("Missing curated Boggle path for "+word);int score=word.length()<=4?1:word.length()==5?2:word.length()==6?3:word.length()==7?5:11;plays.add(new BoggleOutput.Play(word,path,score));total+=score;}return new BoggleOutput(List.copyOf(board),List.copyOf(plays),total);}
	private static List<String> find(List<String>b,String word){for(int r=0;r<4;r++)for(int c=0;c<4;c++){List<String>p=new ArrayList<>();if(find(b,word,0,r,c,0,p))return p;}return null;}
	private static boolean find(List<String>b,String w,int at,int r,int c,int used,List<String>path){int bit=1<<(r*4+c);if((used&bit)!=0)return false;char tile=b.get(r).charAt(c);String token=tile=='Q'?"qu":String.valueOf(Character.toLowerCase(tile));if(!w.startsWith(token,at))return false;path.add(String.valueOf((char)('A'+c))+(r+1));int next=at+token.length();if(next==w.length())return true;for(int dr=-1;dr<=1;dr++)for(int dc=-1;dc<=1;dc++){int nr=r+dr,nc=c+dc;if((dr!=0||dc!=0)&&nr>=0&&nr<4&&nc>=0&&nc<4&&find(b,w,next,nr,nc,used|bit,path))return true;}path.remove(path.size()-1);return false;}
	private record Obs(int r,int c,char letter){}
}
