package ktanesolver.module.modded.regular.connectiondevice;
import java.util.*;import org.springframework.stereotype.Service;import ktanesolver.annotation.ModuleInfo;import ktanesolver.dto.ModuleCatalogDto;import ktanesolver.entity.*;import ktanesolver.enums.*;import ktanesolver.logic.*;
@Service@ModuleInfo(type=ModuleType.CONNECTION_DEVICE,id="KritConnectionDev",name="Connection Device",category=ModuleCatalogDto.ModuleCategory.MODDED_REGULAR,description="Choose the app and construct a valid six-character message from the visible keys.",tags={"code","timer","ports","indicators","batteries"})
public class ConnectionDeviceSolver extends AbstractModuleSolver<ConnectionDeviceInput,ConnectionDeviceOutput>{
	private static final List<Map.Entry<PortType,String>>PORTS=List.of(Map.entry(PortType.DVI,"DVI"),Map.entry(PortType.PARALLEL,"PRL"),Map.entry(PortType.PS2,"PS2"),Map.entry(PortType.RJ45,"RJ4"),Map.entry(PortType.SERIAL,"SRL"),Map.entry(PortType.STEREO_RCA,"RCA"),Map.entry(PortType.COMPOSITE_VIDEO,"CSV"),Map.entry(PortType.USB,"USB"),Map.entry(PortType.HDMI,"HDM"));
	private static final List<String>INDICATORS=List.of("SND","CLR","CAR","IND","FRQ","SIG","NSA","MSA","TRN","BOB","FRK");
	@Override protected SolveResult<ConnectionDeviceOutput>doSolve(RoundEntity round,BombEntity bomb,ModuleEntity module,ConnectionDeviceInput input){
		if(input==null||input.deviceSerial()==null||input.letterKeys()==null||input.digitKeys()==null)return failure("Enter the device serial and all fourteen keys");String device=input.deviceSerial().trim().toUpperCase(Locale.ROOT),letters=input.letterKeys().replaceAll("\\s","").toUpperCase(Locale.ROOT),digits=input.digitKeys().replaceAll("\\s","");
		if(!device.matches("[A-UW]{3}\\d{2}"))return failure("Device serial must be three letters A–U/W followed by two digits");if(!letters.matches("[A-Z]{7}")||letters.chars().distinct().count()!=7)return failure("Enter seven distinct letter keys");if(!digits.matches("\\d{7}")||digits.chars().distinct().count()!=7)return failure("Enter seven distinct digit keys");
		String bombSerial=bomb.getSerialNumber()==null?"":bomb.getSerialNumber().toUpperCase(Locale.ROOT);OptionalInt firstLetter=bombSerial.chars().filter(Character::isLetter).findFirst();List<Integer>bombDigits=bombSerial.chars().filter(Character::isDigit).map(c->c-'0').boxed().toList();if(firstLetter.isEmpty()||bombDigits.isEmpty())return failure("Bomb serial must contain a letter and a digit");
		String app=app(device,bombSerial),required=required(app,bomb,input.batterySet());if(required==null)return failure("Select the first battery set present for Skype");Set<Character>available=new LinkedHashSet<>();(letters+digits).chars().forEach(c->available.add((char)c));String code=findCode(app,required,(char)firstLetter.getAsInt(),available);if(code==null)return failure("The visible keys cannot form a valid code; verify the device keys and battery set");
		int target=switch(app){case"Whatsapp"->bombDigits.get(0);case"Discord"->bombDigits.get(bombDigits.size()-1);default->{int d=bombDigits.get(0)-bombDigits.get(bombDigits.size()-1);yield d<0?d+10:d;}};String second=secondFor(target);List<String>commands=List.of("boot","open "+app.toLowerCase(Locale.ROOT),"set "+code,"send "+second);return success(new ConnectionDeviceOutput(app,required,code,target,second,commands));
	}
	static String app(String device,String bombSerial){int sum=device.charAt(3)-'0'+device.charAt(4)-'0';if(sum>8&&device.chars().anyMatch(c->"WHATSAPP".indexOf(c)>=0))return"Whatsapp";if(device.chars().anyMatch(c->"DISCORD".indexOf(c)>=0)&&bombSerial.chars().anyMatch(c->"DISCORD".indexOf(c)>=0))return"Discord";return"Skype";}
	private static String required(String app,BombEntity bomb,ConnectionDeviceInput.BatterySet battery){if(app.equals("Whatsapp"))return PORTS.stream().filter(e->bomb.hasPort(e.getKey())).map(Map.Entry::getValue).findFirst().orElse("NAN");if(app.equals("Discord"))return INDICATORS.stream().filter(bomb::hasIndicator).findFirst().orElse("NAN");if(battery==null)return null;return switch(battery){case DBT->"DBT";case ABT->"ABT";case THREE_BT->"3BT";case FOUR_BT->"4BT";case NAN->"NAN";};}
	static String findCode(String app,String required,char serial,Set<Character>available){if(!required.chars().allMatch(c->available.contains((char)c))||!available.contains(serial))return null;for(int offset=0;offset<=3;offset++)for(int serialPos=0;serialPos<6;serialPos++){char[]code=new char[6];boolean ok=true;for(int i=0;i<3;i++){int p=offset+i,c=required.charAt(i);if(code[p]!=0&&code[p]!=c)ok=false;code[p]=(char)c;}if(code[serialPos]!=0&&code[serialPos]!=serial)ok=false;code[serialPos]=serial;if(ok){String found=fill(code,0,app,required,available);if(found!=null)return found;}}return null;}
	private static String fill(char[]code,int position,String app,String required,Set<Character>available){if(position==6){String value=new String(code);return valid(value,app,required)?value:null;}if(code[position]!=0)return allowed(code[position],position,app)?fill(code,position+1,app,required,available):null;for(char c:available)if(allowed(c,position,app)){code[position]=c;String found=fill(code,position+1,app,required,available);if(found!=null)return found;}code[position]=0;return null;}
	private static boolean allowed(char c,int p,String app){if(p==0)return switch(app){case"Whatsapp"->"13579".indexOf(c)>=0;case"Discord"->"012345".indexOf(c)>=0;default->"BDFHJLNPRTVXZ".indexOf(c)>=0;};if(p==5&&app.equals("Whatsapp"))return"02468".indexOf(c)>=0;if(p==5&&app.equals("Skype"))return"56789".indexOf(c)>=0;return true;}
	private static boolean valid(String code,String app,String required){long distinct=code.chars().distinct().count();return code.contains(required)&&(app.equals("Whatsapp")||(app.equals("Discord")?(distinct==6||required.equals("BOB")||required.equals("NAN")):distinct>4));}
	static String secondFor(int target){for(int second=0;second<60;second++){int sum=second/10+second%10;if(sum>10)sum-=10;if(sum==target)return String.format(Locale.ROOT,"%02d",second);}throw new IllegalArgumentException("No timer second for "+target);}
}
