package ktanesolver.module.modded.regular.vexillology;
import java.util.*;import org.springframework.stereotype.Service;import ktanesolver.annotation.ModuleInfo;import ktanesolver.dto.ModuleCatalogDto;import ktanesolver.entity.*;import ktanesolver.enums.*;import ktanesolver.logic.*;
@Service @ModuleInfo(type=ModuleType.VEXILLOLOGY,id="vexillology",name="Vexillology",category=ModuleCatalogDto.ModuleCategory.MODDED_REGULAR,description="Paint the flag from its shape, flagpole colors, and edgework, then submit on the required timer digit.",tags={"flags","colors","venn diagram","timing"})
public class VexillologySolver extends AbstractModuleSolver<VexillologyInput,VexillologyOutput>{
 private static final List<String>C=List.of("red","orange","green","yellow","blue","aqua","white","black");private static final int[][]T={{6,5,2},{0,4,5},{4,0,1},{3,7,6},{7,3,0},{1,2,7},{2,1,4},{5,6,3}};
 private static final Map<String,String[]>COUNTRIES=Map.ofEntries(e("horizontal:red,blue,orange","Armenia","4"),e("horizontal:red,white,red","Austria","3"),e("vertical:black,yellow,red","Belgium","2"),e("horizontal:red,yellow,green","Bolivia","1"),e("horizontal:white,green,red","Bulgaria","9"),e("vertical:blue,yellow,red","Chad / Romania","0 or 5"),e("nordic-2:red,white","Denmark","5"),e("horizontal:blue,black,white","Estonia","2"),e("nordic-3:white,red,blue","Faroe Islands","8"),e("nordic-2:white,blue","Finland","8"),e("vertical:blue,white,red","France","3"),e("horizontal:green,yellow,blue","Gabon","1"),e("horizontal:black,red,yellow","Germany","9"),e("vertical:red,yellow,green","Guinea","4"),e("horizontal:red,white,green","Hungary","6"),e("nordic-3:blue,red,white","Iceland","4"),e("vertical:green,white,orange","Ireland","3"),e("vertical:green,white,red","Italy","9"),e("vertical:orange,white,green","Ivory Coast","5"),e("horizontal:yellow,green,red","Lithuania","0"),e("horizontal:red,white,aqua","Luxembourg","2"),e("vertical:green,yellow,red","Mali","3"),e("horizontal:red,white,blue","Netherlands","1"),e("vertical:green,white,green","Nigeria","6"),e("nordic-3:red,blue,white","Norway","7"),e("vertical:red,white,red","Peru","1"),e("horizontal:white,blue,red","Russia","7"),e("horizontal:green,white,blue","Sierra Leone","2"),e("nordic-2:blue,yellow","Sweden","6"),e("horizontal:red,white,black","Yemen","7"));
 @Override protected SolveResult<VexillologyOutput>doSolve(RoundEntity round,BombEntity bomb,ModuleEntity module,VexillologyInput input){if(input==null||input.flagpoleColors()==null||input.flagpoleColors().size()!=3)return failure("Choose a flag type and enter all three flagpole colors");String type=n(input.flagType());if(!Set.of("horizontal","vertical","nordic-2","nordic-3").contains(type))return failure("Flag type must be horizontal, vertical, nordic-2, or nordic-3");List<String>pole=input.flagpoleColors().stream().map(VexillologySolver::n).toList();if(pole.stream().anyMatch(x->!C.contains(x)))return failure("Flagpole colors must be red, orange, green, yellow, blue, aqua, white, or black");int[]p=pole.stream().mapToInt(C::indexOf).toArray();int a=first(type,p),b=second(type,p,bomb),d=type.equals("nordic-2")?-1:venn(p[0],bomb);List<Integer>answer=new ArrayList<>(List.of(a,b));if(d>=0)answer.add(d);String rawKey=key(type,answer);if(!COUNTRIES.containsKey(rawKey))transpose(answer);String key=key(type,answer);String[]country=COUNTRIES.get(key);String digit=country==null?String.valueOf(bomb.getLastDigit()):country[1];List<String>colors=answer.stream().map(C::get).toList(),commands=new ArrayList<>();for(int i=0;i<colors.size();i++)commands.add("fill "+(i+1)+" "+colors.get(i));commands.add("submit on "+(digit.equals("0 or 5")?"5":digit));storeState(module,"vexillologyFlagpoleColors",List.copyOf(pole));storeState(module,"vexillologyFlagType",type);storeState(module,"vexillologyFirstAnswerColor",colors.get(0));return success(new VexillologyOutput(colors,country==null?null:country[0],digit,List.copyOf(commands)));}
 private static int first(String t,int[]p){if(t.equals("horizontal")){if(p[0]==p[1]&&p[1]==p[2])return 7;if(two(p,1)||two(p,2)||two(p,7))return 2;if(p[2]==1||p[2]==6)return 3;if(p[0]==2||p[0]==4)return 1;if(has(p,7)&&has(p,5))return 4;if(has(p,3))return 6;return 0;}if(t.equals("vertical")){if(Arrays.equals(p,new int[]{0,6,4}))return 1;if(p[0]==p[1]||p[0]==p[2]||p[1]==p[2])return 7;if(has(p,4)&&has(p,0)&&has(p,3))return 5;if(p[1]==7||p[1]==1)return 4;if(has(p,6)&&has(p,5))return 6;if(has(p,4))return 2;return 0;}if(p[0]==p[2])return 3;if((p[0]==3||p[1]==3)&&(p[1]==0||p[2]==0))return 1;if(has(p,7)&&has(p,6))return 7;if(p[2]==1)return 2;if(p[1]==2||p[1]==4)return 6;if(has(p,0))return 0;return 4;}
 private static int second(String t,int[]p,BombEntity b){if(b.getBatteryCount()==2&&b.isIndicatorLit("BOB")&&b.getIndicators().containsKey("SIG")&&!b.isIndicatorLit("SIG"))return 5;if(b.getBatteryCount()>=3&&t.equals("nordic-2"))return venn(p[0],b);long lit=b.getIndicators().values().stream().filter(Boolean.TRUE::equals).count(),unlit=b.getIndicators().size()-lit;if(t.equals("horizontal")&&lit>=2)return 2;if(b.getPortPlates().stream().anyMatch(x->x.getPorts().isEmpty()))return 7;if(b.hasPort(PortType.STEREO_RCA)&&b.hasPort(PortType.PARALLEL))return 0;if(unlit>lit)return 4;if(b.hasPort(PortType.SERIAL))return 3;return 6;}
 private static int venn(int firstPole,BombEntity b){String serial=b.getSerialNumber()==null?"":b.getSerialNumber().toUpperCase(Locale.ROOT);int m=(serial.indexOf(Character.toUpperCase(C.get(firstPole).charAt(0)))>=0?8:0)|(b.hasPort(PortType.PS2)?4:0)|(b.getIndicators().size()>=2?2:0)|(b.getLastDigit()>=5?1:0);return new int[]{0,6,1,2,7,4,0,4,4,3,6,7,2,1,3,5}[m];}
 private static void transpose(List<Integer>x){for(int i=1;i<x.size();i++)if(x.subList(0,i).contains(x.get(i)))for(int candidate:T[x.get(i)])if(!x.subList(0,i).contains(candidate)){x.set(i,candidate);break;}if(x.size()==3&&x.get(1).equals(x.get(2)))for(int candidate:T[x.get(2)])if(candidate!=x.get(0)&&candidate!=x.get(1)){x.set(2,candidate);break;}}
 private static String key(String t,List<Integer>x){return t+":"+String.join(",",x.stream().map(C::get).toList());}private static Map.Entry<String,String[]>e(String k,String name,String digit){return Map.entry(k,new String[]{name,digit});}private static boolean has(int[]x,int v){return Arrays.stream(x).anyMatch(n->n==v);}private static boolean two(int[]x,int v){return Arrays.stream(x).filter(n->n==v).count()>=2;}private static String n(String s){return s==null?"":s.trim().toLowerCase(Locale.ROOT);}
}
