package ktanesolver.module.modded.regular.freeparking;

import java.util.*;import org.springframework.stereotype.Service;import ktanesolver.annotation.ModuleInfo;import ktanesolver.dto.ModuleCatalogDto;import ktanesolver.entity.*;import ktanesolver.enums.ModuleType;import ktanesolver.logic.*;

@Service @ModuleInfo(type=ModuleType.FREE_PARKING,id="freeParking",name="Free Parking",category=ModuleCatalogDto.ModuleCategory.MODDED_REGULAR,description="Calculate the Monopoly payment from the token, bomb modules, solves, and strikes.",tags={"calculation","modules","souvenir"})
public class FreeParkingSolver extends AbstractModuleSolver<FreeParkingSolver.Input,FreeParkingSolver.Output>{
 public record Input(String token)implements ModuleInput{} public record Output(String token,int payment,String twitchCommand,String specialRule)implements ModuleOutput{}
 private static final List<String>TOKENS=List.of("Dog","Wheelbarrow","Cat","Iron","Top Hat","Car","Battleship");private static final int[]SOLVED={100,20,150,10,75,200,50};
 private static final Map<ModuleType,int[]>ADJ=Map.ofEntries(
  Map.entry(ModuleType.LAUNDRY,new int[]{199,46,203,1045,-52,209,62}),Map.entry(ModuleType.COOKING,new int[]{199,46,203,1045,-52,209,62}),Map.entry(ModuleType.SINK,new int[]{199,46,203,1045,-52,209,62}),
  Map.entry(ModuleType.HIEROGLYPHICS,new int[]{-123,7,1010,-43,107,-25,78}),Map.entry(ModuleType.LIONS_SHARE,new int[]{-123,7,1010,-43,107,-25,78}),
  Map.entry(ModuleType.MAINTENANCE,new int[]{-77,49,56,-15,-168,1234,89}),Map.entry(ModuleType.GRIDLOCK,new int[]{-77,49,56,-15,-168,1234,89}),
  Map.entry(ModuleType.BRITISH_SLANG,new int[]{32,77,-204,33,1017,-541,-47}),Map.entry(ModuleType.LONDON_UNDERGROUND,new int[]{32,77,-204,33,1017,-541,-47}),
  Map.entry(ModuleType.ONE_HUNDRED_AND_ONE_DALMATIANS,new int[]{1001,33,-505,-55,22,-101,-44}),Map.entry(ModuleType.RETIREMENT,new int[]{201,1127,246,113,120,533,-21}),
  Map.entry(ModuleType.BATTLESHIP,new int[]{-47,-72,152,38,53,-217,1006}),Map.entry(ModuleType.MARITIME_FLAGS,new int[]{-47,-72,152,38,53,-217,1006}),Map.entry(ModuleType.SEMAPHORE,new int[]{-47,-72,152,38,53,-217,1006}),Map.entry(ModuleType.MORSE_WAR,new int[]{-47,-72,152,38,53,-217,1006}));
 @Override protected SolveResult<Output> doSolve(RoundEntity r,BombEntity b,ModuleEntity m,Input in){int t=in==null?-1:index(in.token());if(t<0)return failure("Choose one of the seven token names");storeState(m,"freeParkingToken",TOKENS.get(t));if(b.hasIndicator("BOB"))return success(out(t,0,"BOB"));Set<ModuleType>types=new HashSet<>();b.getModules().forEach(x->types.add(x.getType()));long vaults=java.util.stream.Stream.of(ModuleType.BURGLAR_ALARM,ModuleType.SAFETY_SAFE,ModuleType.JEWEL_VAULT).filter(types::contains).count(),doubles=b.getModules().stream().filter(x->Set.of(ModuleType.DOUBLE_COLOR,ModuleType.DOUBLE_OH,ModuleType.CURSED_DOUBLE_OH).contains(x.getType())).count();if(vaults>=2||doubles>=3)return success(out(t,0,"Go to jail"));if(allSolved(b,ModuleType.JEWEL_VAULT)&&allSolved(b,ModuleType.SILLY_SLOTS)&&allSolved(b,ModuleType.CHEAP_CHECKOUT))return success(out(t,0,"Bankrupt"));String digits=b.getSerialNumber().replaceAll("\\D","");int value=digits.isEmpty()?0:Integer.parseInt(digits);for(ModuleEntity x:b.getModules()){int[]a=ADJ.get(x.getType());if(a!=null)value+=a[t];}value+=(int)b.getModules().stream().filter(ModuleEntity::isSolved).count()*SOLVED[t]-b.getStrikes()*200;value=Math.max(0,value);if(value>5000)value%=5000;return success(out(t,value,"Pay"));}
 private static Output out(int t,int v,String why){return new Output(TOKENS.get(t),v,why.equals("Go to jail")?"go to jail":"pay $"+v,why);}private static int index(String s){if(s==null)return-1;for(int i=0;i<TOKENS.size();i++)if(TOKENS.get(i).equalsIgnoreCase(s.trim()))return i;return-1;}private static boolean allSolved(BombEntity b,ModuleType t){List<ModuleEntity>x=b.getModules().stream().filter(m->m.getType()==t).toList();return !x.isEmpty()&&x.stream().allMatch(ModuleEntity::isSolved);}
}
