package ktanesolver.module.modded.regular.benedictcumberbatch;

import java.util.List;import java.util.Locale;import java.util.Set;
import org.springframework.stereotype.Service;
import ktanesolver.annotation.ModuleInfo;import ktanesolver.dto.ModuleCatalogDto;import ktanesolver.entity.BombEntity;import ktanesolver.entity.ModuleEntity;import ktanesolver.entity.RoundEntity;import ktanesolver.enums.ModuleType;import ktanesolver.enums.PortType;import ktanesolver.logic.AbstractModuleSolver;import ktanesolver.logic.SolveResult;

@Service
@ModuleInfo(type=ModuleType.BENEDICT_CUMBERBATCH,id="benedictCumberbatch",name="Benedict Cumberbatch",category=ModuleCatalogDto.ModuleCategory.MODDED_REGULAR,description="Calculate both rolodex suffixes for Benedict Cumberbatch's meme name.",tags={"words","edgework","rolodex","names"})
public class BenedictCumberbatchSolver extends AbstractModuleSolver<BenedictCumberbatchInput,BenedictCumberbatchOutput>{
	public static final List<String> LEFT_LISTS=List.of("BENE","BUMBLE","BURGER","BOMBA","BUNSEN"),RIGHT_LISTS=List.of("CUMBER","CODDLE","CRUMPLE","CALL","CABBAGE");
	private static final String[][] LEFT={{"dict","dryl","drive","dink","bus","juice","snatch","ton","saur","dang"},{"bee","boi","basher","bong","buzz","stick","pest","blaster","berry","milk"},{"king","dil","coot","top","trap","burg","boop","dirk","bub","cash"},{"boom","bait","butt","blast","stic","dick","buck","blow","tonk","ray"},{"burner","swick","don","snap","whale","rock","box","town","shack","ster"}};
	private static final String[][] RIGHT={{"batch","thatch","snatch","bund","cooch","sniff","stick","dell","bath","chord"},{"swort","cheese","clock","sore","bath","dinck","snoot","sniff","some","wealth"},{"sack","horn","rash","fish","butt","pants","crush","mite","clomp","fish"},{"dispatch","d'captain","'ur'mum","'ya'boi","'m'lady","ghostbusters","'d'police","'fur'help","ing'vienna","a'vote"},{"patch","butt","horn","man","sprout","dong","ship","rash","snutch","flage"}};
	private static final Set<String> LEFT_SPECIAL=Set.of("BROCCOLI","BUFFALO","SYPHILIS","CADBURY"),RIGHT_SPECIAL=Set.of("BONAPARTE","OXFORDSHIRE","TALISMAN","LINGERIE");
	@Override protected SolveResult<BenedictCumberbatchOutput> doSolve(RoundEntity round,BombEntity bomb,ModuleEntity module,BenedictCumberbatchInput input){if(input==null)return failure("Enter both displayed prefixes and suffix-list headings");String lp=up(input.leftPrefix()),ll=up(input.leftList()),rp=up(input.rightPrefix()),rl=up(input.rightList());int li=LEFT_LISTS.indexOf(ll),ri=RIGHT_LISTS.indexOf(rl);if(lp.isBlank()||rp.isBlank()||li<0||ri<0)return failure("Unknown prefix or suffix list");if(!LEFT_SPECIAL.contains(lp)&&!lp.equals(ll))return failure("The forename list does not match its normal prefix");if(!RIGHT_SPECIAL.contains(rp)&&!rp.equals(rl))return failure("The surname list does not match its normal prefix");int left=LEFT_SPECIAL.contains(lp)?0:leftIndex(bomb),right=RIGHT_SPECIAL.contains(rp)?0:rightIndex(bomb);String ls=LEFT[li][left],rs=RIGHT[ri][right];return success(new BenedictCumberbatchOutput(left,right,ls,rs,input.leftPrefix().trim()+ls,input.rightPrefix().trim()+rs));}
	private static int leftIndex(BombEntity b){int n=0;String serial=up(b.getSerialNumber());boolean vowel=serial.chars().anyMatch(c->"AEIOU".indexOf(c)>=0);long digits=serial.chars().filter(Character::isDigit).count(),letters=serial.chars().filter(Character::isLetter).count();int total=b.getModules().size(),solved=(int)b.getModules().stream().filter(ModuleEntity::isSolved).count();boolean moreHalf=solved>total/2;if(b.hasPort(PortType.PARALLEL))n++;if(vowel)n++;if(moreHalf)n++;if(b.hasPort(PortType.SERIAL))n+=2;if(!vowel)n+=2;if(!moreHalf)n+=2;if(b.isIndicatorLit("FRK"))n=n*2+3;if(digits>letters)n=n*2+4;if(b.isLastDigitEven())n=n*2+5;if(b.isIndicatorUnlit("NSA"))n=n*3+6;if(letters>digits)n=n*3+7;if(b.isLastDigitOdd())n=n*3+8;return n%10;}
	private static int rightIndex(BombEntity b){int n=0;List<PortType>ports=b.getPortPlates().stream().flatMap(p->p.getPorts().stream()).toList();long types=ports.stream().distinct().count();boolean duplicate=types!=ports.size();if(b.hasPort(PortType.STEREO_RCA))n++;if(b.getBatteryCount()>2)n++;if(duplicate)n++;if(b.hasPort(PortType.RJ45))n+=2;if(b.getBatteryCount()<2)n+=2;if(!duplicate)n+=2;if(b.isIndicatorLit("FRQ"))n=n*2+3;if(types>1)n=n*2+4;if(b.getBatteryHolders()>1)n=n*2+5;if(b.isIndicatorUnlit("MSA"))n=n*3+6;if(types==1)n=n*3+7;if(b.getBatteryHolders()<1)n=n*3+8;return n%10;}
	private static String up(String s){return s==null?"":s.trim().toUpperCase(Locale.ROOT);}
}
