package ktanesolver.module.modded.regular.simonspins;
import static org.assertj.core.api.Assertions.assertThat;import java.util.*;import org.junit.jupiter.api.Test;import ktanesolver.entity.*;import ktanesolver.logic.*;
class SimonSpinsSolverTest{
 private final SimonSpinsSolver solver=new SimonSpinsSolver();private final BombEntity bomb=bomb();private final ModuleEntity module=new ModuleEntity();
 @Test void carriesRememberedPropertiesAcrossRerandomizedStages(){
  SimonSpinsOutput one=solve(new SimonSpinsInput(1,Map.of("LEVEL",List.of("TOP","MIDDLE","BOTTOM"),"FACE_COLOR",List.of("RED","YELLOW","BLUE")),false));assertThat(one.presses()).containsExactly("CIRCLE");assertThat(one.remembered()).containsExactly("FACE_COLOR=RED");assertThat(one.requiredPropertiesForNextStage()).containsExactly("FACE_COLOR","BACK_SYMBOL");
  SimonSpinsOutput two=solve(new SimonSpinsInput(2,Map.of("FACE_COLOR",List.of("BLUE","RED","YELLOW"),"BACK_SYMBOL",List.of("CIRCLE","SQUARE","STAR")),false));assertThat(two.presses()).containsExactly("PENTAGON","SQUARE");assertThat(two.remembered()).containsExactly("FACE_COLOR=RED","BACK_SYMBOL=STAR");
  SimonSpinsOutput three=solve(new SimonSpinsInput(3,Map.of("FACE_COLOR",List.of("RED","BLUE","YELLOW"),"BACK_SYMBOL",List.of("CIRCLE","STAR","SQUARE"),"PROTRUSION_PLACEMENT",List.of("RIGHT","LEFT","OUTSIDE")),false));assertThat(three.presses()).containsExactly("CIRCLE","PENTAGON","CIRCLE");assertThat(three.remembered()).containsExactly("FACE_COLOR=RED","BACK_SYMBOL=STAR","PROTRUSION_PLACEMENT=RIGHT");
 }
 @Test void usesSerialRowsWrapsAndAllowsStageOneReset(){assertThat(SimonSpinsSolver.startRow(bomb("AB4CD7"))).isEqualTo(14);assertThat(SimonSpinsSolver.requiredRows(19,2)).containsExactly(0,1);solve(new SimonSpinsInput(1,Map.of("LEVEL",List.of("TOP","MIDDLE","BOTTOM"),"FACE_COLOR",List.of("RED","YELLOW","BLUE")),false));assertThat(result(new SimonSpinsInput(3,Map.of(),false))).isInstanceOf(SolveFailure.class);SimonSpinsOutput reset=solve(new SimonSpinsInput(1,Map.of("LEVEL",List.of("BOTTOM","TOP","MIDDLE"),"FACE_COLOR",List.of("BLUE","RED","YELLOW")),false));assertThat(reset.presses()).containsExactly("PENTAGON");}
 @Test void validatesPermutationsAndConfirmsUnknownFinalStage(){assertThat(result(new SimonSpinsInput(1,Map.of("LEVEL",List.of("TOP","TOP","BOTTOM"),"FACE_COLOR",List.of("RED","YELLOW","BLUE")),false))).isInstanceOf(SolveFailure.class);assertThat(result(new SimonSpinsInput(null,null,true))).isInstanceOf(SolveFailure.class);solve(new SimonSpinsInput(1,Map.of("LEVEL",List.of("TOP","MIDDLE","BOTTOM"),"FACE_COLOR",List.of("RED","YELLOW","BLUE")),false));SolveSuccess<SimonSpinsOutput>confirmed=(SolveSuccess<SimonSpinsOutput>)result(new SimonSpinsInput(null,null,true));assertThat(confirmed.solved()).isTrue();assertThat(confirmed.output().confirmedSolved()).isTrue();}
 private SimonSpinsOutput solve(SimonSpinsInput input){return((SolveSuccess<SimonSpinsOutput>)result(input)).output();}private Object result(SimonSpinsInput input){return solver.solve(new RoundEntity(),bomb,module,input);}private static BombEntity bomb(){return bomb("AB0CD0");}private static BombEntity bomb(String serial){BombEntity b=new BombEntity();b.setSerialNumber(serial);return b;}
}
