package ktanesolver.module.modded.regular.varicoloredsquares;

import java.util.*;import org.springframework.stereotype.Service;import ktanesolver.annotation.ModuleInfo;import ktanesolver.dto.ModuleCatalogDto;import ktanesolver.entity.*;import ktanesolver.enums.ModuleType;import ktanesolver.logic.*;

@Service @ModuleInfo(type=ModuleType.VARICOLORED_SQUARES,id="VaricoloredSquaresModule",name="Varicolored Squares",category=ModuleCatalogDto.ModuleCategory.MODDED_REGULAR,description="Determine every currently valid square from the flashing square and adjacent colors.",tags={"colored squares","grid","souvenir"})
public class VaricoloredSquaresSolver extends AbstractModuleSolver<VaricoloredSquaresSolver.Input,VaricoloredSquaresSolver.Output>{
 public record Input(List<String> colors,Integer flashingPosition)implements ModuleInput{} public record Output(String targetColor,List<Integer> pressPositions,List<String> coordinates,String twitchCommand)implements ModuleOutput{} public record State(String initialColor,String lastPressedColor){public State(){this(null,null);}}
 private static final List<String>ALL=List.of("Red","Green","Blue","Yellow","Magenta");private static final Map<String,List<String>>P=Map.of("Blue",chars("YBRMG"),"Red",chars("BRMYG"),"Magenta",chars("GYRBM"),"Yellow",chars("RMBYG"),"Green",chars("RYBMG"));
 @Override protected SolveResult<Output> doSolve(RoundEntity r,BombEntity b,ModuleEntity m,Input in){if(in==null||in.colors()==null||in.colors().size()!=16)return failure("Enter all 16 square colors");List<String>g=new ArrayList<>();for(String x:in.colors()){String c=color(x);if(c==null)return failure("Colors must be Red, Green, Blue, Yellow, or Magenta");g.add(c);}if(g.stream().distinct().count()==1)return success(new Output(g.get(0),List.of(),List.of(),""));State s=m.getStateAs(State.class,State::new);if(s.initialColor()==null){Map<String,Long>counts=new HashMap<>();ALL.forEach(c->counts.put(c,g.stream().filter(c::equals).count()));List<String>four=ALL.stream().filter(c->counts.get(c)==4).toList();if(four.size()!=1||ALL.stream().anyMatch(c->counts.get(c)!=4&&counts.get(c)!=3))return failure("Initial grid must contain one color four times and every other color three times");String target=four.get(0);List<Integer>pos=positions(g,target);storeTypedState(m,new State(target,target));storeState(m,"varicoloredInitialColor",target);return success(out(target,pos),false);}if(in.flashingPosition()==null||in.flashingPosition()<1||in.flashingPosition()>16)return failure("Enter the position of the flashing square");int ix=in.flashingPosition()-1;List<String>pent=P.get(g.get(ix));List<String>adj=neighbors(ix).stream().map(g::get).distinct().sorted(Comparator.comparingInt(pent::indexOf)).toList();String next;if(adj.size()==1)next=pent.get((pent.indexOf(adj.get(0))+1)%5);else if(adj.size()==2)next=pair(pent,adj);else if(adj.size()==3){List<String>missing=ALL.stream().filter(x->!adj.contains(x)).sorted(Comparator.comparingInt(pent::indexOf)).toList();next=pair(pent,missing);}else if(adj.size()==4)next=ALL.stream().filter(x->!adj.contains(x)).findFirst().orElseThrow();else return failure("The flashing square has no orthogonally adjacent colors");int guard=0;while((next.equals(s.lastPressedColor())||!g.contains(next))&&guard++<5)next=pent.get(Math.floorMod(pent.indexOf(next)-1,5));List<Integer>pos=positions(g,next);storeTypedState(m,new State(s.initialColor(),g.get(ix)));storeState(m,"varicoloredInitialColor",s.initialColor());return success(out(next,pos),false);}
 private static Output out(String c,List<Integer>p){List<String>q=p.stream().map(VaricoloredSquaresSolver::coord).toList();return new Output(c,p,q,String.join(" ",q));}private static String pair(List<String>p,List<String>x){int a=p.indexOf(x.get(0)),b=p.indexOf(x.get(1));if(b-a==1)return p.get((b+2)%5);if(a-b==-4)return p.get((a+2)%5);return (a+b)%2==0?p.get((a+b)/2):p.get((b+1)%5);}private static List<Integer>neighbors(int i){List<Integer>n=new ArrayList<>();if(i>=4)n.add(i-4);if(i<12)n.add(i+4);if(i%4>0)n.add(i-1);if(i%4<3)n.add(i+1);return n;}private static List<Integer>positions(List<String>g,String c){List<Integer>p=new ArrayList<>();for(int i=0;i<16;i++)if(g.get(i).equals(c))p.add(i+1);return p;}private static String coord(int p){return "ABCD".charAt((p-1)%4)+Integer.toString((p-1)/4+1);}private static List<String>chars(String s){return s.chars().mapToObj(c->color(Character.toString(c))).toList();}private static String color(String s){if(s==null)return null;return ALL.stream().filter(x->x.equalsIgnoreCase(s)||(s.length()==1&&Character.toUpperCase(s.charAt(0))==x.charAt(0))).findFirst().orElse(null);}
}
