package ktanesolver.module.modded.regular.connectiondevice;import static org.assertj.core.api.Assertions.assertThat;import java.util.*;import org.junit.jupiter.api.Test;import ktanesolver.entity.*;import ktanesolver.enums.*;import ktanesolver.logic.*;import ktanesolver.module.modded.regular.connectiondevice.ConnectionDeviceInput.BatterySet;
class ConnectionDeviceSolverTest{private final ConnectionDeviceSolver solver=new ConnectionDeviceSolver();
	@Test void choosesAppsInPriorityOrder(){assertThat(ConnectionDeviceSolver.app("WAB99","D12ABC")).isEqualTo("Whatsapp");assertThat(ConnectionDeviceSolver.app("DAB12","C34EF5")).isEqualTo("Discord");assertThat(ConnectionDeviceSolver.app("DAB12","Z34EF5")).isEqualTo("Skype");}
	@Test void buildsWhatsappCodeForFirstSupportedPort(){BombEntity b=bomb("A1BC9D",Map.of(),Set.of(PortType.SERIAL,PortType.DVI));ConnectionDeviceOutput out=solve(b,new ConnectionDeviceInput("WAB99","DVIABXZ","0123456",BatterySet.NAN));assertThat(out.app()).isEqualTo("Whatsapp");assertThat(out.requiredToken()).isEqualTo("DVI");assertThat(out.code()).startsWith("1").endsWith("0").contains("DVI").contains("A");assertThat(out.timerDigitSum()).isEqualTo(1);assertThat(out.timerSecond()).isEqualTo("01");}
	@Test void sourceDiscordLeadingFiveAndBobDuplicatesAreAllowed(){Set<Character>keys=new LinkedHashSet<>();"5BOBAXY0123467".chars().forEach(c->keys.add((char)c));String code=ConnectionDeviceSolver.findCode("Discord","BOB",'A',keys);assertThat(code).isNotNull().startsWith("5").contains("BOB").contains("A");}
	@Test void buildsDiscordAndUsesLastSerialDigit(){BombEntity b=bomb("C1AB7D",Map.of("CAR",true,"SND",false),Set.of());ConnectionDeviceOutput out=solve(b,new ConnectionDeviceInput("DAB12","SNDCAXY","0123456",BatterySet.NAN));assertThat(out.app()).isEqualTo("Discord");assertThat(out.requiredToken()).isEqualTo("SND");assertThat(out.timerDigitSum()).isEqualTo(7);}
	@Test void buildsSkypeWithOneRepeatAndDifferenceTiming(){BombEntity b=bomb("V8ABC2",Map.of(),Set.of());ConnectionDeviceOutput out=solve(b,new ConnectionDeviceInput("QWE12","DBTVXYZ","2345678",BatterySet.DBT));assertThat(out.app()).isEqualTo("Skype");assertThat(out.requiredToken()).isEqualTo("DBT");assertThat(out.code()).contains("DBT").contains("V").endsWith("5");assertThat(out.code().chars().distinct().count()).isGreaterThan(4);assertThat(out.timerDigitSum()).isEqualTo(6);assertThat(out.timerSecond()).isEqualTo("06");}
	@Test void timerTenUsesNineteenSeconds(){assertThat(ConnectionDeviceSolver.secondFor(10)).isEqualTo("19");}
	@Test void validatesDeviceAndKeys(){BombEntity b=bomb("A1BC2D",Map.of(),Set.of());assertThat(solver.solve(new RoundEntity(),b,new ModuleEntity(),new ConnectionDeviceInput("BAD","ABCDEFG","0123456",BatterySet.NAN))).isInstanceOf(SolveFailure.class);}
	@SuppressWarnings("unchecked")private ConnectionDeviceOutput solve(BombEntity b,ConnectionDeviceInput i){return((SolveSuccess<ConnectionDeviceOutput>)solver.solve(new RoundEntity(),b,new ModuleEntity(),i)).output();}private static BombEntity bomb(String serial,Map<String,Boolean>indicators,Set<PortType>ports){BombEntity b=new BombEntity();b.setSerialNumber(serial);b.setIndicators(indicators);if(!ports.isEmpty())b.replacePortPlates(List.of(ports));return b;}}
