package ktanesolver.module.modded.regular.detonato;

import java.io.*;import java.nio.charset.StandardCharsets;import java.util.*;import org.springframework.stereotype.Service;import ktanesolver.annotation.ModuleInfo;import ktanesolver.dto.ModuleCatalogDto;import ktanesolver.entity.*;import ktanesolver.enums.ModuleType;import ktanesolver.logic.*;

@Service @ModuleInfo(type=ModuleType.DETONATO,id="Detonato",name="DetoNATO",category=ModuleCatalogDto.ModuleCategory.MODDED_REGULAR,description="Use the displayed NATO-like word's key to select the correct letter for each stage.",tags={"words","ordering","stages","souvenir"})
public class DetonatoSolver extends AbstractModuleSolver<DetonatoSolver.Input,DetonatoSolver.Output>{
 public record Input(String displayedWord,List<String> buttonLetters)implements ModuleInput{} public record Output(int stage,List<String> correctLetters,String twitchCommand)implements ModuleOutput{} public record State(List<String> words){public State(){this(new ArrayList<>());}} private static final Map<String,String>KEYS=load();
 @Override protected SolveResult<Output> doSolve(RoundEntity r,BombEntity b,ModuleEntity m,Input in){if(in==null||in.displayedWord()==null||in.buttonLetters()==null||in.buttonLetters().size()!=4)return failure("Enter the displayed word and four button letters");String key=KEYS.get(in.displayedWord().trim().toLowerCase());if(key==null)return failure("Displayed word was not found in the official DetoNATO table");List<String>letters=in.buttonLetters().stream().map(x->x==null?"":x.trim().toUpperCase()).toList();if(letters.stream().anyMatch(x->x.length()!=1||x.charAt(0)<'A'||x.charAt(0)>'Z')||new HashSet<>(letters).size()!=4)return failure("Enter four different letters A through Z");State s=m.getStateAs(State.class,State::new);int stage=s.words().size();Comparator<String>byKey=Comparator.comparingInt(x->key.indexOf(x));List<String>sorted=letters.stream().sorted(byKey).toList();List<String>correct=switch(stage){case 0->List.of(sorted.get(0));case 1->List.of(sorted.get(3));case 2->List.of(sorted.get(1));case 3->List.of(sorted.get(2));case 4->closest(letters,key,firstLetter(b.getSerialNumber()));case 5->closest(letters,key,Character.toUpperCase(in.displayedWord().trim().charAt(0)));default->List.of();};if(correct.isEmpty())return failure("All six stages are already recorded");List<String>words=new ArrayList<>(s.words());words.add(in.displayedWord().trim());storeTypedState(m,new State(words));storeState(m,"detonatoWords",words);return success(new Output(words.size(),correct,"press "+correct.get(0)),words.size()>=6);}
 private static List<String>closest(List<String>x,String key,char target){int t=key.indexOf(target);int min=x.stream().mapToInt(a->Math.abs(key.indexOf(a)-t)).min().orElse(0);return x.stream().filter(a->Math.abs(key.indexOf(a)-t)==min).toList();}private static char firstLetter(String s){return s.toUpperCase().chars().filter(Character::isLetter).mapToObj(c->(char)c).findFirst().orElse('A');}private static Map<String,String>load(){Map<String,String>m=new HashMap<>();try(InputStream in=DetonatoSolver.class.getResourceAsStream("/ktane/detonato.tsv")){if(in==null)throw new IllegalStateException("Missing detonato.tsv");try(BufferedReader r=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8))){for(String line;(line=r.readLine())!=null;){String[]p=line.split("\\t",2);m.put(p[0].toLowerCase(),p[1]);}}return Map.copyOf(m);}catch(IOException e){throw new ExceptionInInitializerError(e);}}
}
