package ktanesolver.module.modded.regular.giantsdrink;
import java.util.*;import org.springframework.stereotype.Service;import ktanesolver.annotation.ModuleInfo;import ktanesolver.dto.ModuleCatalogDto;import ktanesolver.entity.*;import ktanesolver.enums.ModuleType;import ktanesolver.logic.*;
@Service @ModuleInfo(type=ModuleType.THE_GIANTS_DRINK,id="giantsDrink",name="The Giant's Drink",category=ModuleCatalogDto.ModuleCategory.MODDED_REGULAR,description="Follow the goblet dichotomous key to identify the safe drink.",tags={"goblets","dichotomous key","gems","colors"})
public class GiantsDrinkSolver extends AbstractModuleSolver<GiantsDrinkInput,GiantsDrinkOutput>{
 private static final Set<String>MATERIALS=Set.of("gold","silver","bronze","iron"),GEMS=Set.of("diamond","ruby","sapphire","emerald","amber","amethyst","aquamarine","onyx"),LIQUIDS=Set.of("red","blue","green","orange","purple","cyan"),PLACEMENTS=Set.of("bowl","base");
 private static final int[]SHAPE_COUNTS={10,5,12,5,4,4,9,10};private static final String[]SHAPE_PLACEMENTS={"bowl","bowl","base","base","bowl","base","base","bowl"};
 @Override protected SolveResult<GiantsDrinkOutput>doSolve(RoundEntity round,BombEntity bomb,ModuleEntity module,GiantsDrinkInput input){if(input==null||!valid(input.left())||!valid(input.right()))return failure("Enter both goblets' material, gem, liquid, height, gem count, and gem placement");GiantsDrinkInput.Goblet[]g={normal(input.left()),normal(input.right())};int p=bomb.getStrikes()%2==0?0:1,k=1;List<Integer>path=new ArrayList<>();while(true){path.add(k);switch(k){case 1->k=Set.of("silver","gold").contains(g[p].material())?2:17;case 2->k=g[p].gemCount()>=8?3:10;case 3->k=in(g[p].gem(),"diamond","ruby","sapphire")?4:7;case 4->k=g[0].material().equals(g[1].material())?5:6;case 5->{return result(g[p].liquid().equals("red")||g[p].liquid().equals("blue")?p:1-p,path);}case 6->{return result(in(g[p].liquid(),"green","orange")?1:0,path);}case 7->k=in(g[p].liquid(),"purple","cyan")?8:9;case 8->{return result(sameColor(g[p])?0:1,path);}case 9->{return result(sameShape(g[0],g[1])?1-p:p,path);}case 10->k=g[p].heightRank()>g[1-p].heightRank()?11:14;case 11->k=in(g[p].gem(),"emerald","amber","amethyst")?12:13;case 12->{return result(in(g[p].liquid(),"red","orange")?1:0,path);}case 13->{return result(in(g[p].liquid(),"green","purple")?1-p:p,path);}case 14->k=g[p].gemPlacement().equals("bowl")?15:16;case 15->{return result(in(g[p].gem(),"diamond","aquamarine","onyx")?p:1-p,path);}case 16->{return result(g[0].gem().equals(g[1].gem())?0:1,path);}case 17->k=g[p].heightRank()<g[1-p].heightRank()?18:25;case 18->k=in(g[p].liquid(),"blue","cyan")?19:22;case 19->k=g[p].gemCount()<=7?20:21;case 20->{return result(in(g[p].gem(),"ruby","emerald","onyx")?0:1,path);}case 21->{return result(in(g[p].gem(),"sapphire","amber","aquamarine")?p:1-p,path);}case 22->k=in(g[p].gem(),"ruby","amethyst","onyx")?23:24;case 23->{return result(g[p].material().equals("bronze")?1-p:p,path);}case 24->{return result(g[p].material().equals("iron")?1:0,path);}case 25->k=g[p].gemPlacement().equals("base")?26:29;case 26->k=in(g[p].gem(),"sapphire","emerald","amethyst")?27:28;case 27->{return result(in(g[p].liquid(),"red","purple")?1-p:p,path);}case 28->{return result(in(g[p].liquid(),"green","cyan")?0:1,path);}case 29->k=in(g[p].liquid(),"blue","orange")?30:31;case 30->{return result(in(g[p].gem(),"diamond","amber","onyx")?0:1,path);}default->{return result(in(g[p].gem(),"ruby","amethyst","aquamarine")?p:1-p,path);}}}}
 private static SolveResult<GiantsDrinkOutput>result(int safe,List<Integer>path){String s=safe==0?"left":"right";return new SolveSuccess<>(new GiantsDrinkOutput(s,safe==0?"right":"left",List.copyOf(path),s),true);}
 private static boolean valid(GiantsDrinkInput.Goblet g){if(g==null)return false;GiantsDrinkInput.Goblet n=normal(g);int h=n.heightRank();return MATERIALS.contains(n.material())&&GEMS.contains(n.gem())&&LIQUIDS.contains(n.liquid())&&h>=1&&h<=8&&PLACEMENTS.contains(n.gemPlacement())&&n.gemCount()==SHAPE_COUNTS[h-1]&&n.gemPlacement().equals(SHAPE_PLACEMENTS[h-1]);}
 private static GiantsDrinkInput.Goblet normal(GiantsDrinkInput.Goblet g){return new GiantsDrinkInput.Goblet(low(g.material()),low(g.gem()),low(g.liquid()),g.heightRank(),g.gemCount(),low(g.gemPlacement()));}private static String low(String s){return s==null?"":s.trim().toLowerCase(Locale.ROOT);}private static boolean in(String v,String...x){return Arrays.asList(x).contains(v);}private static boolean sameShape(GiantsDrinkInput.Goblet a,GiantsDrinkInput.Goblet b){return a.heightRank()==b.heightRank()&&a.gemCount()==b.gemCount()&&a.gemPlacement().equals(b.gemPlacement());}private static boolean sameColor(GiantsDrinkInput.Goblet g){return switch(g.gem()){case"ruby"->g.liquid().equals("red");case"sapphire"->g.liquid().equals("blue");case"emerald"->g.liquid().equals("green");case"amethyst"->g.liquid().equals("purple");case"aquamarine"->g.liquid().equals("cyan");default->false;};}
}
