package ktanesolver.module.modded.regular.bartending;

import java.util.*;import java.util.stream.*;import org.springframework.stereotype.Service;import ktanesolver.annotation.ModuleInfo;import ktanesolver.dto.ModuleCatalogDto;import ktanesolver.entity.*;import ktanesolver.enums.ModuleType;import ktanesolver.logic.*;

@Service @ModuleInfo(type=ModuleType.BARTENDING,id="BartendingModule",name="Bartending",category=ModuleCatalogDto.ModuleCategory.MODDED_REGULAR,description="Determine the patron's one or two drinks and provide exact preparation commands.",tags={"recipes","calculation","souvenir"})
public class BartendingSolver extends AbstractModuleSolver<BartendingSolver.Input,BartendingSolver.Output>{
 public record Input(List<String> ingredients)implements ModuleInput{} public record Recipe(String drink,List<Integer> amounts,boolean aged,boolean iced,String preparation,boolean bottled,boolean big){} public record Output(String patron,List<Recipe> drinks,List<String> twitchCommands)implements ModuleOutput{}
 private static final List<String>INGS=List.of("Powdered Delta","Flanergide","Adelhyde","Bronson Extract","Karmotrine"),PATRONS=List.of("Barbara","Patricia","Karl","Konrad","Vivi","Angelika","Donna","Gabe","Clayton","Chip");private static final Map<String,Recipe>RECIPES=new LinkedHashMap<>();private static final List<List<String>>PREFS=new ArrayList<>();static{
  recipe("Beer","1,2,1,2,4",false,false,"Mixed");recipe("Fluffy Dream","3,0,3,0,2",true,false,"Mixed");recipe("Bleeding Jane","3,3,0,1,4",false,false,"Blended");recipe("Sugar Rush","1,0,2,0,4",false,false,"Mixed");recipe("Piano Man","1,1,6,3,2",false,true,"Blended");recipe("Moonblast","1,1,6,0,2",false,true,"Blended");recipe("Fringe Weaver","0,0,1,0,9",true,false,"Mixed");recipe("Blue Fairy","0,1,4,0,5",true,false,"Mixed");recipe("Grizzly Temple","3,0,3,3,1",false,false,"Blended");recipe("Bloom Light","1,2,4,0,3",true,true,"Mixed");recipe("Frothy Water","1,1,1,1,0",true,false,"Mixed");recipe("Piano Woman","2,3,5,5,3",true,false,"Mixed");for(String x:List.of("Absinthe","Rum","Mulan Tea","A Fedora"))RECIPES.put(x,new Recipe(x,List.of(0,0,0,0,0),false,false,"Bottled",true,false));
  String data="Blue Fairy,Piano Man,Frothy Water,Piano Woman,Fringe Weaver,Absinthe;Frothy Water,Piano Woman,Fringe Weaver,Grizzly Temple,A Fedora,Rum;Piano Man,Rum,Grizzly Temple,Mulan Tea,Absinthe,Frothy Water;Mulan Tea,Frothy Water,Fluffy Dream,Bleeding Jane,Rum,A Fedora;Fluffy Dream,Moonblast,Absinthe,Piano Man,Beer,Fringe Weaver;Piano Woman,Blue Fairy,A Fedora,Absinthe,Bleeding Jane,Grizzly Temple;Beer,Sugar Rush,Piano Woman,Bloom Light,Moonblast,Mulan Tea;Moonblast,Mulan Tea,Sugar Rush,A Fedora,Frothy Water,Bloom Light;Grizzly Temple,Bloom Light,Bleeding Jane,Fringe Weaver,Piano Man,Beer;Bleeding Jane,Grizzly Temple,Moonblast,Sugar Rush,Blue Fairy,Fluffy Dream";for(String row:data.split(";"))PREFS.add(List.of(row.split(",")));
 }
 @Override protected SolveResult<Output> doSolve(RoundEntity r,BombEntity b,ModuleEntity m,Input in){if(in==null||in.ingredients()==null||in.ingredients().size()!=5)return failure("Enter the five ingredient names from left to right");List<Integer>values=new ArrayList<>();for(String x:in.ingredients()){int i=index(INGS,x);if(i<0)return failure("Unknown ingredient: "+x);values.add(i+1);}if(new HashSet<>(values).size()!=5)return failure("Use every ingredient exactly once");int patron=(values.get(0)*2+values.get(1))%10,first=Math.max((values.get(3)*2+values.get(4))%7,1)-1;List<Integer>ix=new ArrayList<>(List.of(first));long chaser=b.getSerialNumber().chars().distinct().filter(c->"CH4S3R".indexOf(c)>=0).count();if(chaser>=3)ix.add((first+values.get(2))%6);Collections.sort(ix);boolean big=b.getSerialNumber().chars().anyMatch(c->"B1G".indexOf(c)>=0);List<Recipe>drinks=ix.stream().map(i->scaled(RECIPES.get(PREFS.get(patron).get(i)),big)).toList();List<String>commands=new ArrayList<>();for(int slot=0;slot<drinks.size();slot++)commands.addAll(commands(drinks.get(slot),slot+1,in.ingredients()));commands.add("serve");storeState(m,"bartendingIngredients",in.ingredients());return success(new Output(PATRONS.get(patron),drinks,commands));}
 private static void recipe(String n,String amounts,boolean aged,boolean iced,String prep){RECIPES.put(n,new Recipe(n,Arrays.stream(amounts.split(",")).map(Integer::parseInt).toList(),aged,iced,prep,false,false));}private static Recipe scaled(Recipe r,boolean big){return r.bottled()?r:new Recipe(r.drink(),r.amounts().stream().map(x->big?x*2:x).toList(),r.aged(),r.iced(),r.preparation(),false,big);}private static List<String>commands(Recipe r,int slot,List<String>screen){List<String>c=new ArrayList<>();c.add("slot "+slot);if(r.bottled()){c.add("bottled "+r.drink());return c;}List<String>a=new ArrayList<>();for(int ingredient=0;ingredient<5;ingredient++){int amount=r.amounts().get(ingredient);if(amount>0)a.add((index(screen,INGS.get(ingredient))+1)+" "+amount);}c.add("add "+String.join(", ",a));if(r.iced())c.add("iced");if(r.aged())c.add("aged");c.add("mix "+(r.preparation().equals("Blended")?7:4));return c;}private static int index(List<String>x,String s){if(s==null)return-1;for(int i=0;i<x.size();i++)if(x.get(i).equalsIgnoreCase(s.trim()))return i;return-1;}
}
