package ktanesolver.module.modded.regular.decoloredsquares;

import java.util.*;import org.springframework.stereotype.Service;import ktanesolver.annotation.ModuleInfo;import ktanesolver.dto.ModuleCatalogDto;import ktanesolver.entity.*;import ktanesolver.enums.ModuleType;import ktanesolver.logic.*;

@Service @ModuleInfo(type=ModuleType.DECOLORED_SQUARES,id="DecoloredSquaresModule",name="Decolored Squares",category=ModuleCatalogDto.ModuleCategory.MODDED_REGULAR,description="Walk the default-rule-seed flowchart to find the next colored square.",tags={"colored squares","flowchart","souvenir"})
public class DecoloredSquaresSolver extends AbstractModuleSolver<DecoloredSquaresSolver.Input,DecoloredSquaresSolver.Output>{
 public record Input(List<String> colors)implements ModuleInput{} public record Output(Integer pressPosition,String coordinate,String twitchCommand)implements ModuleOutput{} public record State(int flow,int modulePosition,String columnColor,String rowColor){public State(){this(-1,0,null,null);}}
 private static final List<String>C=List.of("R","G","B","Y","M");private static final String[]SET=new String[36];private static final int[]N=new int[36],Y=new int[36];static{Arrays.fill(N,-1);Arrays.fill(Y,-1);String data="0:B:2:6;2:YGR:0:8;3:BYR:9:2;4:RM:10:5;5:GY:4:11;6:MGRB:0:12;7:RB:6:13;8:BM:20:9;9:R:3:8;10:YGB:4:11;11:YMR:10:17;12:GYRB:6:13;13:YM:16:7;16:RGYM:10:17;17:RY:16:11;18:BG:19:24;19:MBYGR:-1:18;20:M:19:21;21:YB:22:9;22:MRB:28:23;23:G:17:22;24:GRB:26:30;26:BMY:32:27;27:RG:21:28;28:MBRY:22:27;29:YGM:23:35;30:GMR:24:31;31:MGYB:32:19;32::33:-1;33:GM:34:32;34:Y:28:33;35:MBG:34:29";for(String row:data.split(";")){String[]p=row.split(":",-1);int i=Integer.parseInt(p[0]);SET[i]=p[1];N[i]=Integer.parseInt(p[2]);Y[i]=Integer.parseInt(p[3]);}}
 @Override protected SolveResult<Output> doSolve(RoundEntity r,BombEntity b,ModuleEntity m,Input in){if(in==null||in.colors()==null||in.colors().size()!=16)return failure("Enter all 16 grid colors");List<String>g=new ArrayList<>();for(String x:in.colors()){String c=color(x);if(c==null)return failure("Use Red, Green, Blue, Yellow, or Magenta");g.add(c);}State s=m.getStateAs(State.class,State::new);int flow=s.flow(),pos=s.modulePosition();String col=s.columnColor(),row=s.rowColor();if(flow<0){Map<String,Long>counts=new HashMap<>();C.forEach(c->counts.put(c,g.stream().filter(c::equals).count()));long twos=counts.values().stream().filter(x->x==2).count(),fives=counts.values().stream().filter(x->x==5).count();if(twos!=3||fives!=2)return failure("Initial grid must contain three colors twice and two colors five times");col=g.get(1);row=g.get(13);int[]cm={5,2,4,3,0},rm={5,3,0,1,4};flow=cm[C.indexOf(col)]+6*rm[C.indexOf(row)];storeState(m,"decoloredColumnColor",name(col));storeState(m,"decoloredRowColor",name(row));}
  while(pos<16){String allowed=SET[flow];if(allowed!=null&&allowed.contains(g.get(pos))){int nextFlow=Y[flow];int press=pos+1;boolean solved=pos==15||nextFlow<0;storeTypedState(m,new State(nextFlow,pos+1,col,row));String q=coord(press);return success(new Output(press,q,q),solved);}flow=N[flow];pos++;if(flow<0)break;}storeTypedState(m,new State(flow,pos,col,row));return success(new Output(null,null,""));}
 private static String color(String s){if(s==null)return null;String z=s.trim().toUpperCase();if(z.length()==1&&C.contains(z))return z;return switch(z){case"RED"->"R";case"GREEN"->"G";case"BLUE"->"B";case"YELLOW"->"Y";case"MAGENTA"->"M";default->null;};}private static String name(String c){return switch(c){case"R"->"Red";case"G"->"Green";case"B"->"Blue";case"Y"->"Yellow";default->"Magenta";};}private static String coord(int p){return "ABCD".charAt((p-1)%4)+Integer.toString((p-1)/4+1);}
}
