package ktanesolver.module.modded.regular.mazematics;
import java.util.*;import org.springframework.stereotype.Service;import ktanesolver.annotation.ModuleInfo;import ktanesolver.dto.ModuleCatalogDto;import ktanesolver.entity.*;import ktanesolver.enums.ModuleType;import ktanesolver.logic.*;
@Service @ModuleInfo(type=ModuleType.MAZEMATICS,id="mazematics",name="Mazematics",category=ModuleCatalogDto.ModuleCategory.MODDED_REGULAR,description="Navigate the shape-value maze to the goal without reaching restricted values.",tags={"maze","math","shapes","pathfinding"})
public class MazematicsSolver extends AbstractModuleSolver<MazematicsInput,MazematicsOutput>{
 private static final int[][] CELL={{5,6,-4,-2,0,4,-3,-8},{-3,7,-5,-1,3,1,-6,6},{6,-3,1,3,-5,-1,7,-6},{7,-6,-1,4,-7,3,1,-3},{-4,1,6,-8,2,-6,-5,0},{-5,0,-6,2,-8,-7,3,1},{0,-5,7,5,-2,2,-7,-4},{-2,-4,2,-7,5,-8,0,4}};private static final String[] DIR={"up","down","left","right"};private static final int[] DY={-1,1,0,0},DX={0,0,-1,1};
 @Override protected SolveResult<MazematicsOutput> doSolve(RoundEntity r,BombEntity b,ModuleEntity m,MazematicsInput i){if(i==null||i.shapeValues()==null||i.shapeValues().size()!=8||i.shapeValues().stream().anyMatch(v->v==null||v<1||v>9)||new HashSet<>(i.shapeValues()).size()!=8)return failure("Enter eight distinct shape values from 1 to 9");int[] start=coord(i.startCoordinate());if(start==null||i.initialValue()<17||i.initialValue()>32||i.goalValue()<0||i.goalValue()>49)return failure("Enter a coordinate A1-H8 and valid initial and goal values");int[][] maze=maze(i.shapeValues());int startCell=maze[start[1]][start[0]],current=i.initialValue()+startCell;if(current<0||current>49)return failure("The entered starting state is invalid");Restricted restricted=restricted(i.shapeValues(),startCell,i.initialValue());State end=search(maze,start[0],start[1],current,i.goalValue(),restricted.values());if(end==null)return failure("No strike-free path reaches the goal");List<String> moves=new ArrayList<>();List<Integer> totals=new ArrayList<>();for(State s=end;s.parent()!=null;s=s.parent()){moves.add(s.move());totals.add(s.value());}Collections.reverse(moves);Collections.reverse(totals);storeState(m,"mazematicsInitialValue",i.initialValue());storeState(m,"mazematicsGoalValue",i.goalValue());return success(new MazematicsOutput(restricted.name(),moves,totals,"press display "+String.join(" ",moves)));}
 private static State search(int[][] maze,int x,int y,int value,int goal,Set<Integer> banned){ArrayDeque<State> q=new ArrayDeque<>();q.add(new State(x,y,value,0,null,null));Set<String> seen=new HashSet<>();seen.add(x+","+y+","+value+",0");while(!q.isEmpty()){State s=q.remove();for(int d=0;d<4;d++){int nx=Math.floorMod(s.x()+DX[d],8),ny=Math.floorMod(s.y()+DY[d],8),nv=s.value()+maze[ny][nx],count=Math.min(2,s.moves()+1);if(nv<0||nv>49)continue;State n=new State(nx,ny,nv,count,s,DIR[d]);if(count>=2&&nv==goal)return n;if(banned.contains(nv))continue;String key=nx+","+ny+","+nv+","+count;if(seen.add(key))q.add(n);}}return null;}
 private static int[][] maze(List<Integer> v){int[][] a=new int[8][8];for(int y=0;y<8;y++)for(int x=0;x<8;x++){int cell=CELL[y][x];a[y][x]=cell>=0?v.get(cell):-v.get(-cell-1);}return a;}
 private static Restricted restricted(List<Integer> v,int cell,int initial){if(Math.abs(cell)==v.get(1)||Math.abs(cell)==v.get(4))return new Restricted("triangular numbers",Set.of(1,3,6,10,15,21,28,36,45));if(initial%3==0)return new Restricted("multiples of 7",Set.of(0,7,14,21,28,35,42,49));if(cell>0)return new Restricted("prime numbers",Set.of(2,3,5,7,11,13,17,19,23,29,31,37,41,43,47));return new Restricted("Fibonacci numbers",Set.of(1,2,3,5,8,13,21,34));}
 private static int[] coord(String s){if(s==null||!s.trim().toUpperCase(Locale.ROOT).matches("[A-H][1-8]"))return null;String n=s.trim().toUpperCase(Locale.ROOT);return new int[]{n.charAt(0)-'A',n.charAt(1)-'1'};}
 private record Restricted(String name,Set<Integer> values){}private record State(int x,int y,int value,int moves,State parent,String move){}
}
