package ktanesolver.module.modded.regular.curseddoubleoh;
import java.util.*;import org.springframework.stereotype.Service;import ktanesolver.annotation.ModuleInfo;import ktanesolver.dto.ModuleCatalogDto;import ktanesolver.entity.*;import ktanesolver.enums.ModuleType;import ktanesolver.logic.*;
@Service@ModuleInfo(type=ModuleType.CURSED_DOUBLE_OH,id="CursedDoubleOhModule",name="Cursed Double-Oh",category=ModuleCatalogDto.ModuleCategory.MODDED_REGULAR,description="Route the cursed display to 00 without repeating a button or number.",tags={"grid","pathfinding","buttons","souvenir"})
public class CursedDoubleOhSolver extends AbstractModuleSolver<CursedDoubleOhInput,CursedDoubleOhOutput>{
 static final int[]GRID=Arrays.stream(("60 02 15 57 36 83 48 71 24 88 46 31 70 22 64 07 55 13 74 27 53 05 41 18 86 30 62 52 10 04 43 85 37 61 28 76 33 65 78 21 00 56 12 44 87 47 81 26 68 14 72 50 03 35 06 38 42 84 63 20 75 17 51 25 73 67 16 58 01 34 82 40 11 54 80 32 77 45 23 66 08").split(" ")).mapToInt(Integer::parseInt).toArray();
 static final List<String>FUNCTIONS=List.of("SMALL_LEFT","SMALL_RIGHT","SMALL_UP","SMALL_DOWN","LARGE_LEFT","LARGE_RIGHT","LARGE_UP","LARGE_DOWN");private static final Set<Integer>EXCLUDED_STARTS=Set.of(13,37,40,43,67,39,41,31,49);private static final List<String>BUTTONS=List.of("VERT1","HORIZ1","HORIZ2","VERT2");
 @Override protected SolveResult<CursedDoubleOhOutput>doSolve(RoundEntity round,BombEntity bomb,ModuleEntity module,CursedDoubleOhInput input){if(input==null||input.startingNumber()==null||input.buttonFunctions()==null)return failure("Enter the exact initial number and all four inferred button functions");int start=indexOf(GRID,input.startingNumber());if(start<0||GRID[start]<10||EXCLUDED_STARTS.contains(start))return failure("Enter a possible initial two-digit display from this attempt");List<String>functions=input.buttonFunctions().stream().map(CursedDoubleOhSolver::norm).toList();if(functions.size()!=4||functions.stream().anyMatch(f->!FUNCTIONS.contains(f))||!validWiring(functions))return failure("Assign one small horizontal, small vertical, large horizontal, and large vertical function");List<Integer>path=findPath(start,functions);if(path==null)return failure("No legal non-repeating route to 00 was found for that wiring");List<String>presses=new ArrayList<>(),numbers=new ArrayList<>();numbers.add(String.format("%02d",GRID[start]));int pos=start;for(int button:path){presses.add(BUTTONS.get(button));pos=move(pos,functions.get(button));numbers.add(String.format("%02d",GRID[pos]));}presses.add("SUBMIT");storeState(module,"cursedDoubleOhInitialFirstDigit",String.valueOf(input.startingNumber()/10));return success(new CursedDoubleOhOutput(presses,numbers));}
 static List<Integer>findPath(int start,List<String>functions){record Node(int pos,int last,BitSet seen,List<Integer>path){}Queue<Node>q=new ArrayDeque<>();BitSet first=new BitSet(81);first.set(start);q.add(new Node(start,-1,first,List.of()));Set<String>states=new HashSet<>();while(!q.isEmpty()){Node n=q.remove();if(GRID[n.pos()]==0)return n.path();for(int b=0;b<4;b++){if(b==n.last())continue;int next=move(n.pos(),functions.get(b));if(n.seen().get(next))continue;BitSet seen=(BitSet)n.seen().clone();seen.set(next);List<Integer>path=new ArrayList<>(n.path());path.add(b);String key=next+":"+b+":"+Arrays.toString(seen.toLongArray());if(states.add(key))q.add(new Node(next,b,seen,path));}}return null;}
 static int move(int pos,String function){int x=pos%9,y=pos/9;switch(function){case"SMALL_LEFT"->x=x/3*3+(x%3+2)%3;case"SMALL_RIGHT"->x=x/3*3+(x%3+1)%3;case"SMALL_UP"->y=y/3*3+(y%3+2)%3;case"SMALL_DOWN"->y=y/3*3+(y%3+1)%3;case"LARGE_LEFT"->x=(x+6)%9;case"LARGE_RIGHT"->x=(x+3)%9;case"LARGE_UP"->y=(y+6)%9;case"LARGE_DOWN"->y=(y+3)%9;default->throw new IllegalArgumentException(function);}return y*9+x;}
 private static boolean validWiring(List<String>f){return f.stream().filter(x->x.startsWith("SMALL_")&&(x.endsWith("LEFT")||x.endsWith("RIGHT"))).count()==1&&f.stream().filter(x->x.startsWith("SMALL_")&&(x.endsWith("UP")||x.endsWith("DOWN"))).count()==1&&f.stream().filter(x->x.startsWith("LARGE_")&&(x.endsWith("LEFT")||x.endsWith("RIGHT"))).count()==1&&f.stream().filter(x->x.startsWith("LARGE_")&&(x.endsWith("UP")||x.endsWith("DOWN"))).count()==1;}
 private static int indexOf(int[]a,int v){for(int i=0;i<a.length;i++)if(a[i]==v)return i;return-1;}private static String norm(String s){return s==null?"":s.trim().toUpperCase(Locale.ROOT).replace('-','_').replace(' ','_');}
}
