package ktanesolver.module.modded.regular.requested;

import static org.assertj.core.api.Assertions.assertThat;
import java.util.*;import org.junit.jupiter.api.Test;import ktanesolver.entity.*;import ktanesolver.enums.ModuleType;import ktanesolver.logic.*;import ktanesolver.module.modded.regular.souvenir.*;
import ktanesolver.module.modded.regular.alchemy.AlchemySolver;import ktanesolver.module.modded.regular.bartending.BartendingSolver;import ktanesolver.module.modded.regular.cookiejars.CookieJarsSolver;import ktanesolver.module.modded.regular.decoloredsquares.DecoloredSquaresSolver;import ktanesolver.module.modded.regular.detonato.DetonatoSolver;import ktanesolver.module.modded.regular.flavortext.FlavorTextSolver;import ktanesolver.module.modded.regular.flavortextex.FlavorTextExSolver;import ktanesolver.module.modded.regular.freeparking.FreeParkingSolver;import ktanesolver.module.modded.regular.homophones.HomophonesSolver;import ktanesolver.module.modded.regular.krazytalk.KrazyTalkSolver;import ktanesolver.module.modded.regular.madmemory.MadMemorySolver;import ktanesolver.module.modded.regular.numbers.NumbersSolver;import ktanesolver.module.modded.regular.questionmark.QuestionMarkSolver;import ktanesolver.module.modded.regular.shapesandbombs.ShapesAndBombsSolver;import ktanesolver.module.modded.regular.simonsstages.SimonsStagesSolver;import ktanesolver.module.modded.regular.sync1253.Sync1253Solver;import ktanesolver.module.modded.regular.unrelatedanagrams.UnrelatedAnagramsSolver;import ktanesolver.module.modded.regular.varicoloredsquares.VaricoloredSquaresSolver;import ktanesolver.module.modded.regular.westeros.WesterosSolver;import ktanesolver.module.modded.regular.zoni.ZoniSolver;

class RequestedModulesSolverTest{
 private static BombEntity bomb(){BombEntity b=new BombEntity();b.setSerialNumber("A12BCD");return b;}private static ModuleEntity module(){return new ModuleEntity();}@SuppressWarnings("unchecked")private static<T extends ModuleOutput> T output(SolveResult<T>r){assertThat(r).isInstanceOf(SolveSuccess.class);return((SolveSuccess<T>)r).output();}
 @Test void numbers(){var x=output(new NumbersSolver().solve(new RoundEntity(),bomb(),module(),new NumbersSolver.Input(1,2)));assertThat(x.displayedNumber()).isEqualTo("12");assertThat(x.pressDigits()).hasSize(4);}
 @Test void simonsStages(){var x=output(new SimonsStagesSolver().solve(new RoundEntity(),bomb(),module(),new SimonsStagesSolver.Input(List.of(new SimonsStagesSolver.Stage("Blue",List.of("Red","Blue","Yellow"))))));assertThat(x.pressSequences().get(0)).containsExactly("Yellow","Blue","Red");}
 @Test void questionMark(){var m=module();var x=output(new QuestionMarkSolver().solve(new RoundEntity(),bomb(),m,new QuestionMarkSolver.Input(List.of(1,2,3,4))));assertThat(x.holdSymbols()).isNotEmpty();assertThat(m.getState()).containsKey("questionMarkSymbols");}
 @Test void flavorTextEx(){var m=module();var x=output(new FlavorTextExSolver().solve(new RoundEntity(),bomb(),m,new FlavorTextExSolver.Input("14",1940043870L,List.of("1","9","4","0"))));assertThat(x.pressLabels()).containsExactly("1","9","4","0");}
 @Test void homophones(){var x=output(new HomophonesSolver().solve(new RoundEntity(),bomb(),module(),new HomophonesSolver.Input(List.of("i","see","ell","won"),List.of("I","C","L","ONE"))));assertThat(x.pressPositions()).containsExactly(1,2,3,4);}
 @Test void zoni(){var m=module();var x=output(new ZoniSolver().solve(new RoundEntity(),bomb(),m,new ZoniSolver.Input("angel")));assertThat(x.digit()).isEqualTo(1);assertThat(m.getState()).containsKey("zoniWords");}
 @Test void sync1253(){var x=output(new Sync1253Solver().solve(new RoundEntity(),bomb(),module(),new Sync1253Solver.Input("bombs","CMP")));assertThat(x.base4()).isEqualTo("0");}
 @Test void unrelatedAnagrams(){var x=output(new UnrelatedAnagramsSolver().solve(new RoundEntity(),bomb(),module(),new UnrelatedAnagramsSolver.Input(300,120)));assertThat(x.baseWord()).isEqualTo("ANTDUELER");}
 @Test void westeros(){var x=output(new WesterosSolver().solve(new RoundEntity(),bomb(),module(),new WesterosSolver.Input("Winter is Coming",List.of("Arya","Tyrion"))));assertThat(x.house()).isEqualTo("Stark");}
 @Test void madMemory(){var m=module();var x=output(new MadMemorySolver().solve(new RoundEntity(),bomb(),m,new MadMemorySolver.Input("ONE",List.of(4,1,3,2))));assertThat(x.stage()).isEqualTo(1);assertThat(m.getState()).containsKey("madMemoryDisplays");}
 @Test void krazyTalk(){var x=output(new KrazyTalkSolver().solve(new RoundEntity(),bomb(),module(),new KrazyTalkSolver.Input(1,"Quote.",List.of("It says, [MESSAGE]"),"End quote.")));assertThat(x.holdDigit()).isEqualTo(7);assertThat(x.releaseDigit()).isEqualTo(1);}
 @Test void alchemy(){var x=output(new AlchemySolver().solve(new RoundEntity(),bomb(),module(),new AlchemySolver.Input("Creation",List.of("Creation","Terra","Heva","Fire","Meta","Strucota"))));assertThat(x.actions()).containsExactly("submit","set frequency Life","submit");}
 @Test void cookieJars(){var x=output(new CookieJarsSolver().solve(new RoundEntity(),bomb(),module(),new CookieJarsSolver.Input(List.of(new CookieJarsSolver.Jar(0,2),new CookieJarsSolver.Jar(4,2),new CookieJarsSolver.Jar(9,2)),1)));assertThat(x.validJars()).isNotEmpty();}
 @Test void freeParking(){var x=output(new FreeParkingSolver().solve(new RoundEntity(),bomb(),module(),new FreeParkingSolver.Input("Dog")));assertThat(x.payment()).isEqualTo(12);}
 @Test void varicoloredSquares(){var colors=List.of("Red","Red","Red","Red","Green","Green","Green","Blue","Blue","Blue","Yellow","Yellow","Yellow","Magenta","Magenta","Magenta");var x=output(new VaricoloredSquaresSolver().solve(new RoundEntity(),bomb(),module(),new VaricoloredSquaresSolver.Input(colors,null)));assertThat(x.targetColor()).isEqualTo("Red");assertThat(x.pressPositions()).containsExactly(1,2,3,4);}
 @Test void decoloredSquares(){var colors=List.of("Red","Red","Green","Green","Blue","Blue","Yellow","Yellow","Yellow","Yellow","Yellow","Magenta","Magenta","Magenta","Magenta","Magenta");assertThat(new DecoloredSquaresSolver().solve(new RoundEntity(),bomb(),module(),new DecoloredSquaresSolver.Input(colors))).isInstanceOf(SolveSuccess.class);}
 @Test void flavorText(){var x=output(new FlavorTextSolver().solve(new RoundEntity(),bomb(),module(),new FlavorTextSolver.Input("How can this module be real if our eyes aren't real?")));assertThat(x.present()).isFalse();}
 @Test void detonato(){var m=module();var x=output(new DetonatoSolver().solve(new RoundEntity(),bomb(),m,new DetonatoSolver.Input("Alpha",List.of("A","B","C","D"))));assertThat(x.correctLetters()).containsExactly("A");assertThat(m.getState()).containsKey("detonatoWords");}
 @Test void bartending(){var m=module();var x=output(new BartendingSolver().solve(new RoundEntity(),bomb(),m,new BartendingSolver.Input(List.of("Powdered Delta","Flanergide","Adelhyde","Bronson Extract","Karmotrine"))));assertThat(x.drinks()).isNotEmpty();assertThat(x.twitchCommands()).endsWith("serve");assertThat(m.getState()).containsKey("bartendingIngredients");}
 @Test void shapesAndBombs(){var m=module();var x=output(new ShapesAndBombsSolver().solve(new RoundEntity(),bomb(),m,new ShapesAndBombsSolver.Input("A","White",Collections.nCopies(15,"Center"))));assertThat(x.targetPattern()).hasSize(40);assertThat(x.twitchCommands()).endsWith("submit");assertThat(m.getState()).containsKey("shapesAndBombsInitialLetter");}
 @Test void souvenirQuestionFamilies(){record Case(ModuleType type,Map<String,Object>state,String question,List<String>answers,String expected){}List<Case>cases=List.of(
  new Case(ModuleType.NUMBERS,Map.of("numbersDisplay","12"),"displayed number",List.of("12","34"),"12"),new Case(ModuleType.FREE_PARKING,Map.of("freeParkingToken","Dog"),"token",List.of("Car","Dog"),"Dog"),new Case(ModuleType.VARICOLORED_SQUARES,Map.of("varicoloredInitialColor","Red"),"initial color",List.of("Blue","Red"),"Red"),
  new Case(ModuleType.ZONI,Map.of("zoniWords",List.of("angel","pizza","light")),"second word",List.of("pizza","radio"),"pizza"),new Case(ModuleType.MAD_MEMORY,Map.of("madMemoryDisplays",List.of("ONE","02","FOR","4")),"third display",List.of("FOR","FOUR"),"FOR"),new Case(ModuleType.BARTENDING,Map.of("bartendingIngredients",List.of("Powdered Delta","Flanergide","Adelhyde","Bronson Extract","Karmotrine")),"fourth ingredient",List.of("Karmotrine","Bronson Extract"),"Bronson Extract"),
  new Case(ModuleType.QUESTION_MARK,Map.of("questionMarkSymbols",List.of(1,3,7,9)),"flashed symbols",List.of("2","3"),"3"),new Case(ModuleType.DECOLORED_SQUARES,Map.of("decoloredColumnColor","Blue","decoloredRowColor","Red"),"starting column color",List.of("Blue","Red"),"Blue"),new Case(ModuleType.FLAVOR_TEXT_EX,Map.of("flavorTextExModules",List.of("14","Memory","Mazes")),"third module",List.of("Mazes","Memory"),"Mazes"),
  new Case(ModuleType.SHAPES_AND_BOMBS,Map.of("shapesAndBombsInitialLetter","A"),"initial letter",List.of("A","B"),"A"),new Case(ModuleType.HOMOPHONES,Map.of("homophonesPhrases",List.of("i","see","ell","won")),"second phrase",List.of("sea","see"),"see"),new Case(ModuleType.DETONATO,Map.of("detonatoWords",List.of("Alpha","Beta","Charlie","Delta","Echo","Foxtrot")),"sixth word",List.of("Foxtrot","Flockstrot"),"Foxtrot"),new Case(ModuleType.SYNC_125_3,Map.of("sync1253Displays",List.of("CMP1","CMP2","CMP3","CMP4")),"fourth display",List.of("CMP3","CMP4"),"CMP4"));
  for(Case c:cases){BombEntity b=bomb();ModuleEntity source=module();source.setId(UUID.randomUUID());source.setType(c.type());source.setSolved(true);source.setState(c.state());b.getModules().add(source);ModuleEntity souvenir=module();souvenir.setId(UUID.randomUUID());souvenir.setType(ModuleType.SOUVENIR);b.getModules().add(souvenir);SouvenirOutput x=output(new SouvenirSolver().solve(new RoundEntity(),b,souvenir,new SouvenirInput(source.getId(),c.question(),c.answers(),false)));assertThat(x.answer()).as(c.type().name()).isEqualTo(c.expected());}}
}
