package ktanesolver.module.modded.regular.cookiejars;

import java.util.*;import org.springframework.stereotype.Service;import ktanesolver.annotation.ModuleInfo;import ktanesolver.dto.ModuleCatalogDto;import ktanesolver.entity.*;import ktanesolver.enums.ModuleType;import ktanesolver.logic.*;

@Service @ModuleInfo(type=ModuleType.COOKIE_JARS,id="cookieJars",name="Cookie Jars",category=ModuleCatalogDto.ModuleCategory.MODDED_REGULAR,description="Choose a jar whose cookie satisfies the current history and parity rule.",tags={"cookies","multi-step","conditional twitch"})
public class CookieJarsSolver extends AbstractModuleSolver<CookieJarsSolver.Input,CookieJarsSolver.Output>{
 public record Jar(int cookie,int count){} public record Input(List<Jar> jars,int currentJar)implements ModuleInput{} public record Output(List<Integer> validJars,int recommendedJar,String cookieName,String twitchCommand)implements ModuleOutput{} public record State(int last,int previous,Integer pending){public State(){this(-1,-1,null);}}
 private static final List<String>NAMES=List.of("Chocolate Chip","Sugar","M&M","Oatmeal Raisin","Snickerdoodle","Peanut Butter","Fortune","Butter","Gingerbread","OREO");
 @Override protected SolveResult<Output> doSolve(RoundEntity r,BombEntity b,ModuleEntity m,Input in){if(in==null||in.jars()==null||in.jars().size()!=3||in.currentJar()<1||in.currentJar()>3)return failure("Enter three jars and the currently shown jar");if(in.jars().stream().anyMatch(x->x==null||x.cookie()<0||x.cookie()>9||x.count()<0)||in.jars().stream().map(Jar::cookie).distinct().count()!=3)return failure("Cookie numbers must be three different values from 0 through 9 and counts cannot be negative");if(in.jars().stream().allMatch(x->x.count()==0))return success(new Output(List.of(),0,"None",""));State s=m.getStateAs(State.class,()->initial(b));int last=s.last(),previous=s.previous();if(s.pending()!=null){previous=last;last=s.pending();}int solved=(int)b.getModules().stream().filter(ModuleEntity::isSolved).count();List<Integer>valid=new ArrayList<>();for(int i=0;i<3;i++){Jar j=in.jars().get(i);if(j.count()>0&&ok(j,last,previous,solved))valid.add(i+1);}if(valid.isEmpty()){int best=-1,bestCookie=99;for(int i=0;i<3;i++)if(in.jars().get(i).count()>0&&in.jars().get(i).cookie()<bestCookie){best=i+1;bestCookie=in.jars().get(i).cookie();}valid.add(best);}int target=valid.get(0),cookie=in.jars().get(target-1).cookie();storeTypedState(m,new State(last,previous,cookie));String cmd=valid.contains(in.currentJar())?"eat":((target-in.currentJar()+3)%3==1?"right":"left");return success(new Output(valid,target,NAMES.get(cookie),cmd),false);}
 private static State initial(BombEntity b){List<Integer>d=b.getSerialNumber().chars().filter(Character::isDigit).map(x->x-'0').boxed().toList();return new State(d.isEmpty()?0:d.get(0),d.size()<2?d.isEmpty()?0:d.get(0):d.get(1),null);}private static boolean ok(Jar j,int l,int p,int solved){return switch(j.cookie()){case 0->l!=p;case 1->l==p;case 2->l<p;case 3->l>p;case 4->l==4;case 5->l!=5;case 6->(l&1)==(solved&1);case 7->(l&1)!=(solved&1);case 8->(j.count()&1)==(solved&1);default->(j.count()&1)!=(solved&1);};}
}
