/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ktanesolver;

import javax.swing.JOptionPane;

/**
 *
 * @author Komp
 */
public class ComplicatedWires extends javax.swing.JFrame {
    int last;
    char[] serial;
    int parC, batC;
    boolean led,star;
    String colour;
    public ComplicatedWires(char[] s, int p, int b) {
        serial=s;
        parC=p;
        batC=b;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        cbColour = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        chbStar = new javax.swing.JCheckBox();
        chbLED = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cbColour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "White", "Blue", "Red", "Red-Blue" }));

        jLabel1.setText("Colour");

        chbStar.setText("Star");

        chbLED.setText("LED");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chbLED)
                    .addComponent(chbStar)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbColour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbColour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbStar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbLED)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        colour=cbColour.getSelectedItem().toString().toLowerCase();
        led=chbLED.isSelected();
        star=chbStar.isSelected();
        for(int i=serial.length-1;i>=0;i--){
            if(Character.isDigit(serial[i]))
            {
                last=Character.getNumericValue(serial[i]);
                break;
            }
        }
        wireChoice();
    }//GEN-LAST:event_jButton1ActionPerformed
    private void wireChoice(){
        if(led){
            if(star){
                switch(colour){
                    case "red":{
                        if(batC>=2){
                        JOptionPane.showMessageDialog(this, "Cut the wire");
                                }
                        else{
                            JOptionPane.showMessageDialog(this, "Don't cut the wire");
                            }
                        break;

                    }
                    case "blue":{
                        if(parC>=1)
                            JOptionPane.showMessageDialog(this, "Cut the wire");
                        else
                            JOptionPane.showMessageDialog(this, "Don't cut the wire");
                        break;

                    }
                    case "red-blue":{
                        JOptionPane.showMessageDialog(this, "Don't cut the wire");
                        break;

                    }
                    case "white":{
                        if(batC>=2)
                        JOptionPane.showMessageDialog(this, "Cut the wire");       
                        else
                            JOptionPane.showMessageDialog(this, "Don't cut the wire");
                        break;

                    }
                }
            }
            else{
                switch(colour){
                    case "red":{
                        if(batC>=2)
                        JOptionPane.showMessageDialog(this, "Cut the wire");       
                        else
                            JOptionPane.showMessageDialog(this, "Don't cut the wire");
                        break;

                    }
                    case "blue":{
                        if(parC>=1)
                            JOptionPane.showMessageDialog(this, "Cut the wire");
                        else
                            JOptionPane.showMessageDialog(this, "Don't cut the wire");
                        break;

                    }
                    case "red-blue":{
                        if(last%2==0)
                        JOptionPane.showMessageDialog(this, "Cut the wire");
                        else
                            JOptionPane.showMessageDialog(this, "Don't cut the wire");
                        break;

                    }
                    case "white":{
                        JOptionPane.showMessageDialog(this, "Don't cut the wire");
                        break;

                    }
                }
                
            }
        }
        else{
            if(star){
                switch(colour){
                    case "red":{
                        JOptionPane.showMessageDialog(this, "Cut the wire");
                        break;

                    }
                    case "blue":{
                        JOptionPane.showMessageDialog(this, "Don't cut the wire");
                        break;

                    }
                    case "red-blue":{
                        if(parC>=1)
                            JOptionPane.showMessageDialog(this, "Cut the wire");
                        else
                            JOptionPane.showMessageDialog(this, "Don't cut the wire");
                        break;

                    }
                    case "white":{
                        JOptionPane.showMessageDialog(this, "Cut the wire");
                        break;
                    }
                }
                
            }
            else{
                switch(colour){
                    case "red":{
                        if(last%2==0)
                        JOptionPane.showMessageDialog(this, "Cut the wire");
                        else
                            JOptionPane.showMessageDialog(this, "Don't cut the wire");
                        break;

                    }
                    case "blue":{
                        if(last%2==0)
                        JOptionPane.showMessageDialog(this, "Cut the wire");
                        else
                            JOptionPane.showMessageDialog(this, "Don't cut the wire");
                        break;

                    }
                    case "red-blue":{
                        if(last%2==0)
                        JOptionPane.showMessageDialog(this, "Cut the wire");
                        else
                            JOptionPane.showMessageDialog(this, "Don't cut the wire");
                        break;

                    }
                    case "white":{
                        JOptionPane.showMessageDialog(this, "Cut the wire");
                        break;
                    }
                }
                
            }
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComplicatedWires.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComplicatedWires.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComplicatedWires.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComplicatedWires.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ComplicatedWires().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbColour;
    private javax.swing.JCheckBox chbLED;
    private javax.swing.JCheckBox chbStar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
