package ktanesolver;
import java.awt.GridLayout;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Komp
 */
public class Keypads extends javax.swing.JFrame {

    public ImageIcon list = new ImageIcon("Lista.jpg");
    public Keypads() {
        initComponents();
    }
    String[] convert;
    int[] symbols;
    int[][] slist={
        {1,2,3,4,5,6,7},
        {8,1,7,9,10,6,11},
        {12,13,9,14,15,3,10},
        {16,17,18,5,14,11,19},
        {20,19,18,21,17,22,23},
        {16,8,24,25,20,26,27}
    };
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lList = new javax.swing.JLabel();
        tfInput = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bAccept = new javax.swing.JButton();
        lS1 = new javax.swing.JLabel();
        lS2 = new javax.swing.JLabel();
        lS3 = new javax.swing.JLabel();
        lS4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Keypads");

        lList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lista.jpg"))); // NOI18N

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Type in the numbers of symbols that");
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel2.setText("appear on the module");

        bAccept.setText("OK");
        bAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAcceptActionPerformed(evt);
            }
        });

        lS1.setText("1");

        lS2.setText("2");

        lS3.setText("3");

        lS4.setText("4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lList)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(tfInput)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lS1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lS2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lS3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lS4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(41, 41, 41))
                            .addComponent(bAccept))
                        .addGap(66, 66, 66)))
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(bAccept)
                .addGap(75, 75, 75)
                .addComponent(lS1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lS2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lS3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lS4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lList, javax.swing.GroupLayout.PREFERRED_SIZE, 537, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAcceptActionPerformed
        convert=tfInput.getText().split(" ");
        symbols=new int[convert.length];
        for(int i=0;i<convert.length;i++){
            symbols[i]=Integer.parseInt(convert[i]);
        }
        symbols=order(symbols);
        String[] images = getImages(symbols);
        lS1.setIcon(new javax.swing.ImageIcon(getClass().getResource(images[0]))); // NOI18N
        lS2.setIcon(new javax.swing.ImageIcon(getClass().getResource(images[1]))); // NOI18N
        lS3.setIcon(new javax.swing.ImageIcon(getClass().getResource(images[2]))); // NOI18N
        lS4.setIcon(new javax.swing.ImageIcon(getClass().getResource(images[3]))); // NOI18N
        
        
        
    }//GEN-LAST:event_bAcceptActionPerformed
    public int[] order(int[] s){
        int[] order = new int[s.length];
        int best=0;
        int row=0;
        for(int i=0;i<6;i++){
            for(int j=0;j<7;j++){
                for(int k=0;k<4;k++){
                    if(slist[i][j]==s[k])
                    {
                        best++;
                    }
                }
            }
            if(best==4)
            {
                row =i;
                break;
            }
            best=0;
        }
        int items=0;
        for(int i=0;i<7;i++){
            for(int j=0;j<4;j++){
                if(slist[row][i]==s[j]){
                    order[items]=s[j];
                    items++;
                }
            }
        }
            
        return order;
    }
    public String[] getImages(int[] s){
        String[] ima=new String[4];
        for(int i=0;i<4;i++){
            switch(s[i])
            {
                case 1:
                    ima[i] = "/S1.jpg";
                    break;
                case 2:
                    ima[i] = "/S2.jpg";
                    break;
                case 3:
                    ima[i] = "/S3.jpg";
                    break;
                case 4:
                    ima[i] = "/S4.jpg";
                    break;
                case 5:
                    ima[i] = "/S5.jpg";
                    break;
                case 6:
                    ima[i] = "/S6.jpg";
                    break;
                case 7:
                    ima[i] = "/S7.jpg";
                    break;
                case 8:
                    ima[i] = "/S8.jpg";
                    break;
                case 9:
                    ima[i] = "/S9.jpg";
                    break;
                case 10:
                    ima[i] = "/S10.jpg";
                    break;
                case 11:
                    ima[i] = "/S11.jpg";
                    break;
                case 12:
                    ima[i] = "/S12.jpg";
                    break;
                case 13:
                    ima[i] = "/S13.jpg";
                    break;
                case 14:
                    ima[i] = "/S14.jpg";
                    break;
                case 15:
                    ima[i] = "/S15.jpg";
                    break;
                case 16:
                    ima[i] = "/S16.jpg";
                    break;
                case 17:
                    ima[i] = "/S17.jpg";
                    break;
                case 18:
                    ima[i] = "/S18.jpg";
                    break;
                case 19:
                    ima[i] = "/S19.jpg";
                    break;
                case 20:
                    ima[i] = "/S20.jpg";
                    break;
                case 21:
                    ima[i] = "/S21.jpg";
                    break;
                case 22:
                    ima[i] = "/S22.jpg";
                    break;
                case 23:
                    ima[i] = "/S23.jpg";
                    break;
                case 24:
                    ima[i] = "/S24.jpg";
                    break;
                case 25:
                    ima[i] = "/S25.jpg";
                    break;
                case 26:
                    ima[i] = "/S26.jpg";
                    break;
                case 27:
                    ima[i] = "/S27.jpg";
                    break;
            }
        }
        return ima;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Keypads.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Keypads.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Keypads.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Keypads.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Keypads().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAccept;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lList;
    private javax.swing.JLabel lS1;
    private javax.swing.JLabel lS2;
    private javax.swing.JLabel lS3;
    private javax.swing.JLabel lS4;
    private javax.swing.JTextField tfInput;
    // End of variables declaration//GEN-END:variables
}
