/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ktanesolver;

import javax.swing.JOptionPane;

/**
 *
 * @author Komp
 */
public class Wires extends javax.swing.JFrame {
    Menu menu;
    int redC, blueC, yellowC, whiteC, blackC;
    String[] input;
    char[] serial;
    int digit;
    public Wires(Menu m,char[] s) {
        menu=m;
        serial=s;
        initComponents();
    }
    void wires3(String[] w){
        if(redC==0){
            JOptionPane.showMessageDialog(rootPane, "Cut the second wire");
        }
        else{
        if(w[2].matches("white")){
            JOptionPane.showMessageDialog(rootPane, "Cut the last wire");
        }else{  
        if(blueC>1){
            JOptionPane.showMessageDialog(rootPane, "Cut the last blue wire");
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Cut the last wire");
            }
        }
    }
    void wires4(String[] w){
        if(redC>1&&digit%2==1){
            JOptionPane.showMessageDialog(rootPane, "Cut the last red wire");
        }
        else{
            if(w[3].matches("yellow")&&redC==0){
                JOptionPane.showMessageDialog(rootPane, "Cut the first wire");
            }
            else{
                if(blueC==1){
                    JOptionPane.showMessageDialog(rootPane, "Cut the first wire");
                }
                else{
                    if(yellowC>1)
                    {
                        JOptionPane.showMessageDialog(rootPane, "Cut the last wire");
                    }
                    else
                        JOptionPane.showMessageDialog(rootPane, "Cut the second wire");
                }
            }
        }
    }
    void wires5(String[] w){
        if(w[4].matches("black")&&digit%2==1){
            JOptionPane.showMessageDialog(rootPane, "Cut the fourth wire");
        }else{
            if(redC==1&&yellowC>1){
                JOptionPane.showMessageDialog(rootPane, "Cut the first wire");
            }
            else{
                if(blackC==0)
                {
                    JOptionPane.showMessageDialog(rootPane, "Cut the second wire");
                }
                else
                    JOptionPane.showMessageDialog(rootPane, "Cut the first wire");
            }
        }
    }
    void wires6(String[] w){
        if(yellowC==0&&digit%2==1){
            JOptionPane.showMessageDialog(rootPane, "Cut the third wire");
        }
        else{
            if(yellowC==1&&whiteC>1){
                JOptionPane.showMessageDialog(rootPane, "Cut the fourth wire");
            }
            else{
                if(redC==0){
                    JOptionPane.showMessageDialog(rootPane, "Cut the last wire");
                }
                else
                    JOptionPane.showMessageDialog(rootPane, "Cut the fourth wire");
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bAccept = new javax.swing.JButton();
        tfWires = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        bMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Wires");

        bAccept.setText("OK");
        bAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAcceptActionPerformed(evt);
            }
        });

        jLabel1.setText("Type in the colors of the wires from top to bottom with spaces in between");

        bMenu.setText("Menu");
        bMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(bAccept)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bMenu)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tfWires)
                    .addComponent(jLabel1))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfWires, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(bAccept)
                    .addComponent(bMenu)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAcceptActionPerformed
        redC=blueC=blackC=yellowC=whiteC=0;
        for(int i=serial.length-1;i>=0;i--){
            if(Character.isDigit(serial[i]))
            {
                digit=Character.getNumericValue(serial[i]);
                break;
            }
        }
        input=tfWires.getText().toLowerCase().split(" ");
        for (String input1 : input) {
            if (input1.matches("red")) {
                redC++;
            }
            if (input1.matches("blue")) {
                blueC++;
            }
            if (input1.matches("black")) {
                blackC++;
            }
            if (input1.matches("yellow")) {
                yellowC++;
            }
            if (input1.matches("white")) {
                whiteC++;
            }
        }
        switch(input.length)
        {
            case 3:
                    {
                        wires3(input);
                        break;
                    }
            case 4:
                    {
                        wires4(input);
                        break;
                    }
            case 5:
                    {
                        wires5(input);
                        break;
                    }
            case 6:
                    {
                        wires6(input);
                        break;
                    }
        }
        
    }//GEN-LAST:event_bAcceptActionPerformed

    private void bMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMenuActionPerformed
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Wires.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Wires.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Wires.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Wires.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Wires().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAccept;
    private javax.swing.JButton bMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField tfWires;
    // End of variables declaration//GEN-END:variables
}
