package ktanesolver.module.modded.regular.shapesandbombs;

import java.util.*;import org.springframework.stereotype.Service;import ktanesolver.annotation.ModuleInfo;import ktanesolver.dto.ModuleCatalogDto;import ktanesolver.entity.*;import ktanesolver.enums.ModuleType;import ktanesolver.logic.*;

@Service @ModuleInfo(type=ModuleType.SHAPES_AND_BOMBS,id="ShapesBombs",name="Shapes And Bombs",category=ModuleCatalogDto.ModuleCategory.MODDED_REGULAR,description="Transform the initial letter with the arrow sequence and produce the final 5-by-8 shape.",tags={"shapes","arrows","grid","souvenir"})
public class ShapesAndBombsSolver extends AbstractModuleSolver<ShapesAndBombsSolver.Input,ShapesAndBombsSolver.Output>{
 public record Input(String initialLetter,String color,List<String> arrows)implements ModuleInput{} public record Output(String targetPattern,List<Integer> togglePositions,List<String> coordinates,List<String> twitchCommands)implements ModuleOutput{}
 private static final String LETTERS="ABDEGIKLNOPSTXY";private static final List<String>COLORS=List.of("Yellow","Green","Cyan","Blue","Purple","White");private static final int[]DIR={0,1,-5,-1,5,-4,6,-6,4};private static final List<String>ARROWS=List.of("Center","Right","Up","Left","Down","Right-Up","Right-Down","Up-Left","Left-Down");
 private static final String[]INITIAL={"XOOOXOXXXOOXXXOOOOOOOXXXOOXXXOOXXXOOXXXO","OOOOXOXXXOOXXXOOOOOXOXXXOOXXXOOXXXOOOOOX","OOOOXOXXXOOXXXOOXXXOOXXXOOXXXOOXXXOOOOOX","OOOOOOXXXXOXXXXOOOOXOXXXXOXXXXOXXXXOOOOO","XOOOXOXXXOOXXXXOXXXXOXOOOOXXXOOXXXOXOOOX","OOOOOXXOXXXXOXXXXOXXXXOXXXXOXXXXOXXOOOOO","OXXXOOXXOXOXOXXOOXXXOXOXXOXXOXOXXOXOXXXO","OXXXXOXXXXOXXXXOXXXXOXXXXOXXXXOXXXXOOOOO","OXXXOOOXXOOXOXOOXOXOOXXOOOXXXOOXXXOOXXXO","XOOOXOXXXOOXXXOOXXXOOXXXOOXXXOOXXXOXOOOX","OOOOXOXXXOOXXXOOOOOXOXXXXOXXXXOXXXXOXXXX","XOOOXOXXXOOXXXXXOOOXXXXXOXXXXOOXXXOXOOOX","OOOOOXXOXXXXOXXXXOXXXXOXXXXOXXXXOXXXXOXX","OXXXOXOXOXXOXOXXXOXXXXOXXXOXOXXOXOXOXXXO","OXXXOXOXOXXOXOXXXOXXXXOXXXXOXXXXOXXXXOXX"};
 private static final String[]TARGET={"XXXXXXXXXXXXXXXOXXXXOXXXOOXOXOOXOXOOOOOO","XOOOXOXXXOXXXXOXXXOXXXOXXXXOXXXXXXXXXOXX","XXOXXXOXOXOXXXOXOOOXOXXXOXOXOXXXOXXOOXOO","XOOOXXXXXOXXXXOXOOOXXXXXOXXXXOXXXXOXOOOX","OXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOX","XXOXXXXOXXXXOXXXOOOXOXOXOOOOOOXOOOXXXOXX","XOOOXOXXXOOXXXOXOXOXOOOOOXOXOXOOOOOXOXOX","XXXXXXXOOOXXOOOXXOOOXXXOXOXOXXXOOXXXOOXX","XXOXOOXXOXXXXXXXOOOXXXXXXXOXOOXXXXXOOOOO","OOXOOOXXXOOXOXOOOXOOOOXOOOXOXOOXXXOOOXOO","XXXXXXXOXXXXOXXXXOXXXOOOXXXOXXOXOXOOOOOO","OOOOOOXXXOOXXXOOXOXOOXOXOOXXXOOXXXOOOOOO","OOOOOXXXOXXXOXXXXXOXOOOOOOXXXXOXXXXOXOOO","XXXXOXXXOXXXOXXOOXOOOXOXOOXXXOOXXXOOOOOO","XOXOXOXOOXXXXXXOXOXOOXOXOXXXXXOXOOXXOXOX","XOXOXOXXXOOXXXOXOOOXOXXXOOOXOOOXXXOXOOOX","XOXOXXOXOXXXOXXXOXOXOXOXOOXXXOXOXOXXXOXX","OXOXOOXOXOOXOXOOXOXOOXOXOOXOXOOXOXOOXOXO","OOOOOXXXXXOOOOOXXXXXOOOOOXXXXXOOOOOXXXXX","XXOXXXXOXXXXOXXXXOXXXXOXXXXOXXXXXXXXXOXX"};
 private static final String[]TABLE={"KEPTALINGDOBYXS","KINGSLEDYOPXTAB","ONSLYPKIDTXBAEG","ABDEGIKLNOPSTXY","YXTSPONLKIGEDBA"};
 @Override protected SolveResult<Output> doSolve(RoundEntity r,BombEntity b,ModuleEntity m,Input in){if(in==null||in.initialLetter()==null||in.initialLetter().trim().length()!=1||in.arrows()==null||in.arrows().size()!=15)return failure("Enter a valid initial letter, color, and all 15 arrows");char letter=Character.toUpperCase(in.initialLetter().trim().charAt(0));int li=LETTERS.indexOf(letter),ci=index(COLORS,in.color());if(li<0||ci<0)return failure("Unknown initial letter or square color");int[]ar=new int[15];for(int i=0;i<15;i++){int x=index(ARROWS,in.arrows().get(i));if(x<0)return failure("Unknown arrow at position "+(i+1));ar[i]=DIR[x];}String initial=INITIAL[li],mod=initial;if(ci<5){int start=switch(ci){case 0->li;case 1->b.getModules().size();case 2->count(initial,'O');case 3->count(initial,'X');default->0;};String table=TABLE[ci];int nowLetter=table.indexOf(letter);for(int i=start%15;i<15;i++)nowLetter=wrapped(nowLetter,ar[i],15,3);int end=LETTERS.indexOf(table.charAt(nowLetter)),square=Math.max(0,Math.min(39,start));StringBuilder sb=new StringBuilder(mod);for(int i=end;i<15;i++){square=wrapped(square,ar[i]*(sb.charAt(square)=='O'?1:-1),40,5);sb.setCharAt(square,sb.charAt(square)=='O'?'X':'O');}mod=sb.toString();}boolean unlit=b.isLastDigitOdd(),upper=li%2==0;String half=upper?mod.substring(0,20):mod.substring(20);int count=count(half,unlit?'X':'O'),targetIx=Math.max(5,Math.min(14,count))-5+((b.getModules().stream().filter(ModuleEntity::isSolved).count()&1)==1?10:0);String target=TARGET[targetIx];List<Integer>toggles=new ArrayList<>();for(int i=0;i<40;i++)if(initial.charAt(i)!=target.charAt(i))toggles.add(i+1);List<String>coords=toggles.stream().map(ShapesAndBombsSolver::coord).toList();List<String>cmd=new ArrayList<>();if(!coords.isEmpty())cmd.add("press "+String.join(" ",coords));cmd.add("submit");storeState(m,"shapesAndBombsInitialLetter",Character.toString(letter));return success(new Output(target,toggles,coords,cmd));}
 private static int wrapped(int square,int dir,int size,int rows){int temp=Math.abs(dir)==4?-Integer.signum(dir):(Math.abs(dir)%5)*Integer.signum(dir);if(square%rows+temp==-1||square%rows+temp==rows)temp=(rows-1)*(square%rows+temp==rows?-1:1);square+=temp;if(Math.abs(dir)!=1&&dir!=0)square+=rows*Integer.signum(dir);if(square<0)square=size-Math.abs(square);return square%size;}private static int count(String s,char c){return(int)s.chars().filter(x->x==c).count();}private static String coord(int p){return "ABCDE".charAt((p-1)%5)+Integer.toString((p-1)/5+1);}private static int index(List<String>x,String s){if(s==null)return-1;for(int i=0;i<x.size();i++)if(x.get(i).equalsIgnoreCase(s.trim()))return i;return-1;}
}
