export enum ModuleType {
  LONDON_UNDERGROUND = "LONDON_UNDERGROUND",
  COOKING = "COOKING",
  THE_SUN = "THE_SUN",
  THE_MOON = "THE_MOON",
  THE_NUMBER = "THE_NUMBER",
  RUBIKS_CLOCK = "RUBIKS_CLOCK",
  ERROR_CODES = "ERROR_CODES",
  SINK = "SINK",
  IDENTITY_PARADE = "IDENTITY_PARADE",
  MAFIA = "MAFIA",
  PAINTING = "PAINTING",
  JUKEBOX = "JUKEBOX",
  WIRES = "WIRES",
  BUTTON = "BUTTON",
  KEYPADS = "KEYPADS",
  MEMORY = "MEMORY",
  SIMON_SAYS = "SIMON_SAYS",
  MORSE_CODE = "MORSE_CODE",
  FORGET_ME_NOT = "FORGET_ME_NOT",
  FORGET_EVERYTHING = "FORGET_EVERYTHING",
  SOUVENIR = "SOUVENIR",
  SONIC_THE_HEDGEHOG = "SONIC_THE_HEDGEHOG",
  ICE_CREAM = "ICE_CREAM",
  THE_SCREW = "THE_SCREW",
  YAHTZEE = "YAHTZEE",
  X_RAY = "X_RAY",
  BATTLESHIP = "BATTLESHIP",
  MINESWEEPER = "MINESWEEPER",
  VISUAL_IMPAIRMENT = "VISUAL_IMPAIRMENT",
  WHOS_ON_FIRST = "WHOS_ON_FIRST",
  THIRD_BASE = "THIRD_BASE",
  VENTING_GAS = "VENTING_GAS",
  CAPACITOR_DISCHARGE = "CAPACITOR_DISCHARGE",
  COMPLICATED_WIRES = "COMPLICATED_WIRES",
  WIRE_SEQUENCES = "WIRE_SEQUENCES",
  PASSWORDS = "PASSWORDS",
  EXTENDED_PASSWORD = "EXTENDED_PASSWORD",
  MAZES = "MAZES",
  KNOBS = "KNOBS",
  COLOR_FLASH = "COLOR_FLASH",
  COLOR_DECODING = "COLOR_DECODING",
  PIANO_KEYS = "PIANO_KEYS",
  SEMAPHORE = "SEMAPHORE",
  PERSPECTIVE_PEGS = "PERSPECTIVE_PEGS",
  EMOJI_MATH = "EMOJI_MATH",
  SWITCHES = "SWITCHES",
  COLORED_SWITCHES = "COLORED_SWITCHES",
  TWO_BITS = "TWO_BITS",
  WORD_SCRAMBLE = "WORD_SCRAMBLE",
  FONT_SELECT = "FONT_SELECT",
  WORD_SEARCH = "WORD_SEARCH",
  BROKEN_BUTTONS = "BROKEN_BUTTONS",
  COMPLICATED_BUTTONS = "COMPLICATED_BUTTONS",
  ANAGRAMS = "ANAGRAMS",
  COMBINATION_LOCK = "COMBINATION_LOCK",
  LISTENING = "LISTENING",
  FOREIGN_EXCHANGE_RATES = "FOREIGN_EXCHANGE_RATES",
  ROUND_KEYPAD = "ROUND_KEYPAD",
  COMPLEX_KEYPAD = "COMPLEX_KEYPAD",
  NUMBER_PAD = "NUMBER_PAD",
  ORIENTATION_CUBE = "ORIENTATION_CUBE",
  MORSEMATICS = "MORSEMATICS",
  CONNECTION_CHECK = "CONNECTION_CHECK",
  LETTER_KEYS = "LETTER_KEYS",
  LOGIC = "LOGIC",
  SUPERLOGIC = "SUPERLOGIC",
  LOGIC_GATES = "LOGIC_GATES",
  ASTROLOGY = "ASTROLOGY",
  MYSTIC_SQUARE = "MYSTIC_SQUARE",
  CRAZY_TALK = "CRAZY_TALK",
  ADVENTURE_GAME = "ADVENTURE_GAME",
  PLUMBING = "PLUMBING",
  CRUEL_PIANO_KEYS = "CRUEL_PIANO_KEYS",
  FESTIVE_PIANO_KEYS = "FESTIVE_PIANO_KEYS",
  BUTTON_SEQUENCE = "BUTTON_SEQUENCE",
  FLAGS = "FLAGS",
  TIMEZONE = "TIMEZONE",
  POLYHEDRAL_MAZE = "POLYHEDRAL_MAZE",
  SYMBOLIC_COORDINATES = "SYMBOLIC_COORDINATES",
  POETRY = "POETRY",
  ALGEBRA = "ALGEBRA",
  SAFETY_SAFE = "SAFETY_SAFE",
  CRYPTOGRAPHY = "CRYPTOGRAPHY",
  CAESAR_CIPHER = "CAESAR_CIPHER",
  MODERN_CIPHER = "MODERN_CIPHER",
  PLAYFAIR_CIPHER = "PLAYFAIR_CIPHER",
  TURN_THE_KEY = "TURN_THE_KEY",
  TURN_THE_KEYS = "TURN_THE_KEYS",
  CHESS = "CHESS",
  MOUSE_IN_THE_MAZE = "MOUSE_IN_THE_MAZE",
  MORSE_A_MAZE = "MORSE_A_MAZE",
  HEXAMAZE = "HEXAMAZE",
  BLIND_MAZE = "BLIND_MAZE",
  BITMAPS = "BITMAPS",
  BRAILLE = "BRAILLE",
  COLORED_SQUARES = "COLORED_SQUARES",
  ADJACENT_LETTERS = "ADJACENT_LETTERS",
  SILLY_SLOTS = "SILLY_SLOTS",
  SKEWED_SLOTS = "SKEWED_SLOTS",
  THREE_D_MAZE = "THREE_D_MAZE",
  SIMON_STATES = "SIMON_STATES",
  SIMON_SCREAMS = "SIMON_SCREAMS",
  SIMON_SINGS = "SIMON_SINGS",
  SIMON_SENDS = "SIMON_SENDS",
  SIMON_SHRIEKS = "SIMON_SHRIEKS",
  MODULES_AGAINST_HUMANITY = "MODULES_AGAINST_HUMANITY",
  LAUNDRY = "LAUNDRY",
  PROBING = "PROBING",
  ALPHABET = "ALPHABET",
  MICROCONTROLLER = "MICROCONTROLLER",
  MURDER = "MURDER",
  SUBWAYS = "SUBWAYS",
  RESISTORS = "RESISTORS",
  GAMEPAD = "GAMEPAD",
  TIC_TAC_TOE = "TIC_TAC_TOE",
  MONSPLODE_FIGHT = "MONSPLODE_FIGHT",
  MONSPLODE_TRADING_CARDS = "MONSPLODE_TRADING_CARDS",
  GAME_OF_LIFE_SIMPLE = "GAME_OF_LIFE_SIMPLE",
  GAME_OF_LIFE_CRUEL = "GAME_OF_LIFE_CRUEL",
  SHAPE_SHIFT = "SHAPE_SHIFT",
  FOLLOW_THE_LEADER = "FOLLOW_THE_LEADER",
  FRIENDSHIP = "FRIENDSHIP",
  THE_BULB = "THE_BULB",
  BLIND_ALLEY = "BLIND_ALLEY",
  SEA_SHELLS = "SEA_SHELLS",
  ENGLISH_TEST = "ENGLISH_TEST",
  ROCK_PAPER_SCISSORS_LIZARD_SPOCK = "ROCK_PAPER_SCISSORS_LIZARD_SPOCK",
  SQUARE_BUTTON = "SQUARE_BUTTON",
  TEXT_FIELD = "TEXT_FIELD",
  SYMBOLIC_PASSWORD = "SYMBOLIC_PASSWORD",
  WIRE_PLACEMENT = "WIRE_PLACEMENT",
  PERPLEXING_WIRES = "PERPLEXING_WIRES",
  DOUBLE_OH = "DOUBLE_OH",
  CHEAP_CHECKOUT = "CHEAP_CHECKOUT",
  COORDINATES = "COORDINATES",
  LIGHT_CYCLE = "LIGHT_CYCLE",
  SYMBOL_CYCLE = "SYMBOL_CYCLE",
  BINARY_LEDS = "BINARY_LEDS",
  RHYTHMS = "RHYTHMS",
  COLOR_MATH = "COLOR_MATH",
  COLOR_MORSE = "COLOR_MORSE",
  COLOR_GENERATOR = "COLOR_GENERATOR",
  BIG_CIRCLE = "BIG_CIRCLE",
  MASTERMIND_SIMPLE = "MASTERMIND_SIMPLE",
  MASTERMIND_CRUEL = "MASTERMIND_CRUEL",
  GRIDLOCK = "GRIDLOCK",
  ONLY_CONNECT = "ONLY_CONNECT",
  NEUTRALIZATION = "NEUTRALIZATION",
  WEB_DESIGN = "WEB_DESIGN",
  CHORD_QUALITIES = "CHORD_QUALITIES",
  CREATION = "CREATION",
  RUBIKS_CUBE = "RUBIKS_CUBE",
  FIZZ_BUZZ = "FIZZ_BUZZ",
  THE_CLOCK = "THE_CLOCK",
  THE_STOPWATCH = "THE_STOPWATCH",
  PIE = "PIE",
  THE_WIRE = "THE_WIRE",
  LED_ENCRYPTION = "LED_ENCRYPTION",
  LED_GRID = "LED_GRID",
  GRAFFITI_NUMBERS = "GRAFFITI_NUMBERS",
  X01 = "X01",
  LOGICAL_BUTTONS = "LOGICAL_BUTTONS",
  GRID_MATCHING = "GRID_MATCHING",
  LASERS = "LASERS",
  TURTLE_ROBOT = "TURTLE_ROBOT",
  GUITAR_CHORDS = "GUITAR_CHORDS",
  CALENDAR = "CALENDAR",
  USA_MAZE = "USA_MAZE",
  BINARY_TREE = "BINARY_TREE",
  THE_TIME_KEEPER = "THE_TIME_KEEPER",
  LIGHTSPEED = "LIGHTSPEED",
  BLACK_HOLE = "BLACK_HOLE",
  SIMONS_STAR = "SIMONS_STAR",
  MORSE_WAR = "MORSE_WAR",
  THE_STOCK_MARKET = "THE_STOCK_MARKET",
  MINESEEKER = "MINESEEKER",
  MAZE_SCRAMBLER = "MAZE_SCRAMBLER",
  THE_NUMBER_CIPHER = "THE_NUMBER_CIPHER",
  ALPHABET_NUMBERS = "ALPHABET_NUMBERS",
  BRITISH_SLANG = "BRITISH_SLANG",
  DOUBLE_COLOR = "DOUBLE_COLOR",
  MARITIME_FLAGS = "MARITIME_FLAGS",
  EQUATIONS = "EQUATIONS",
  DETERMINANTS = "DETERMINANTS",
  PATTERN_CUBE = "PATTERN_CUBE",
  KNOW_YOUR_WAY = "KNOW_YOUR_WAY",
  SPLITTING_THE_LOOT = "SPLITTING_THE_LOOT",
  CHARACTER_SHIFT = "CHARACTER_SHIFT",
  SIMON_SAMPLES = "SIMON_SAMPLES",
  DRAGON_ENERGY = "DRAGON_ENERGY",
  UNCOLORED_SQUARES = "UNCOLORED_SQUARES",
  FLASHING_LIGHTS = "FLASHING_LIGHTS",
  THREE_D_TUNNELS = "THREE_D_TUNNELS",
  SYNCHRONIZATION = "SYNCHRONIZATION",
  THE_SWITCH = "THE_SWITCH",
  REVERSE_MORSE = "REVERSE_MORSE",
  MANOMETERS = "MANOMETERS",
  SHIKAKU = "SHIKAKU",
  WIRE_SPAGHETTI = "WIRE_SPAGHETTI",
  MODULE_HOMEWORK = "MODULE_HOMEWORK",
  TENNIS = "TENNIS",
  BENEDICT_CUMBERBATCH = "BENEDICT_CUMBERBATCH",
  BOGGLE = "BOGGLE",
  HORRIBLE_MEMORY = "HORRIBLE_MEMORY",
  SIGNALS = "SIGNALS",
  BOOLEAN_MAZE = "BOOLEAN_MAZE",
  SONIC_KNUCKLES = "SONIC_KNUCKLES",
  QUINTUPLES = "QUINTUPLES",
  THE_SPHERE = "THE_SPHERE",
  COFFEEBUCKS = "COFFEEBUCKS",
  COLORFUL_MADNESS = "COLORFUL_MADNESS",
  BASES = "BASES",
  LIONS_SHARE = "LIONS_SHARE",
  SNOOKER = "SNOOKER",
  BLACKJACK = "BLACKJACK",
  PARTY_TIME = "PARTY_TIME",
  ACCUMULATION = "ACCUMULATION",
  THE_PLUNGER_BUTTON = "THE_PLUNGER_BUTTON",
  THE_DIGIT = "THE_DIGIT",
  THE_JACK_O_LANTERN = "THE_JACK_O_LANTERN",
  T_WORDS = "T_WORDS",
  FESTIVE_JUKEBOX = "FESTIVE_JUKEBOX",
  DIVIDED_SQUARES = "DIVIDED_SQUARES",
  CONNECTION_DEVICE = "CONNECTION_DEVICE",
  INSTRUCTIONS = "INSTRUCTIONS",
  VALVES = "VALVES",
  BLOCKBUSTERS = "BLOCKBUSTERS",
  CATCHPHRASE = "CATCHPHRASE",
  COUNTDOWN = "COUNTDOWN",
  CRUEL_COUNTDOWN = "CRUEL_COUNTDOWN",
  ENCRYPTED_MORSE = "ENCRYPTED_MORSE",
  THE_CRYSTAL_MAZE = "THE_CRYSTAL_MAZE",
  IKEA = "IKEA",
  RETIREMENT = "RETIREMENT",
  ONE_HUNDRED_AND_ONE_DALMATIANS = "ONE_HUNDRED_AND_ONE_DALMATIANS",
  PERIODIC_TABLE = "PERIODIC_TABLE",
  SCHLAG_DEN_BOMB = "SCHLAG_DEN_BOMB",
  MAHJONG = "MAHJONG",
  KUDOSUDOKU = "KUDOSUDOKU",
  THE_RADIO = "THE_RADIO",
  MODULO = "MODULO",
  NUMBER_NIMBLENESS = "NUMBER_NIMBLENESS",
  PAY_RESPECTS = "PAY_RESPECTS",
  CHALLENGE_AND_CONTACT = "CHALLENGE_AND_CONTACT",
  THE_LABYRINTH = "THE_LABYRINTH",
  SPINNING_BUTTONS = "SPINNING_BUTTONS",
  THE_TRIANGLE = "THE_TRIANGLE",
  SUEET_WALL = "SUEET_WALL",
  HOT_POTATO = "HOT_POTATO",
  CHRISTMAS_PRESENTS = "CHRISTMAS_PRESENTS",
  HIEROGLYPHICS = "HIEROGLYPHICS",
  FUNCTIONS = "FUNCTIONS",
  NEEDY_MRS_BOB = "NEEDY_MRS_BOB",
  SCRIPTING = "SCRIPTING",
  SIMON_SPINS = "SIMON_SPINS",
  CURSED_DOUBLE_OH = "CURSED_DOUBLE_OH",
  TEN_BUTTON_COLOR_CODE = "TEN_BUTTON_COLOR_CODE",
  CRACKBOX = "CRACKBOX",
  STREET_FIGHTER = "STREET_FIGHTER",
  IMBALANCE = "IMBALANCE",
  SEQUENCES = "SEQUENCES",
  FAULTY_DIGITAL_ROOT = "FAULTY_DIGITAL_ROOT",
  THREE_LEDS = "THREE_LEDS",
  SIMPLETON = "SIMPLETON",
  THE_NEUTRAL_BUTTON = "THE_NEUTRAL_BUTTON",
  TANGRAMS = "TANGRAMS",
  BITWISE_OPERATIONS = "BITWISE_OPERATIONS",
  FAST_MATH = "FAST_MATH",
  BOOLEAN_VENN_DIAGRAM = "BOOLEAN_VENN_DIAGRAM",
  ZOO = "ZOO",
  POINT_OF_ORDER = "POINT_OF_ORDER",
  POKER = "POKER",
  NONOGRAM = "NONOGRAM",
  SET = "SET",
  HUNTING = "HUNTING",
  CURRICULUM = "CURRICULUM",
  MAINTENANCE = "MAINTENANCE",
  BACKGROUNDS = "BACKGROUNDS",
  FAULTY_BACKGROUNDS = "FAULTY_BACKGROUNDS",
  MORTAL_KOMBAT = "MORTAL_KOMBAT",
  MASHEMATICS = "MASHEMATICS",
  GREEK_CALCULUS = "GREEK_CALCULUS",
  RADIATOR = "RADIATOR",
  THE_IPHONE = "THE_IPHONE",
  THE_SWAN = "THE_SWAN",
  WASTE_MANAGEMENT = "WASTE_MANAGEMENT",
  HUMAN_RESOURCES = "HUMAN_RESOURCES",
  EUROPEAN_TRAVEL = "EUROPEAN_TRAVEL",
  LEGOS = "LEGOS",
  THE_CUBE = "THE_CUBE",
  JEWEL_VAULT = "JEWEL_VAULT",
  DR_DOCTOR = "DR_DOCTOR",
  TAX_RETURNS = "TAX_RETURNS",
  MARBLE_TUMBLE = "MARBLE_TUMBLE",
  BURGLAR_ALARM = "BURGLAR_ALARM",
  PRESS_X = "PRESS_X",
  THE_CODE = "THE_CODE",
  TAP_CODE = "TAP_CODE",
  SYNONYMS = "SYNONYMS",
  DIGITAL_ROOT = "DIGITAL_ROOT",
  SKYRIM = "SKYRIM",
  THE_HANGOVER = "THE_HANGOVER",
  BINARY_PUZZLE = "BINARY_PUZZLE",
  FACTORY_MAZE = "FACTORY_MAZE",
  BROKEN_GUITAR_CHORDS = "BROKEN_GUITAR_CHORDS",
  DOMINOES = "DOMINOES",
  HOGWARTS = "HOGWARTS",
  REGULAR_CRAZY_TALK = "REGULAR_CRAZY_TALK",
  SIMON_SPEAKS = "SIMON_SPEAKS",
  DISCOLORED_SQUARES = "DISCOLORED_SQUARES",
  SKINNY_WIRES = "SKINNY_WIRES",
  KRAZY_TALK = "KRAZY_TALK",
  NUMBERS = "NUMBERS",
  ALCHEMY = "ALCHEMY",
  COOKIE_JARS = "COOKIE_JARS",
  FREE_PARKING = "FREE_PARKING",
  SIMONS_STAGES = "SIMONS_STAGES",
  VARICOLORED_SQUARES = "VARICOLORED_SQUARES",
  ZONI = "ZONI",
  MAD_MEMORY = "MAD_MEMORY",
  UNRELATED_ANAGRAMS = "UNRELATED_ANAGRAMS",
  BARTENDING = "BARTENDING",
  QUESTION_MARK = "QUESTION_MARK",
  DECOLORED_SQUARES = "DECOLORED_SQUARES",
  FLAVOR_TEXT = "FLAVOR_TEXT",
  FLAVOR_TEXT_EX = "FLAVOR_TEXT_EX",
  SHAPES_AND_BOMBS = "SHAPES_AND_BOMBS",
  HOMOPHONES = "HOMOPHONES",
  DETONATO = "DETONATO",
  SYNC_125_3 = "SYNC_125_3",
  WESTEROS = "WESTEROS",
}

export enum PortType {
  COMPOSITE_VIDEO = "COMPOSITE_VIDEO",
  DVI = "DVI",
  HDMI = "HDMI",
  PARALLEL = "PARALLEL",
  PS2 = "PS2",
  RJ45 = "RJ45",
  SERIAL = "SERIAL",
  STEREO_RCA = "STEREO_RCA",
  USB = "USB",
}

export enum BombStatus {
  ACTIVE = "ACTIVE",
  DEFUSED = "DEFUSED",
  EXPLODED = "EXPLODED",
}

export enum RoundStatus {
  SETUP = "SETUP",
  ACTIVE = "ACTIVE",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
}

export type JsonRecord = Record<string, unknown>;

export interface ModuleEntity {
  id: string;
  type: string;
  solved: boolean;
  version: number;
  twitchCode?: string;
  state: JsonRecord;
  solution: JsonRecord;
}

export interface PortPlateEntity {
  id?: string;
  ports: PortType[];
}

export interface BombEntity {
  id: string;
  serialNumber: string;
  aaBatteryCount: number;
  dBatteryCount: number;
  indicators: Record<string, boolean>;
  portPlates: PortPlateEntity[];
  status: BombStatus;
  strikes: number;
  modules: ModuleEntity[];
}

export interface RoundEntity {
  id: string;
  status: RoundStatus;
  startTime?: string;
  version?: number;
  bombs: BombEntity[];
  roundState: JsonRecord;
}

export interface BombSummary {
  serialNumber?: string;
  aaBatteryCount: number;
  dBatteryCount: number;
  indicators: Record<string, boolean>;
  ports: PortType[];
  moduleTypes: string[];
}

export interface RoundSummary {
  id: string;
  status: RoundStatus;
  startTime?: string;
  version?: number;
  bombCount: number;
  moduleCount: number;
  bombs: BombSummary[];
}

export interface CreateBombRequest {
  serialNumber: string;
  aaBatteryCount: number;
  dBatteryCount: number;
  indicators: Record<string, boolean>;
  portPlates: PortType[][];
  modules?: Record<string, number>;
}

export interface BombConfig {
  serialNumber?: string;
  aaBatteryCount?: number;
  dBatteryCount?: number;
  indicators?: Record<string, boolean>;
  portPlates?: PortType[][];
}

export interface ModuleCatalogItem {
  id: string;
  name: string;
  category: ModuleCategory;
  type: string;
  tags: string[];
  description: string;
  hasInput: boolean;
  hasOutput: boolean;
  checkFirst?: boolean;
}

export enum ModuleCategory {
  VANILLA_REGULAR = "VANILLA_REGULAR",
  VANILLA_NEEDY = "VANILLA_NEEDY",
  MODDED_REGULAR = "MODDED_REGULAR",
  MODDED_NEEDY = "MODDED_NEEDY",
}

export interface AddModulesRequest {
  type: string;
  count: number;
}

export type RoundEventType =
  | "MODULE_UPDATED"
  | "MODULE_SOLVED"
  | "MODULE_STRIKE"
  | "ROUND_STRIKE"
  | "MEMORY_STAGE_COMPLETED"
  | "ROUND_UPDATED";

export interface RoundEventMessage {
  type: RoundEventType;
  timestamp?: string;
  id?: string;
  payload: Record<string, unknown>;
}
