package ktanesolver.module.modded.regular.alchemy;

import java.util.*;import org.springframework.stereotype.Service;import ktanesolver.annotation.ModuleInfo;import ktanesolver.dto.ModuleCatalogDto;import ktanesolver.entity.*;import ktanesolver.enums.ModuleType;import ktanesolver.logic.*;

@Service @ModuleInfo(type=ModuleType.ALCHEMY,id="JuckAlchemy",name="Alchemy",category=ModuleCatalogDto.ModuleCategory.MODDED_REGULAR,description="Follow Alchemy's redraw and transmutation flow from the seven displayed symbols.",tags={"symbols","flowchart","multi-step"})
public class AlchemySolver extends AbstractModuleSolver<AlchemySolver.Input,AlchemySolver.Output>{
 public record Input(String center,List<String> outerSymbols)implements ModuleInput{} public record Output(int flowStep,List<String> actions,boolean redrawRequired)implements ModuleOutput{} public record State(int step){public State(){this(0);}}
 private static final Set<String> SYMBOLS=Set.of("creation","fire","heva","meta","strucota","terra");
 @Override protected SolveResult<Output> doSolve(RoundEntity r,BombEntity b,ModuleEntity m,Input in){if(in==null||in.center()==null||in.outerSymbols()==null||in.outerSymbols().size()!=6)return failure("Enter the center and six outer symbols in clockwise order from bottom-right");String c=n(in.center());List<String>o=in.outerSymbols().stream().map(AlchemySolver::n).toList();if(!SYMBOLS.contains(c)||!new HashSet<>(o).equals(SYMBOLS))return failure("Use each of Creation, Fire, Heva, Meta, Strucota, and Terra once around a valid center");int step=m.getStateAs(State.class,State::new).step();List<String>a=new ArrayList<>();boolean redraw=false;boolean solved=false;int next=step;
  if(step==0){boolean perfect=!(opposite(o,"creation","terra")||adjacent(o,"heva","meta")||(o.get(4).equals("fire")&&b.isLastDigitEven()));if(!perfect){String f=o.get(3).equals("heva")?"Mind":o.get(0).equals("creation")?"Life":o.get(1).equals("terra")?"Energy":o.get(4).equals("strucota")?"Matter":o.get(5).equals("fire")?"Flames":null;if(f!=null)a.add("set frequency "+f);a.add("redraw");redraw=true;}else switch(c){case"fire"->next=3;case"meta"->next=2;case"strucota"->next=5;case"heva"->next=4;case"creation"->{a.add("submit");a.add("set frequency Life");a.add("submit");solved=true;}default->{a.add("press Fire");next=3;}}}
  else switch(step){case 2->{if(c.equals("terra")){a.add("set frequency Life");a.add("press Heva");next=8;}else if(c.equals("meta")){a.add("press Heva");next=5;}else if(c.equals("fire")){a.add("set frequency Mind");a.add("press Strucota");next=6;}else{a.add("redraw");next=3;redraw=true;}}case 3->{if(b.isIndicatorLit("TRN")){a.add("set frequency Energy");a.add("redraw");next=6;redraw=true;}else next=4;}case 4->{if(c.equals("terra")){a.add("set frequency Energy");a.add("redraw");next=10;redraw=true;}else if(c.equals("creation")){a.add("press Fire");next=7;}else if(c.equals("fire")){a.add("set frequency Life");a.add("press Strucota");next=9;}else{a.add("redraw");next=5;redraw=true;}}case 5->{if(b.isIndicatorLit("SND")){a.add("set frequency Life");a.add("redraw");next=8;redraw=true;}else next=10;}case 6->{a.addAll(List.of("press Terra","submit","set frequency Mind","submit"));solved=true;}case 7->{a.addAll(List.of("press Creation","submit","set frequency Life","submit"));solved=true;}case 8->{a.addAll(List.of("press Terra","submit","set frequency Matter","submit"));solved=true;}case 9->{a.addAll(List.of("press Creation","submit","set frequency Flames","submit"));solved=true;}case 10->{a.addAll(List.of("press Heva","submit","set frequency Energy","submit"));solved=true;}default->{return failure("Invalid stored Alchemy flow step");}}
  if(!solved)storeTypedState(m,new State(next));return success(new Output(next,a,redraw),solved);}
 private static String n(String s){return s==null?"":s.trim().toLowerCase();}private static boolean opposite(List<String>x,String a,String b){int i=x.indexOf(a),j=x.indexOf(b);return Math.floorMod(i-j,6)==3;}private static boolean adjacent(List<String>x,String a,String b){int i=x.indexOf(a),j=x.indexOf(b);return Math.floorMod(i-j,6)==1||Math.floorMod(j-i,6)==1;}
}
