/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        paper: '#F9F6EE',
        ink: '#1C1917',
        'ink-muted': '#6B7280',
        'ink-subtle': '#9CA3AF',
        'border-strong': '#1C1917',
      },
      fontFamily: {
        display: ['Oswald', 'sans-serif'],
        sans: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      boxShadow: {
        'card': '2px 2px 0 var(--shadow-ink, #1C1917)',
        'card-hover': '3px 3px 0 var(--shadow-ink, #1C1917)',
        'card-sm': '1px 1px 0 var(--shadow-ink, #1C1917)',
      },
      keyframes: {
        'fade-in': {
          from: { opacity: '0', transform: 'translateY(4px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'slide-in-right': {
          from: { transform: 'translateX(100%)' },
          to: { transform: 'translateX(0)' },
        },
        'slide-out-right': {
          from: { transform: 'translateX(0)' },
          to: { transform: 'translateX(100%)' },
        },
        'pulse-success': {
          '0%, 100%': { boxShadow: '0 0 0 0 rgba(21, 128, 61, 0.3)' },
          '50%': { boxShadow: '0 0 0 8px rgba(21, 128, 61, 0)' },
        },
      },
      animation: {
        'fade-in': 'fade-in 0.15s ease-out',
        'slide-in-right': 'slide-in-right 0.25s ease-out',
        'slide-out-right': 'slide-out-right 0.25s ease-in',
        'pulse-success': 'pulse-success 1s ease-in-out 2',
      },
    },
  },
  plugins: [require("flyonui")],
  flyonui: {
    themes: [
      {
        manual: {
          "primary": "#C41230",
          "primary-focus": "#9B0E26",
          "primary-content": "#FFFFFF",
          "secondary": "#374151",
          "secondary-focus": "#1F2937",
          "secondary-content": "#FFFFFF",
          "accent": "#B45309",
          "accent-focus": "#92400E",
          "accent-content": "#FFFFFF",
          "neutral": "#6B7280",
          "neutral-focus": "#4B5563",
          "neutral-content": "#FFFFFF",
          "base-100": "#F9F6EE",
          "base-200": "#F0EBE0",
          "base-300": "#E2D9CA",
          "base-content": "#1C1917",
          "info": "#1D4ED8",
          "info-content": "#FFFFFF",
          "success": "#15803D",
          "success-content": "#FFFFFF",
          "warning": "#B45309",
          "warning-content": "#FFFFFF",
          "error": "#C41230",
          "error-content": "#FFFFFF",
        },
      },
      {
        "manual-dark": {
          "primary": "#C41230",
          "primary-focus": "#9B0E26",
          "primary-content": "#FFFFFF",
          "secondary": "#9CA3AF",
          "secondary-focus": "#6B7280",
          "secondary-content": "#FFFFFF",
          "accent": "#D97706",
          "accent-focus": "#B45309",
          "accent-content": "#FFFFFF",
          "neutral": "#6B7280",
          "neutral-focus": "#4B5563",
          "neutral-content": "#FFFFFF",
          "base-100": "#1C1917",
          "base-200": "#292524",
          "base-300": "#3C3330",
          "base-content": "#F5F0E8",
          "info": "#3B82F6",
          "info-content": "#FFFFFF",
          "success": "#16A34A",
          "success-content": "#FFFFFF",
          "warning": "#D97706",
          "warning-content": "#FFFFFF",
          "error": "#DC2626",
          "error-content": "#FFFFFF",
        },
      },
    ],
    defaultTheme: "manual",
    base: true,
    styled: true,
    utils: true,
    prefix: "",
    logs: false,
    themeRoot: ":root",
  },
}
