package ktanesolver.module.modded.regular.yellowarrows;
import java.util.ArrayList;import java.util.List;import java.util.Locale;import org.springframework.stereotype.Service;import ktanesolver.annotation.ModuleInfo;import ktanesolver.dto.ModuleCatalogDto;import ktanesolver.entity.*;import ktanesolver.enums.*;import ktanesolver.logic.*;
@Service
@ModuleInfo(type=ModuleType.YELLOW_ARROWS,id="yellowArrowsModule",name="Yellow Arrows",category=ModuleCatalogDto.ModuleCategory.MODDED_REGULAR,description="Advance through five rule rows from the displayed letter and serial offset.",tags={"arrows","letters","edgework","sequences"})
public class YellowArrowsSolver extends AbstractModuleSolver<YellowArrowsInput,YellowArrowsOutput>{
 @Override protected SolveResult<YellowArrowsOutput>doSolve(RoundEntity round,BombEntity bomb,ModuleEntity module,YellowArrowsInput input){
  if(input==null||input.startingRow()==null||!input.startingRow().trim().toUpperCase(Locale.ROOT).matches("[A-Z]"))return failure("Enter the displayed starting-row letter");String serial=bomb.getSerialNumber();if(serial==null||!serial.matches("[A-Za-z0-9]{6}"))return failure("Enter the six-character bomb serial number first");
  String row=input.startingRow().trim().toUpperCase(Locale.ROOT);List<String>previous=input.resetSequence()?new ArrayList<>():strings(module.getState().get("yellowArrowsPresses"));int current=input.resetSequence()?row.charAt(0)-'A':number(module.getState().get("yellowArrowsCurrentRow"),row.charAt(0)-'A');current=(current+bomb.getLastDigit()+1)%26;
  String direction=direction(current,previous,bomb);previous.add(direction);storeState(module,"yellowArrowsStartingRow",row);storeState(module,"yellowArrowsCurrentRow",current);storeState(module,"yellowArrowsPresses",List.copyOf(previous));boolean done=previous.size()==5;return success(new YellowArrowsOutput(direction,String.valueOf((char)('A'+current)),previous.size(),done),done);
 }
 private static String direction(int row,List<String>p,BombEntity b){String last=p.isEmpty()?"":p.get(p.size()-1);return switch(row){case 0->"up";case 1->last.equals("left")?"down":"right";case 2->b.getLastDigit()==3?"left":"up";case 3->"down";case 4->b.isIndicatorLit("SIG")?"right":"left";case 5->b.hasPort(PortType.PS2)?"up":"down";case 6->p.contains("down")?"down":"up";case 7->b.hasPort(PortType.SERIAL)?"up":"right";case 8->hasNeedy(b)?"up":"down";case 9->last.equals("down")?"left":"up";case 10->"down";case 11->b.getBatteryCount()==0?"up":"down";case 12->b.getBatteryHolders()<3?"right":"left";case 13->"right";case 14->b.getSerialNumber().toUpperCase(Locale.ROOT).contains("O")?"left":"down";case 15->b.getSerialNumber().chars().filter(Character::isLetter).count()==4?"down":"up";case 16->last.equals("right")?"down":"left";case 17->b.isIndicatorUnlit("CLR")?"up":"down";case 18->"left";case 19->b.getBatteryCount()%2==0?"left":"down";case 20->"up";case 21->last.equals("up")?"up":"down";case 22->b.getPortPlates().isEmpty()?"right":"up";case 23->"left";case 24->"up";default->"right";};}
 private static boolean hasNeedy(BombEntity b){return b.getModules().stream().anyMatch(m->m.getType()!=null&&m.getType().isNeedy());}private static int number(Object v,int fallback){return v instanceof Number n?n.intValue():fallback;}private static List<String>strings(Object v){if(!(v instanceof List<?>l))return new ArrayList<>();return new ArrayList<>(l.stream().map(String::valueOf).toList());}
}
