import { useState } from "react";
import { solveBabaIsWho, type BabaAttribute, type BabaCharacter, type BabaIsWhoOutput } from "../../services/babaIsWhoService";
import type { BombEntity } from "../../types";
import { ErrorAlert, SolverControls, SolverLayout, SolverSection, useSolver } from "../common";
const characters: BabaCharacter[] = ["BABA","KEKE","ME","ROCK","FLAG","WALL"];
const attributes: BabaAttribute[] = ["YOU","MOVE","DEFEAT","PUSH","WIN","STOP"];
export default function BabaIsWhoSolver({ bomb }: { bomb: BombEntity | null | undefined }) {
  const [rules, setRules] = useState(characters.map((subject, i) => ({ subject, attribute: attributes[i] })));
  const [buttons, setButtons] = useState(characters.map((character, i) => ({ character, attribute: attributes[i] })));
  const [result, setResult] = useState<BabaIsWhoOutput | null>(null);
  const { isLoading,error,isSolved,setIsLoading,setError,setIsSolved,clearError,currentModule,round,markModuleSolved } = useSolver();
  const solve = async () => { if (!round?.id || !bomb?.id || !currentModule?.id) return setError("Missing required information"); setIsLoading(true); clearError(); try { const response = await solveBabaIsWho(round.id,bomb.id,currentModule.id,{rules,buttons}); setResult(response.output); setIsSolved(response.solved); if(response.solved)markModuleSolved(bomb.id,currentModule.id); } catch(cause){setError(cause instanceof Error?cause.message:"Failed to solve Baba Is Who?");} finally{setIsLoading(false);} };
  const select = "h-10 rounded-md border bg-background px-2";
  return <SolverLayout><SolverSection title="Rules in displayed order"><div className="space-y-2">{rules.map((rule,i)=><div key={i} className="grid grid-cols-[2rem_1fr_auto_1fr] items-center gap-2"><span>{i+1}.</span><select value={rule.subject} onChange={e=>setRules(values=>values.map((v,j)=>j===i?{...v,subject:e.target.value as BabaCharacter}:v))} className={select}>{characters.map(x=><option key={x}>{x}</option>)}</select><span>IS</span><select value={rule.attribute} onChange={e=>setRules(values=>values.map((v,j)=>j===i?{...v,attribute:e.target.value as BabaAttribute}:v))} className={select}>{attributes.map(x=><option key={x}>{x}</option>)}</select></div>)}</div></SolverSection><SolverSection title="3×2 button grid (reading order)"><div className="grid grid-cols-3 gap-3">{buttons.map((button,i)=><div key={i} className="space-y-2 rounded-md border p-2"><select value={button.character} onChange={e=>setButtons(values=>values.map((v,j)=>j===i?{...v,character:e.target.value as BabaCharacter}:v))} className={`${select} w-full`}>{characters.map(x=><option key={x}>{x}</option>)}</select><select value={button.attribute} onChange={e=>setButtons(values=>values.map((v,j)=>j===i?{...v,attribute:e.target.value as BabaAttribute}:v))} className={`${select} w-full`}>{attributes.map(x=><option key={x}>{x}</option>)}</select></div>)}</div></SolverSection><SolverControls onSolve={solve} onReset={()=>{setResult(null);setIsSolved(false);}} isLoading={isLoading} isSolved={isSolved}/><ErrorAlert error={error}/>{result&&<SolverSection title="Press"><p className="text-center text-3xl font-bold">{result.position}: {result.character} IS {result.attribute}</p><p className="text-center text-sm">{result.appliedRule?`Rule ${result.appliedRule}`:"No rule applied"}{result.defeatShifted?"; shifted right because the original target was DEFEAT":""}</p></SolverSection>}</SolverLayout>;
}
