import { useCallback, useMemo, useState } from "react";
import { BENEDICT_LEFT_LISTS, BENEDICT_LEFT_PREFIXES, BENEDICT_RIGHT_LISTS, BENEDICT_RIGHT_PREFIXES, solveBenedictCumberbatch, type BenedictCumberbatchOutput } from "../../services/benedictCumberbatchService";
import { useRoundStore } from "../../store/useRoundStore";import { ModuleType, type BombEntity } from "../../types";import { generateTwitchCommand } from "../../utils/twitchCommands";import { ErrorAlert, SolverControls, SolverInstructions, SolverLayout, SolverSection, TwitchCommandDisplay, useSolver, useSolverModulePersistence } from "../common";
export default function BenedictCumberbatchSolver({ bomb }: { bomb: BombEntity | null | undefined }) {
  const [leftPrefix,setLeftPrefix]=useState<string>("Bene"),[leftList,setLeftList]=useState<string>("Bene"),[rightPrefix,setRightPrefix]=useState<string>("Cumber"),[rightList,setRightList]=useState<string>("Cumber"),[result,setResult]=useState<BenedictCumberbatchOutput|null>(null),[twitchCommand,setTwitchCommand]=useState("");
  const {isLoading,error,isSolved,setIsLoading,setError,setIsSolved,clearError,reset:resetSolverState,currentModule,round,markModuleSolved}=useSolver();const updateModuleAfterSolve=useRoundStore((s)=>s.updateModuleAfterSolve);const state=useMemo(()=>({leftPrefix,leftList,rightPrefix,rightList,result,twitchCommand}),[leftPrefix,leftList,rightPrefix,rightList,result,twitchCommand]);
  useSolverModulePersistence<typeof state,BenedictCumberbatchOutput>({state,onRestoreState:useCallback((s)=>{if(s.leftPrefix)setLeftPrefix(s.leftPrefix);if(s.leftList)setLeftList(s.leftList);if(s.rightPrefix)setRightPrefix(s.rightPrefix);if(s.rightList)setRightList(s.rightList);if(s.result)setResult(s.result);if(s.twitchCommand)setTwitchCommand(s.twitchCommand);},[]),onRestoreSolution:useCallback((solution:BenedictCumberbatchOutput)=>{setResult(solution);setTwitchCommand(generateTwitchCommand({moduleType:ModuleType.BENEDICT_CUMBERBATCH,result:solution}));},[]),currentModule,setIsSolved});
  const solve=async()=>{if(!round?.id||!bomb?.id||!currentModule?.id)return setError("Missing required information");clearError();setIsLoading(true);try{const response=await solveBenedictCumberbatch(round.id,bomb.id,currentModule.id,leftPrefix,leftList,rightPrefix,rightList);const command=generateTwitchCommand({moduleType:ModuleType.BENEDICT_CUMBERBATCH,result:response.output});setResult(response.output);setTwitchCommand(command);setIsSolved(response.solved);if(response.solved)markModuleSolved(bomb.id,currentModule.id);updateModuleAfterSolve(bomb.id,currentModule.id,{leftPrefix,leftList,rightPrefix,rightList,result:response.output,twitchCommand:command},response.output,response.solved);}catch(cause){setError(cause instanceof Error?cause.message:"Failed to solve Benedict Cumberbatch");}finally{setIsLoading(false);}};const reset=()=>{setResult(null);setTwitchCommand("");resetSolverState();};
  const select=(label:string,value:string,change:(v:string)=>void,options:readonly string[])=><label className="space-y-1"><span className="text-sm font-medium">{label}</span><select value={value} onChange={(e)=>{change(e.target.value);setResult(null);setTwitchCommand("");clearError();}} className="w-full rounded-md border border-input bg-background p-2">{options.map((o)=><option key={o}>{o}</option>)}</select></label>;
  return <SolverLayout><SolverSection title="Rolodexes" description="For a special displayed prefix, flip through suffix cards to identify its table-list heading."><div className="grid gap-3 sm:grid-cols-2">{select("Forename prefix",leftPrefix,setLeftPrefix,BENEDICT_LEFT_PREFIXES)}{select("Forename suffix list",leftList,setLeftList,BENEDICT_LEFT_LISTS)}{select("Surname prefix",rightPrefix,setRightPrefix,BENEDICT_RIGHT_PREFIXES)}{select("Surname suffix list",rightList,setRightList,BENEDICT_RIGHT_LISTS)}</div></SolverSection><SolverControls onSolve={solve} onReset={reset} isLoading={isLoading} isSolved={isSolved} solveText="Build name"/><ErrorAlert error={error}/>{result&&<SolverSection title="Correct name" className="border-emerald-500/40"><p className="text-2xl font-bold">{result.forename} {result.surname}</p><p>Suffix indices: {result.leftIndex} and {result.rightIndex}</p></SolverSection>}{twitchCommand&&<TwitchCommandDisplay command={twitchCommand}/>}<SolverInstructions>The module continuously recalculates the forename after more than half of the bomb's solvable modules are solved; solve again if that threshold changes before submission.</SolverInstructions></SolverLayout>;
}
