import { useCallback, useMemo, useState } from "react";
import { solveBoggle, type BoggleOutput, type BoggleVisibleCell } from "../../services/boggleService";
import { useRoundStore } from "../../store/useRoundStore";
import { ModuleType, type BombEntity } from "../../types";
import { generateTwitchCommand } from "../../utils/twitchCommands";
import { ErrorAlert, SolverControls, SolverInstructions, SolverLayout, SolverSection, TwitchCommandDisplay, useSolver, useSolverModulePersistence } from "../common";

const CELLS = Array.from({ length: 16 }, (_, index) => `${"ABCD"[index % 4]}${Math.floor(index / 4) + 1}`);
const INITIAL: BoggleVisibleCell[] = ["A1", "B1", "C1", "D1"].map((cell) => ({ cell, letter: "" }));

export default function BoggleSolver({ bomb }: { bomb: BombEntity | null | undefined }) {
  const [visible, setVisible] = useState<BoggleVisibleCell[]>(INITIAL), [result, setResult] = useState<BoggleOutput | null>(null), [twitchCommand, setTwitchCommand] = useState("");
  const { isLoading, error, isSolved, setIsLoading, setError, setIsSolved, clearError, reset: resetSolverState, currentModule, round, markModuleSolved } = useSolver();
  const updateModuleAfterSolve = useRoundStore((state) => state.updateModuleAfterSolve);
  const state = useMemo(() => ({ visible, result, twitchCommand }), [visible, result, twitchCommand]);
  useSolverModulePersistence<typeof state, BoggleOutput>({ state, onRestoreState: useCallback((saved) => { if (saved.visible) setVisible(saved.visible); if (saved.result) setResult(saved.result); if (saved.twitchCommand) setTwitchCommand(saved.twitchCommand); }, []), onRestoreSolution: useCallback((solution: BoggleOutput) => { setResult(solution); setTwitchCommand(generateTwitchCommand({ moduleType: ModuleType.BOGGLE, result: solution })); }, []), currentModule, setIsSolved });
  const update = (index: number, change: Partial<BoggleVisibleCell>) => { setVisible((cells) => cells.map((cell, cellIndex) => cellIndex === index ? { ...cell, ...change } : cell)); setResult(null); setTwitchCommand(""); clearError(); };
  const solve = async () => { if (!round?.id || !bomb?.id || !currentModule?.id) return setError("Missing required information"); clearError(); setIsLoading(true); try { const normalized = visible.map(({ cell, letter }) => ({ cell: cell.toUpperCase(), letter: letter.trim().toUpperCase() })); const response = await solveBoggle(round.id, bomb.id, currentModule.id, normalized); const command = generateTwitchCommand({ moduleType: ModuleType.BOGGLE, result: response.output }); setResult(response.output); setTwitchCommand(command); setIsSolved(response.solved); if (response.solved) markModuleSolved(bomb.id, currentModule.id); updateModuleAfterSolve(bomb.id, currentModule.id, { visible: normalized, result: response.output, twitchCommand: command }, response.output, response.solved); } catch (cause) { setError(cause instanceof Error ? cause.message : "Failed to solve Boggle"); } finally { setIsLoading(false); } };
  const reset = () => { setVisible(INITIAL); setResult(null); setTwitchCommand(""); resetSolverState(); };
  return <SolverLayout><SolverSection title="Initially visible letters" description="Enter the four lit cells and their letters before pressing anything."><div className="grid gap-3 sm:grid-cols-2">{visible.map((entry, index) => <div key={index} className="flex gap-2"><select aria-label={`Visible cell ${index + 1}`} value={entry.cell} onChange={(event) => update(index, { cell: event.target.value })} className="rounded-md border border-input bg-background p-2">{CELLS.map((cell) => <option key={cell}>{cell}</option>)}</select><input aria-label={`Visible letter ${index + 1}`} value={entry.letter} onChange={(event) => update(index, { letter: event.target.value.replace(/[^a-z]/gi, "").slice(0, 1).toUpperCase() })} maxLength={1} className="w-full rounded-md border border-input bg-background p-2 uppercase" placeholder="Letter" /></div>)}</div></SolverSection><SolverControls onSolve={solve} onReset={reset} isLoading={isLoading} isSolved={isSolved} solveText="Find words"/><ErrorAlert error={error}/>{result && <><SolverSection title="Board"><div className="grid w-fit grid-cols-4 gap-1 font-mono text-xl">{result.board.flatMap((row) => [...row]).map((letter, index) => <span key={index} className="flex size-9 items-center justify-center rounded border">{letter}</span>)}</div></SolverSection><SolverSection title={`Words — ${result.score} points`} className="border-emerald-500/40">{result.plays.map((play) => <p key={play.word}><strong>{play.word.toUpperCase()}</strong> ({play.score}): {play.cells.join(" ")}</p>)}</SolverSection></>}{twitchCommand && <TwitchCommandDisplay command={twitchCommand}/>}<SolverInstructions>Submit each listed word as a separate Twitch command. Q consumes an implicit U without another tile. A rejected word does not change the board.</SolverInstructions></SolverLayout>;
}
