import { useState } from "react";
import { COLORED_KEYS_COLORS, solveColoredKeys, type ColoredKey, type ColoredKeysOutput } from "../../services/coloredKeysService";
import type { BombEntity } from "../../types";
import { ErrorAlert, SolverControls, SolverInstructions, SolverLayout, SolverSection, TwitchCommandDisplay, useSolver } from "../common";

const positions = ["Top left", "Top right", "Bottom left", "Bottom right"];
export default function ColoredKeysSolver({ bomb }: { bomb: BombEntity | null | undefined }) {
  const [word, setWord] = useState("red"), [displayColor, setDisplayColor] = useState("red");
  const [keys, setKeys] = useState<ColoredKey[]>(positions.map(() => ({ color: "red", letter: "A" })));
  const [result, setResult] = useState<ColoredKeysOutput | null>(null);
  const { isLoading, error, isSolved, setIsLoading, setError, setIsSolved, clearError, reset: resetSolverState, currentModule, round, markModuleSolved } = useSolver();
  const solve = async () => { if (!round?.id || !bomb?.id || !currentModule?.id) return setError("Missing required information"); clearError(); setIsLoading(true); try { const response = await solveColoredKeys(round.id, bomb.id, currentModule.id, word, displayColor, keys); setResult(response.output); setIsSolved(response.solved); if (response.solved) markModuleSolved(bomb.id, currentModule.id); } catch (cause) { setError(cause instanceof Error ? cause.message : "Failed to solve Colored Keys"); } finally { setIsLoading(false); } };
  const reset = () => { setWord("red"); setDisplayColor("red"); setKeys(positions.map(() => ({ color: "red", letter: "A" }))); setResult(null); resetSolverState(); };
  const colors = (label: string, value: string, change: (value: string) => void) => <label>{label}<select aria-label={label} value={value} onChange={event => { change(event.target.value); setResult(null); clearError(); }} className="mt-1 h-11 w-full rounded border bg-background px-2">{COLORED_KEYS_COLORS.map(color => <option key={color}>{color}</option>)}</select></label>;
  return <SolverLayout><SolverSection title="Display"><div className="grid grid-cols-2 gap-3">{colors("Displayed word", word, setWord)}{colors("Word color", displayColor, setDisplayColor)}</div></SolverSection><SolverSection title="Keys"><div className="grid grid-cols-2 gap-3">{keys.map((key, index) => <div key={positions[index]}><p>{positions[index]}</p><select aria-label={`${positions[index]} color`} value={key.color} onChange={event => { const next = [...keys]; next[index] = { ...key, color: event.target.value }; setKeys(next); setResult(null); }} className="h-11 w-full rounded border bg-background px-2">{COLORED_KEYS_COLORS.map(color => <option key={color}>{color}</option>)}</select><input aria-label={`${positions[index]} letter`} maxLength={1} value={key.letter} onChange={event => { const next = [...keys]; next[index] = { ...key, letter: event.target.value.toUpperCase() }; setKeys(next); setResult(null); }} className="mt-1 h-11 w-full rounded border bg-background px-2 uppercase" /></div>)}</div></SolverSection><SolverControls onSolve={solve} onReset={reset} isLoading={isLoading} isSolved={isSolved} /><ErrorAlert error={error} />{result && <SolverSection title={`Press ${result.position}`} className="border-emerald-500/40"><p>Scores: {result.scores.join(" / ")}</p></SolverSection>}{result && <TwitchCommandDisplay command={`!number ${result.keyPosition}`} />}<SolverInstructions>The verified upstream parser accepts button numbers 1–4 in reading order.</SolverInstructions></SolverLayout>;
}
