import { useCallback, useMemo, useState } from "react";
import { solveCrypticPassword, type CrypticPasswordOutput } from "../../services/crypticPasswordService";
import { useRoundStore } from "../../store/useRoundStore";
import { ModuleType, type BombEntity } from "../../types";
import { generateTwitchCommand } from "../../utils/twitchCommands";
import { ErrorAlert, SolverControls, SolverInstructions, SolverLayout, SolverSection, TwitchCommandDisplay, useSolver, useSolverModulePersistence } from "../common";

export default function CrypticPasswordSolver({ bomb }: { bomb: BombEntity | null | undefined }) {
  const [startingWord, setStartingWord] = useState(""), [keyWord, setKeyWord] = useState("");
  const [result, setResult] = useState<CrypticPasswordOutput | null>(null), [twitchCommand, setTwitchCommand] = useState("");
  const { isLoading, error, isSolved, setIsLoading, setError, setIsSolved, clearError, reset: resetSolverState, currentModule, round, markModuleSolved } = useSolver();
  const updateModuleAfterSolve = useRoundStore(state => state.updateModuleAfterSolve);
  const state = useMemo(() => ({ startingWord, keyWord, result, twitchCommand }), [startingWord, keyWord, result, twitchCommand]);
  useSolverModulePersistence<typeof state, CrypticPasswordOutput>({ state, onRestoreState: useCallback(saved => { if (saved.startingWord) setStartingWord(saved.startingWord); if (saved.keyWord) setKeyWord(saved.keyWord); if (saved.result) setResult(saved.result); if (saved.twitchCommand) setTwitchCommand(saved.twitchCommand); }, []), onRestoreSolution: useCallback((solution: CrypticPasswordOutput) => { setResult(solution); setTwitchCommand(generateTwitchCommand({ moduleType: ModuleType.CRYPTIC_PASSWORD, result: solution })); }, []), currentModule, setIsSolved });
  const changed = () => { setResult(null); setTwitchCommand(""); setIsSolved(false); clearError(); };
  const solve = async () => { if (!round?.id || !bomb?.id || !currentModule?.id) return setError("Missing required information"); clearError(); setIsLoading(true); try { const response = await solveCrypticPassword(round.id, bomb.id, currentModule.id, startingWord, keyWord); const command = generateTwitchCommand({ moduleType: ModuleType.CRYPTIC_PASSWORD, result: response.output }); setResult(response.output); setTwitchCommand(command); setIsSolved(response.solved); if (response.solved) markModuleSolved(bomb.id, currentModule.id); updateModuleAfterSolve(bomb.id, currentModule.id, { startingWord, keyWord, result: response.output, twitchCommand: command }, response.output, response.solved); } catch (cause) { setError(cause instanceof Error ? cause.message : "Failed to solve Cryptic Password"); } finally { setIsLoading(false); } };
  const reset = () => { setStartingWord(""); setKeyWord(""); setResult(null); setTwitchCommand(""); resetSolverState(); };
  const field = (label: string, value: string, maxLength: number, setValue: (value: string) => void) => <label>{label}<input aria-label={label} maxLength={maxLength} value={value} onChange={event => { setValue(event.target.value.toUpperCase().replace(/[^A-Z]/g, "")); changed(); }} className="mt-1 h-11 w-full rounded border bg-background px-3 font-mono uppercase" /></label>;
  return <SolverLayout><SolverSection title="Displayed words"><div className="grid gap-3 sm:grid-cols-2">{field("Starting word", startingWord, 6, setStartingWord)}{field("Key word", keyWord, 6, setKeyWord)}</div></SolverSection><SolverControls onSolve={solve} onReset={reset} isLoading={isLoading} isSolved={isSolved} solveText="Encrypt word" /><ErrorAlert error={error} />{result && <SolverSection title="Submit this word" className="border-emerald-500/40"><p className="font-mono text-5xl font-bold tracking-widest">{result.answer}</p><p className="mt-2 text-sm text-muted-foreground">Effective key: {result.effectiveKey}{result.transposedTable ? " · transposed table" : ""}</p></SolverSection>}{twitchCommand && <TwitchCommandDisplay command={twitchCommand} />}<SolverInstructions>This solver implements the canonical default rule seed. Enter the top six-letter word and the bottom three-to-six-letter key.</SolverInstructions></SolverLayout>;
}
