import { useState } from "react";
import { solveFindTheDate, type FindTheDateOutput } from "../../services/findTheDateService";
import { ModuleType, type BombEntity } from "../../types";
import { generateTwitchCommand } from "../../utils/twitchCommands";
import { ErrorAlert, SolverControls, SolverLayout, SolverSection, TwitchCommandDisplay, useSolver } from "../common";
const months = ["January","February","March","April","May","June","July","August","September","October","November","December"];
export default function FindTheDateSolver({ bomb }: { bomb: BombEntity | null | undefined }) {
  const [stage, setStage] = useState(1), [day, setDay] = useState(1), [month, setMonth] = useState("January"), [year, setYear] = useState(0);
  const [result, setResult] = useState<FindTheDateOutput | null>(null), [command, setCommand] = useState(""); const { isLoading, error, isSolved, setIsLoading, setError, setIsSolved, clearError, currentModule, round, markModuleSolved } = useSolver();
  const solve = async () => { if (!round?.id || !bomb?.id || !currentModule?.id) return setError("Missing required information"); setIsLoading(true); clearError(); try { const response = await solveFindTheDate(round.id, bomb.id, currentModule.id, { day, month, year }); setResult(response.output); setStage(response.output.nextStage); const next = generateTwitchCommand({ moduleType: ModuleType.FIND_THE_DATE, result: response.output }); setCommand(next); setIsSolved(response.solved); if (response.solved) markModuleSolved(bomb.id, currentModule.id); } catch (cause) { setError(cause instanceof Error ? cause.message : "Failed to solve Find The Date"); } finally { setIsLoading(false); } };
  return <SolverLayout><SolverSection title={`Stage ${stage} date`}><div className="grid gap-3 sm:grid-cols-3"><label>Day<input type="number" min={1} max={30} value={day} onChange={(e) => setDay(Number(e.target.value))} className="mt-1 block h-11 w-full rounded-md border bg-background px-3" /></label><label>Month<select value={month} onChange={(e) => setMonth(e.target.value)} className="mt-1 block h-11 w-full rounded-md border bg-background px-3">{months.map(x => <option key={x}>{x}</option>)}</select></label><label>Year (000–2899)<input type="number" min={0} max={2899} value={year} onChange={(e) => setYear(Number(e.target.value))} className="mt-1 block h-11 w-full rounded-md border bg-background px-3" /></label></div></SolverSection><SolverControls onSolve={solve} onReset={() => { setResult(null); setCommand(""); setIsSolved(false); }} solveText={stage === 3 ? "Solve module" : "Solve stage"} isLoading={isLoading} isSolved={isSolved} /><ErrorAlert error={error} />{result && <SolverSection title="Submit"><p className="text-center text-3xl font-bold">{result.weekday}</p></SolverSection>}{command && <TwitchCommandDisplay command={command} />}</SolverLayout>;
}
