import { useState } from "react";
import { solveGreenArrows, type GreenArrowsOutput } from "../../services/greenArrowsService";
import type { BombEntity } from "../../types";
import { ErrorAlert, SolverControls, SolverInstructions, SolverLayout, SolverSection, TwitchCommandDisplay, useSolver } from "../common";

export default function GreenArrowsSolver({ bomb }: { bomb: BombEntity | null | undefined }) {
  const [number, setNumber] = useState("00"), [resetStreak, setResetStreak] = useState(false), [result, setResult] = useState<GreenArrowsOutput | null>(null);
  const { isLoading, error, isSolved, setIsLoading, setError, setIsSolved, clearError, reset: resetSolverState, currentModule, round, markModuleSolved } = useSolver();
  const solve = async () => { if (!round?.id || !bomb?.id || !currentModule?.id) return setError("Missing required information"); clearError(); setIsLoading(true); try { const response = await solveGreenArrows(round.id, bomb.id, currentModule.id, Number(number), resetStreak); setResult(response.output); setResetStreak(false); setIsSolved(response.solved); if (response.solved) markModuleSolved(bomb.id, currentModule.id); } catch (cause) { setError(cause instanceof Error ? cause.message : "Failed to solve Green Arrows"); } finally { setIsLoading(false); } };
  return <SolverLayout><SolverSection title="Current display"><input aria-label="Displayed number" inputMode="numeric" maxLength={2} value={number} onChange={event => { setNumber(event.target.value.replace(/\D/g, "")); setResult(null); }} className="h-12 w-full rounded border bg-background px-3 text-center font-mono text-2xl" /><label className="mt-3 block"><input type="checkbox" checked={resetStreak} onChange={event => setResetStreak(event.target.checked)} /> A strike reset the streak before this display</label></SolverSection><SolverControls onSolve={solve} onReset={() => { setNumber("00"); setResetStreak(false); setResult(null); resetSolverState(); }} isLoading={isLoading} isSolved={isSolved} solveText="Get next press" /><ErrorAlert error={error} />{result && <SolverSection title={`Press ${result.direction}`} className="border-emerald-500/40"><p>Correct streak after this press: {result.streakAfterPress}/7</p></SolverSection>}{result && <TwitchCommandDisplay command={`!number ${result.direction}`} />}<SolverInstructions>After pressing, enter the newly generated number. Check the reset box only after an incorrect in-game press.</SolverInstructions></SolverLayout>;
}
