import { useState } from "react";
import { HIDDEN_COLORS, solveHiddenColors, type HiddenColorsOutput } from "../../services/hiddenColorsService";
import type { BombEntity } from "../../types";
import { ErrorAlert, SolverControls, SolverInstructions, SolverLayout, SolverSection, useSolver } from "../common";

export default function HiddenColorsSolver({ bomb }: { bomb: BombEntity | null | undefined }) {
  const [led, setLed] = useState("red"), [buttons, setButtons] = useState(Array(20).fill("red") as string[]), [result, setResult] = useState<HiddenColorsOutput | null>(null);
  const { isLoading, error, isSolved, setIsLoading, setError, setIsSolved, clearError, reset: resetSolverState, currentModule, round, markModuleSolved } = useSolver();
  const solve = async () => { if (!round?.id || !bomb?.id || !currentModule?.id) return setError("Missing required information"); clearError(); setIsLoading(true); try { const response = await solveHiddenColors(round.id, bomb.id, currentModule.id, led, buttons); setResult(response.output); setIsSolved(response.solved); if (response.solved) markModuleSolved(bomb.id, currentModule.id); } catch (cause) { setError(cause instanceof Error ? cause.message : "Failed to solve Hidden Colors"); } finally { setIsLoading(false); } };
  return <SolverLayout><SolverSection title="Main LED"><select aria-label="LED color" value={led} onChange={event => { setLed(event.target.value); setResult(null); }} className="h-11 w-full rounded border bg-background px-2">{HIDDEN_COLORS.map(color => <option key={color}>{color}</option>)}</select></SolverSection><SolverSection title="Buttons 1–20"><div className="grid grid-cols-4 gap-2">{buttons.map((color,index) => <label key={index} className="text-xs">{index+1}<select aria-label={`Button ${index+1} color`} value={color} onChange={event => { const next=[...buttons]; next[index]=event.target.value; setButtons(next); setResult(null); }} className="block h-9 w-full rounded border bg-background px-1">{HIDDEN_COLORS.map(value => <option key={value}>{value}</option>)}</select></label>)}</div></SolverSection><SolverControls onSolve={solve} onReset={() => { setLed("red"); setButtons(Array(20).fill("red")); setResult(null); resetSolverState(); }} isLoading={isLoading} isSolved={isSolved} /><ErrorAlert error={error} />{result && <SolverSection title="Press sequence" className="border-emerald-500/40"><p>Press green button {result.greenButton} to switch on the LED, then press button {result.correctButton}.</p><p className="text-sm text-muted-foreground">Rule {result.appliedRule}; {Object.entries(result.namedButtons).map(([name,position]) => `${name}=${position}`).join(", ")}</p></SolverSection>}<SolverInstructions>Reveal and record every button color before switching on the LED. Upstream Twitch command grammar was unavailable from the surviving sources, so no command is emitted.</SolverInstructions></SolverLayout>;
}
