import { useCallback, useMemo, useState } from "react";
import { solveHieroglyphics, type HieroglyphicsOutput } from "../../services/hieroglyphicsService";
import { useRoundStore } from "../../store/useRoundStore";
import { ModuleType, type BombEntity } from "../../types";
import { generateTwitchCommand } from "../../utils/twitchCommands";
import { ErrorAlert, SolverControls, SolverInstructions, SolverLayout, SolverSection, TwitchCommandDisplay, useSolver, useSolverModulePersistence } from "../common";

const GLYPHS=["Male","Bull","Urn","Eye of Horus","Ankh","Goose","Lion","Water","Head of Cow","Mosaic","Lasso","Two Reeds","Scales","Bone","Triangle","Horn","Owl"];
const ALIASES=["A","B","C","D","E"];
export default function HieroglyphicsSolver({bomb}:{bomb:BombEntity|null|undefined}){
 const[glyphNames,setGlyphNames]=useState(GLYPHS.slice(0,5)),[rows,setRows]=useState(["","",""]),[sums,setSums]=useState([0,0,0]),[anubisGlyphs,setAnubis]=useState(""),[horusGlyphs,setHorus]=useState("");
 const[result,setResult]=useState<HieroglyphicsOutput|null>(null),[twitchCommand,setTwitchCommand]=useState("");const{isLoading,error,isSolved,setIsLoading,setError,setIsSolved,clearError,reset:resetSolverState,currentModule,round,markModuleSolved}=useSolver();const updateModuleAfterSolve=useRoundStore(s=>s.updateModuleAfterSolve);const state=useMemo(()=>({glyphNames,rows,sums,anubisGlyphs,horusGlyphs,result,twitchCommand}),[glyphNames,rows,sums,anubisGlyphs,horusGlyphs,result,twitchCommand]);
 useSolverModulePersistence<typeof state,HieroglyphicsOutput>({state,onRestoreState:useCallback(s=>{if(s.glyphNames)setGlyphNames(s.glyphNames);if(s.rows)setRows(s.rows);if(s.sums)setSums(s.sums);if(s.anubisGlyphs)setAnubis(s.anubisGlyphs);if(s.horusGlyphs)setHorus(s.horusGlyphs);if(s.result)setResult(s.result);if(s.twitchCommand)setTwitchCommand(s.twitchCommand);},[]),onRestoreSolution:useCallback((solution:HieroglyphicsOutput)=>{setResult(solution);setTwitchCommand(generateTwitchCommand({moduleType:ModuleType.HIEROGLYPHICS,result:solution}));},[]),currentModule,setIsSolved});
 const changed=()=>{setResult(null);setTwitchCommand("");setIsSolved(false);clearError();};
 const solve=async()=>{if(!round?.id||!bomb?.id||!currentModule?.id)return setError("Missing required information");clearError();setIsLoading(true);try{const response=await solveHieroglyphics(round.id,bomb.id,currentModule.id,glyphNames,rows,sums,anubisGlyphs,horusGlyphs);const command=generateTwitchCommand({moduleType:ModuleType.HIEROGLYPHICS,result:response.output});setResult(response.output);setTwitchCommand(command);setIsSolved(response.solved);markModuleSolved(bomb.id,currentModule.id);updateModuleAfterSolve(bomb.id,currentModule.id,{glyphNames,rows,sums,anubisGlyphs,horusGlyphs,result:response.output,twitchCommand:command},response.output,true);}catch(cause){setError(cause instanceof Error?cause.message:"Failed to solve Hieroglyphics");}finally{setIsLoading(false);}};
 const reset=()=>{setGlyphNames(GLYPHS.slice(0,5));setRows(["","",""]);setSums([0,0,0]);setAnubis("");setHorus("");setResult(null);setTwitchCommand("");resetSolverState();};
 return<SolverLayout><SolverSection title="Five small glyphs (display order A–E)"><div className="grid gap-2 sm:grid-cols-2">{glyphNames.map((name,i)=><label key={i}>{ALIASES[i]}<select aria-label={`Glyph ${ALIASES[i]}`}value={name}onChange={e=>{const next=[...glyphNames];next[i]=e.target.value;setGlyphNames(next);changed();}}className="ml-2 h-10 rounded border bg-background px-2">{GLYPHS.map(g=><option key={g}>{g}</option>)}</select></label>)}</div></SolverSection><SolverSection title="Equation rows"><div className="space-y-2">{rows.map((row,i)=><div key={i}className="grid grid-cols-[1fr_7rem] gap-2"><input aria-label={`${i+3}-glyph row`}placeholder={`${i+3} aliases, e.g. ABC`}maxLength={i+3}value={row}onChange={e=>{const next=[...rows];next[i]=e.target.value.toUpperCase();setRows(next);changed();}}className="h-10 rounded border bg-background px-3 uppercase"/><input aria-label={`${i+3}-glyph sum`}type="number"value={sums[i]||""}onChange={e=>{const next=[...sums];next[i]=Number(e.target.value);setSums(next);changed();}}className="h-10 rounded border bg-background px-3"/></div>)}</div></SolverSection><SolverSection title="Large lock glyph aliases"><div className="grid gap-3 sm:grid-cols-2"><label>Anubis (left) pair<input aria-label="Anubis glyphs"maxLength={2}value={anubisGlyphs}onChange={e=>{setAnubis(e.target.value.toUpperCase());changed();}}className="mt-1 h-11 w-full rounded border bg-background px-3 uppercase"/></label><label>Horus (right) pair<input aria-label="Horus glyphs"maxLength={2}value={horusGlyphs}onChange={e=>{setHorus(e.target.value.toUpperCase());changed();}}className="mt-1 h-11 w-full rounded border bg-background px-3 uppercase"/></label></div></SolverSection><SolverControls onSolve={solve}onReset={reset}isLoading={isLoading}isSolved={isSolved}/><ErrorAlert error={error}/>{result&&<SolverSection title="Set locks, then press seal"className="border-emerald-500/40"><p className="text-2xl font-bold">Anubis {result.anubisPosition} · Horus {result.horusPosition}</p><p className="mt-2 text-4xl font-bold">Timer digit {result.timerDigit}</p><p className="mt-2 text-sm">Values: {Object.entries(result.values).map(([a,v])=>`${a}=${v}`).join(", ")}. Priority: {result.priorityGlyph} × {result.priorityOccurrences}.</p></SolverSection>}{twitchCommand&&<TwitchCommandDisplay command={twitchCommand}/>}<SolverInstructions>Alias the top glyphs A–E from left to right, then use those aliases for all rows and locks. The source counts one top-row appearance plus every equation-row and lock appearance of the priority glyph. A wrong seal press strikes without regenerating the module. Hieroglyphics is not a Souvenir candidate.</SolverInstructions></SolverLayout>;
}
