import { useCallback, useMemo, useState } from "react";
import { HORRIBLE_MEMORY_COLORS, solveHorribleMemory, type HorribleMemoryButton, type HorribleMemoryColor, type HorribleMemoryOutput } from "../../services/horribleMemoryService";
import { useRoundStore } from "../../store/useRoundStore";
import { ModuleType, type BombEntity } from "../../types";
import { generateTwitchCommand } from "../../utils/twitchCommands";
import { ErrorAlert, SolverControls, SolverInstructions, SolverLayout, SolverSection, StageIndicator, TwitchCommandDisplay, useSolver, useSolverModulePersistence } from "../common";

const INITIAL: HorribleMemoryButton[] = HORRIBLE_MEMORY_COLORS.map((color, index) => ({ label: index + 1, color }));
export default function HorribleMemorySolver({ bomb }: { bomb: BombEntity | null | undefined }) {
  const [stage, setStage] = useState(1), [display, setDisplay] = useState(1), [buttons, setButtons] = useState<HorribleMemoryButton[]>(INITIAL), [restartAttempt, setRestartAttempt] = useState(true), [result, setResult] = useState<HorribleMemoryOutput | null>(null), [twitchCommand, setTwitchCommand] = useState("");
  const { isLoading, error, isSolved, setIsLoading, setError, setIsSolved, clearError, reset: resetSolverState, currentModule, round, markModuleSolved } = useSolver(); const updateModuleAfterSolve = useRoundStore((state) => state.updateModuleAfterSolve);
  const state = useMemo(() => ({ stage, display, buttons, restartAttempt, result, twitchCommand }), [stage, display, buttons, restartAttempt, result, twitchCommand]);
  useSolverModulePersistence<typeof state, HorribleMemoryOutput>({ state, onRestoreState: useCallback((saved) => { if (saved.stage) setStage(saved.stage); if (saved.display) setDisplay(saved.display); if (saved.buttons) setButtons(saved.buttons); if (saved.restartAttempt !== undefined) setRestartAttempt(saved.restartAttempt); if (saved.result) setResult(saved.result); if (saved.twitchCommand) setTwitchCommand(saved.twitchCommand); }, []), onRestoreSolution: useCallback((solution: HorribleMemoryOutput) => { setResult(solution); setTwitchCommand(generateTwitchCommand({ moduleType: ModuleType.HORRIBLE_MEMORY, result: solution })); }, []), currentModule, setIsSolved });
  const updateButton = (index: number, change: Partial<HorribleMemoryButton>) => { setButtons((old) => old.map((button, i) => i === index ? { ...button, ...change } : button)); clearError(); };
  const solve = async () => { if (!round?.id || !bomb?.id || !currentModule?.id) return setError("Missing required information"); clearError(); setIsLoading(true); try { const response = await solveHorribleMemory(round.id, bomb.id, currentModule.id, stage, display, buttons, restartAttempt); const command = generateTwitchCommand({ moduleType: ModuleType.HORRIBLE_MEMORY, result: response.output }); const nextStage = response.solved ? stage : stage + 1; setResult(response.output); setTwitchCommand(command); setStage(nextStage); setDisplay(1); setButtons(INITIAL); setRestartAttempt(false); setIsSolved(response.solved); if (response.solved) markModuleSolved(bomb.id, currentModule.id); updateModuleAfterSolve(bomb.id, currentModule.id, { stage: nextStage, display: 1, buttons: INITIAL, restartAttempt: false, result: response.output, twitchCommand: command }, response.output, response.solved); } catch (cause) { setError(cause instanceof Error ? cause.message : "Failed to solve Horrible Memory"); } finally { setIsLoading(false); } };
  const reset = () => { setStage(1); setDisplay(1); setButtons(INITIAL); setRestartAttempt(true); setResult(null); setTwitchCommand(""); resetSolverState(); };
  return <SolverLayout><StageIndicator total={5} current={stage} completedThrough={stage - 1}/><SolverSection title={`Stage ${stage}`} description="Enter the display and all six buttons from left to right before pressing the answer."><label className="space-y-1"><span className="text-sm font-medium">Displayed number</span><select aria-label="Displayed number" value={display} onChange={(event) => setDisplay(Number(event.target.value))} className="w-full rounded-md border border-input bg-background p-2">{[1,2,3,4,5,6].map((value) => <option key={value}>{value}</option>)}</select></label><div className="mt-3 grid gap-2 sm:grid-cols-2">{buttons.map((button, index) => <div key={index} className="grid grid-cols-[auto_1fr_1fr] items-center gap-2"><span className="text-sm">Pos. {index + 1}</span><select aria-label={`Label at position ${index + 1}`} value={button.label} onChange={(event) => updateButton(index, { label: Number(event.target.value) })} className="rounded-md border border-input bg-background p-2">{[1,2,3,4,5,6].map((value) => <option key={value}>{value}</option>)}</select><select aria-label={`Color at position ${index + 1}`} value={button.color} onChange={(event) => updateButton(index, { color: event.target.value as HorribleMemoryColor })} className="rounded-md border border-input bg-background p-2">{HORRIBLE_MEMORY_COLORS.map((color) => <option key={color}>{color.toLowerCase()}</option>)}</select></div>)}</div></SolverSection><SolverControls onSolve={solve} onReset={reset} isLoading={isLoading} isSolved={isSolved} solveText={`Solve stage ${stage}`}/><ErrorAlert error={error}/>{result && <SolverSection title={`Stage ${result.stage} answer`} className="border-emerald-500/40"><p className="text-2xl font-bold">Press position {result.position}</p><p>{result.color} button labeled {result.label}</p></SolverSection>}{twitchCommand && <TwitchCommandDisplay command={twitchCommand}/>}<SolverInstructions>After a correct press, enter the newly generated next stage. If the module strikes, use Reset; the next stage-1 submission replaces the entire failed attempt and its Souvenir facts.</SolverInstructions></SolverLayout>;
}
