import { useState } from "react";
import { solveInsaneTalk, type InsaneTalkOutput } from "../../services/insaneTalkService";
import { ModuleType, type BombEntity } from "../../types";
import { generateTwitchCommand } from "../../utils/twitchCommands";
import { ErrorAlert, SolverControls, SolverLayout, SolverSection, TwitchCommandDisplay, useSolver } from "../common";
export default function InsaneTalkSolver({ bomb }: { bomb: BombEntity | null | undefined }) {
  const [phrase, setPhrase] = useState(""), [labels, setLabels] = useState([0, 1, 2, 3]), [result, setResult] = useState<InsaneTalkOutput | null>(null), [command, setCommand] = useState("");
  const { isLoading, error, isSolved, setIsLoading, setError, setIsSolved, clearError, currentModule, round, markModuleSolved } = useSolver();
  const solve = async () => { if (!round?.id || !bomb?.id || !currentModule?.id) return setError("Missing required information"); setIsLoading(true); clearError(); try { const response = await solveInsaneTalk(round.id, bomb.id, currentModule.id, { phrase, buttonLabels: labels }); setResult(response.output); setCommand(generateTwitchCommand({ moduleType: ModuleType.INSANE_TALK, result: response.output })); setIsSolved(response.solved); if (response.solved) markModuleSolved(bomb.id, currentModule.id); } catch (cause) { setError(cause instanceof Error ? cause.message : "Failed to solve Insane Talk"); } finally { setIsLoading(false); } };
  return <SolverLayout><SolverSection title="Display"><label>Phrase (include surrounding quotes if shown)<textarea value={phrase} onChange={(e) => setPhrase(e.target.value)} rows={4} className="mt-1 block w-full rounded-md border bg-background p-3" /></label><div className="mt-3 grid grid-cols-4 gap-2">{labels.map((value, i) => <label key={i} className="text-center text-xs">Button {i + 1}<input type="number" min={0} max={9} value={value} onChange={(e) => setLabels(labels.map((x, j) => j === i ? Number(e.target.value) : x))} className="mt-1 block h-10 w-full rounded-md border bg-background px-2 text-center" /></label>)}</div></SolverSection><SolverControls onSolve={solve} onReset={() => { setResult(null); setCommand(""); setIsSolved(false); }} isLoading={isLoading} isSolved={isSolved} /><ErrorAlert error={error} />{result && <SolverSection title="Press labels"><p className="text-center text-3xl font-bold">{result.pressLabels.join(" ")}</p><p className="text-center text-xs text-muted-foreground">Phrase code: {result.phraseCode}{result.quoted ? " (reversed)" : ""}</p></SolverSection>}{command && <TwitchCommandDisplay command={command} />}</SolverLayout>;
}
