import{useCallback,useMemo,useState}from"react";
import{solveKudosudoku,type KudosudokuOutput}from"../../services/kudosudokuService";
import{useRoundStore}from"../../store/useRoundStore";
import{ModuleType,type BombEntity}from"../../types";
import{generateTwitchCommand}from"../../utils/twitchCommands";
import{ErrorAlert,SolverControls,SolverInstructions,SolverLayout,SolverSection,TwitchCommandDisplay,useSolver,useSolverModulePersistence}from"../common";

const CODINGS=["LETTERS","DIGITS","MORSE_CODE","SEMAPHORES","BRAILLE","MARITIME_FLAGS","TAP_CODE","BINARY","SIMON_SAMPLES","ASTROLOGY","SNOOKER","ARROWS","CARD_SUITS","MAHJONG","ZONI","CHESS_PIECES"];
const FIXED:Record<string,string[]>={DIGITS:["1","2","3","4"],SIMON_SAMPLES:["Kick","Snare","Hi-hat","Open hi-hat"],ASTROLOGY:["Fire","Water","Earth","Air"],SNOOKER:["Red","Yellow","Green","Brown"],ARROWS:["Down","Left","Up","Right"],CARD_SUITS:["Spades","Hearts","Clubs","Diamonds"],MAHJONG:["Plum","Orchid","Chrysanthemum","Bamboo"],CHESS_PIECES:["Rook","Knight","Bishop","Queen"]};
const label=(coding:string)=>coding.toLowerCase().replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
const coord=(index:number)=>String.fromCharCode(65+index%4)+String(1+Math.floor(index/4));
function namesFromSerial(serial:string|undefined){const text=(serial??"").toUpperCase(),letter=text.match(/[A-Z]/)?.[0],digit=text.match(/\d/)?.[0];if(!letter||digit===undefined)return[];const distance=digit==="0"?10:Number(digit);return Array.from({length:4},(_,i)=>String.fromCharCode((letter.charCodeAt(0)-65+i*distance)%26+65));}
function reference(coding:string,names:string[]){if(FIXED[coding])return FIXED[coding];if(coding==="BINARY")return names.map(name=>(name.charCodeAt(0)-64).toString(2).padStart(5,"0"));if(coding==="LETTERS")return names;return names.map(name=>`${label(coding)} ${name}`);}

export default function KudosudokuSolver({bomb}:{bomb:BombEntity|null|undefined}){
 const[grid,setGrid]=useState<number[]>(Array(16).fill(0)),[coordinate,setCoordinate]=useState(""),[coding,setCoding]=useState(""),[completed,setCompleted]=useState<string[]>([]),[result,setResult]=useState<KudosudokuOutput|null>(null),[twitchCommand,setTwitchCommand]=useState("");
 const{isLoading,error,isSolved,setIsLoading,setError,setIsSolved,clearError,reset:resetSolverState,currentModule,round,markModuleSolved}=useSolver();const updateModuleAfterSolve=useRoundStore(s=>s.updateModuleAfterSolve);
 const state=useMemo(()=>({grid,coordinate,coding,completed,result,twitchCommand}),[grid,coordinate,coding,completed,result,twitchCommand]);
 useSolverModulePersistence<typeof state,KudosudokuOutput>({state,onRestoreState:useCallback(s=>{if(Array.isArray(s.grid)&&s.grid.length===16)setGrid(s.grid);if(s.coordinate)setCoordinate(s.coordinate);if(s.coding)setCoding(s.coding);if(Array.isArray(s.completed))setCompleted(s.completed);if(s.result)setResult(s.result);if(s.twitchCommand)setTwitchCommand(s.twitchCommand);},[]),onRestoreSolution:useCallback((solution:KudosudokuOutput)=>{setResult(solution);setTwitchCommand(generateTwitchCommand({moduleType:ModuleType.KUDOSUDOKU,result:solution}));},[]),currentModule,setIsSolved});
 const numberNames=result?.numberNames??namesFromSerial(bomb?.serialNumber),gridSolved=Boolean(result?.solution?.length===16),initialHidden=grid.map((value,index)=>value===0?coord(index):null).filter((value):value is string=>Boolean(value)),remaining=initialHidden.filter(value=>!completed.includes(value));
 const updateCell=(index:number,value:number)=>{const next=[...grid];next[index]=value;setGrid(next);setResult(null);setCompleted([]);setCoordinate("");setCoding("");setTwitchCommand("");setIsSolved(false);clearError();};
 const solve=async()=>{if(!round?.id||!bomb?.id||!currentModule?.id)return setError("Missing required information");if(gridSolved&&(!coordinate||!coding))return setError("Select the newly revealed square and its coding");clearError();setIsLoading(true);try{const response=await solveKudosudoku(round.id,bomb.id,currentModule.id,grid,gridSolved?coordinate:null,gridSolved?coding:null);const nextCompleted=response.output.coordinate?[...new Set([...completed,response.output.coordinate])]:grid.map((value,index)=>value?coord(index):null).filter((value):value is string=>Boolean(value));const command=generateTwitchCommand({moduleType:ModuleType.KUDOSUDOKU,result:response.output});setCompleted(nextCompleted);setResult(response.output);setTwitchCommand(command);setIsSolved(response.solved);if(response.solved)markModuleSolved(bomb.id,currentModule.id);updateModuleAfterSolve(bomb.id,currentModule.id,{grid,coordinate,coding,completed:nextCompleted,result:response.output,twitchCommand:command},response.output,response.solved);}catch(cause){setError(cause instanceof Error?cause.message:"Failed to solve Kudosudoku");}finally{setIsLoading(false);}};
 const reset=()=>{setGrid(Array(16).fill(0));setCoordinate("");setCoding("");setCompleted([]);setResult(null);setTwitchCommand("");resetSolverState();};
 return <SolverLayout>
  <SolverSection title="Decoded givens"><div className="grid grid-cols-4 gap-2">{grid.map((value,index)=><label key={index} className="text-center text-xs">{coord(index)}<select aria-label={coord(index)} value={value} onChange={e=>updateCell(index,Number(e.target.value))} disabled={gridSolved} className="mt-1 h-10 w-full rounded border bg-background text-center"><option value={0}>—</option>{[1,2,3,4].map(n=><option key={n}>{n}</option>)}</select></label>)}</div></SolverSection>
  <SolverSection title="Code reference"><p className="mb-2 text-sm">Number names: {numberNames.map((name,index)=>`${index+1}=${name}`).join(", ")||"enter a serial number"}</p><div className="max-h-64 overflow-auto text-xs">{CODINGS.map(name=><div key={name} className="grid grid-cols-[9rem_1fr] gap-2 border-t py-1"><span>{label(name)}</span><span>{reference(name,numberNames).map((value,index)=>`${index+1}: ${value}`).join(" · ")}</span></div>)}</div></SolverSection>
  {gridSolved&&remaining.length>0&&<SolverSection title="Translate a revealed square"><p className="mb-2 text-sm">Open one unfinished square first{coordinate&&<>: <code>!number {coordinate}</code></>}.</p><div className="grid gap-3 sm:grid-cols-2"><label>Square<select aria-label="Revealed square" value={coordinate} onChange={e=>{setCoordinate(e.target.value);setCoding("");setTwitchCommand("");clearError();}} className="mt-1 h-11 w-full rounded border bg-background px-3"><option value="">Select…</option>{remaining.map(value=><option key={value}>{value}</option>)}</select></label><label>Coding<select aria-label="Revealed coding" value={coding} onChange={e=>{setCoding(e.target.value);setTwitchCommand("");clearError();}} className="mt-1 h-11 w-full rounded border bg-background px-3"><option value="">Select…</option>{CODINGS.map(value=><option key={value} value={value}>{label(value)}</option>)}</select></label></div></SolverSection>}
  <SolverControls onSolve={solve} onReset={reset} isLoading={isLoading} isSolved={isSolved}/><ErrorAlert error={error}/>
  {result&&<SolverSection title={result.coordinate?`Submit ${result.coordinate}`:"Solved grid"} className="border-emerald-500/40"><div className="grid grid-cols-4 gap-1 font-mono text-xl">{result.solution.map((value,index)=><span key={index} className="rounded border p-2 text-center">{value}</span>)}</div>{result.submission&&<p className="mt-3 text-lg"><strong>{result.submission}</strong> ({result.coding&&label(result.coding)}, value {result.value})</p>}<p className="mt-2 text-sm">{result.remaining} unfinished square{result.remaining===1?"":"s"} remain.</p></SolverSection>}
  {twitchCommand&&<TwitchCommandDisplay command={twitchCommand}/>}<SolverInstructions>Decode every initially visible cell to 1–4 and use 0/blank elsewhere. After the grid is solved, open an unfinished coordinate, report the revealed coding, and submit the returned value. A strike keeps the Sudoku and solved cells but reshuffles coding types among unfinished squares. Souvenir asks which coordinates were and were not initially pre-filled.</SolverInstructions>
 </SolverLayout>;
}
