import { useCallback, useMemo, useState } from "react";
import { solveMicroModules, type MicroIndicator, type MicroModulesInput, type MicroModulesOutput } from "../../services/microModulesService";
import { useRoundStore } from "../../store/useRoundStore";
import { ModuleType, type BombEntity } from "../../types";
import { generateTwitchCommand } from "../../utils/twitchCommands";
import { ErrorAlert, SolverControls, SolverInstructions, SolverLayout, SolverSection, TwitchCommandDisplay, useSolver, useSolverModulePersistence } from "../common";

const batteryColors = ["RED", "ORANGE", "YELLOW", "GREEN", "BLUE", "PURPLE", "PINK", "BLACK"];
const wireColors = ["RED", "YELLOW", "GREEN", "BLUE", "WHITE", "BLACK"];
const arrows = ["LEFT", "RIGHT", "REVERSE", "CLOCKWISE", "SWAP", "DIAGONAL_TL", "DIAGONAL_TR", "DIAGONAL_BL", "DIAGONAL_BR"];
const renderers = ["BOMB", "EXPL", "MINI", "NULL", "BOB", "MSA", "SIG", "TRN", "DVID", "Parallel", "StereoRCA", "RJ45", "WireCount", "AllWires", "WireRenderer", "CurrentWire"];

export default function MicroModulesSolver({ bomb }: { bomb: BombEntity | null | undefined }) {
  const [ids, setIds] = useState([1, 2, 3, 4]), [microSerial, setMicroSerial] = useState("ABCDE0"), [indicators, setIndicators] = useState<MicroIndicator[]>([{ label:"INDC", lit:false }, { label:"EXPL", lit:false }, { label:"BOOM", lit:false }]), [batteryColor, setBatteryColor] = useState("BLACK");
  const [keypadArrows, setKeypadArrows] = useState(["RIGHT", "LEFT", "RIGHT", "LEFT"]), [rendererName, setRendererName] = useState("BOMB"), [wires, setWires] = useState(["RED", "YELLOW", "GREEN", "BLUE", "WHITE", "BLACK"]);
  const [morseDigits, setMorseDigits] = useState("0000"), [mathLetters, setMathLetters] = useState("ABC"), [operators, setOperators] = useState(["+", "+"]), [result, setResult] = useState<MicroModulesOutput | null>(null), [twitchCommand, setTwitchCommand] = useState("");
  const { isLoading, error, isSolved, setIsLoading, setError, setIsSolved, clearError, reset: resetSolverState, currentModule, round, markModuleSolved } = useSolver();
  const updateModuleAfterSolve = useRoundStore(state => state.updateModuleAfterSolve);
  const state = useMemo(() => ({ ids, microSerial, indicators, batteryColor, keypadArrows, rendererName, wires, morseDigits, mathLetters, operators, result, twitchCommand }), [ids, microSerial, indicators, batteryColor, keypadArrows, rendererName, wires, morseDigits, mathLetters, operators, result, twitchCommand]);
  useSolverModulePersistence<typeof state, MicroModulesOutput>({
    state,
    onRestoreState: useCallback(saved => { if (saved.ids) setIds(saved.ids); if (saved.microSerial) setMicroSerial(saved.microSerial); if (saved.indicators) setIndicators(saved.indicators); if (saved.batteryColor) setBatteryColor(saved.batteryColor); if (saved.keypadArrows) setKeypadArrows(saved.keypadArrows); if (saved.rendererName) setRendererName(saved.rendererName); if (saved.wires) setWires(saved.wires); if (saved.morseDigits) setMorseDigits(saved.morseDigits); if (saved.mathLetters) setMathLetters(saved.mathLetters); if (saved.operators) setOperators(saved.operators); if (saved.result) setResult(saved.result); if (saved.twitchCommand) setTwitchCommand(saved.twitchCommand); }, []),
    onRestoreSolution: useCallback((solution: MicroModulesOutput) => { setResult(solution); setTwitchCommand(generateTwitchCommand({ moduleType: ModuleType.MICRO_MODULES, result: solution })); }, []), currentModule, setIsSolved,
  });
  const changed = () => { setResult(null); setTwitchCommand(""); setIsSolved(false); clearError(); };
  const input = (): MicroModulesInput => ({ directionalKeypadsId:ids[0], codeMorseId:ids[1], scriptWiresId:ids[2], mathCodeId:ids[3], microSerial, microIndicators:indicators, microBatteryColor:batteryColor, arrows:keypadArrows, rendererName, wireColors:wires, receivedMorseDigits:morseDigits, mathLetters, firstOperator:operators[0], secondOperator:operators[1] });
  const solve = async () => {
    if (!round?.id || !bomb?.id || !currentModule?.id) return setError("Missing required information");
    clearError(); setIsLoading(true);
    try {
      const response = await solveMicroModules(round.id, bomb.id, currentModule.id, input());
      const command = generateTwitchCommand({ moduleType: ModuleType.MICRO_MODULES, result: response.output });
      setResult(response.output); setTwitchCommand(command); setIsSolved(response.solved); if (response.solved) markModuleSolved(bomb.id, currentModule.id);
      updateModuleAfterSolve(bomb.id, currentModule.id, { ...state, result:response.output, twitchCommand:command }, response.output, response.solved);
    } catch (cause) { setError(cause instanceof Error ? cause.message : "Failed to solve Micro-Modules"); } finally { setIsLoading(false); }
  };
  const reset = () => { setIds([1,2,3,4]); setMicroSerial("ABCDE0"); setIndicators([{label:"INDC",lit:false},{label:"EXPL",lit:false},{label:"BOOM",lit:false}]); setBatteryColor("BLACK"); setKeypadArrows(["RIGHT","LEFT","RIGHT","LEFT"]); setRendererName("BOMB"); setWires(["RED","YELLOW","GREEN","BLUE","WHITE","BLACK"]); setMorseDigits("0000"); setMathLetters("ABC"); setOperators(["+","+"]); setResult(null); setTwitchCommand(""); resetSolverState(); };
  const selectClass = "mt-1 h-10 w-full rounded border bg-background px-2";
  return <SolverLayout>
    <SolverSection title="Micro-bomb and module IDs"><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{["Directional Keypads","Code Morse","Script Wires","The Math Code"].map((name,index)=><label key={name}>{name}<select aria-label={`${name} ID`} value={ids[index]} onChange={event=>{setIds(current=>current.map((value,i)=>i===index?Number(event.target.value):value));changed();}} className={selectClass}>{[1,2,3,4].map(value=><option key={value}>{value}</option>)}</select></label>)}</div><div className="mt-3 grid gap-3 sm:grid-cols-2"><label>Micro serial<input value={microSerial} onChange={event=>{setMicroSerial(event.target.value.toUpperCase().slice(0,6));changed();}} className={selectClass}/></label><label>Micro battery<select value={batteryColor} onChange={event=>{setBatteryColor(event.target.value);changed();}} className={selectClass}>{batteryColors.map(value=><option key={value}>{value}</option>)}</select></label></div><div className="mt-3 grid grid-cols-3 gap-3">{indicators.map((indicator,index)=><div key={index}><input aria-label={`Micro indicator ${index+1}`} value={indicator.label} onChange={event=>{setIndicators(current=>current.map((value,i)=>i===index?{...value,label:event.target.value.toUpperCase().slice(0,4)}:value));changed();}} className={selectClass}/><label className="mt-1 flex gap-2"><input type="checkbox" checked={indicator.lit} onChange={event=>{setIndicators(current=>current.map((value,i)=>i===index?{...value,lit:event.target.checked}:value));changed();}}/>Lit</label></div>)}</div></SolverSection>
    <SolverSection title="Directional Keypads"><div className="grid grid-cols-2 gap-3">{keypadArrows.map((value,index)=><label key={index}>Position {index+1}<select value={value} onChange={event=>{setKeypadArrows(current=>current.map((item,i)=>i===index?event.target.value:item));changed();}} className={selectClass}>{arrows.map(arrow=><option key={arrow}>{arrow}</option>)}</select></label>)}</div></SolverSection>
    <SolverSection title="Script Wires"><label>MeshRenderer name<select value={rendererName} onChange={event=>{setRendererName(event.target.value);changed();}} className={selectClass}>{renderers.map(value=><option key={value}>{value}</option>)}</select></label><div className="mt-3 grid grid-cols-3 gap-3 sm:grid-cols-6">{wires.map((value,index)=><label key={index}>Wire {index+1}<select value={value} onChange={event=>{setWires(current=>current.map((item,i)=>i===index?event.target.value:item));changed();}} className={selectClass}>{wireColors.map(color=><option key={color}>{color}</option>)}</select></label>)}</div></SolverSection>
    <SolverSection title="Code Morse and The Math Code"><div className="grid gap-3 sm:grid-cols-2"><label>Received Morse digits<input value={morseDigits} onChange={event=>{setMorseDigits(event.target.value.replace(/\D/g,"").slice(0,4));changed();}} className={selectClass}/></label><label>Math letters<input value={mathLetters} onChange={event=>{setMathLetters(event.target.value.toUpperCase().replace(/[^A-Z]/g,"").slice(0,3));changed();}} className={selectClass}/></label></div><div className="mt-3 grid grid-cols-2 gap-3">{operators.map((value,index)=><label key={index}>Operator {index+1}<select value={value} onChange={event=>{setOperators(current=>current.map((item,i)=>i===index?event.target.value:item));changed();}} className={selectClass}>{["+","-","*","/"].map(operator=><option key={operator}>{operator}</option>)}</select></label>)}</div></SolverSection>
    <SolverControls onSolve={solve} onReset={reset} isLoading={isLoading} isSolved={isSolved} solveText="Solve micro-bomb"/><ErrorAlert error={error}/>
    {result&&<SolverSection title="Solutions" className="border-emerald-500/40"><p className="font-semibold">Order: {result.anyOrder?"Any order (safe order shown)":result.solveOrder.join(" → ")}</p><p className="mt-2">Cut wires: {result.cutWires.join(", ")} · Press keypad: {result.keypadPosition}</p><p>Code Morse: {result.morseCode} · Math Code: {result.mathCode}</p></SolverSection>}
    {twitchCommand&&<TwitchCommandDisplay command={twitchCommand}/>}<SolverInstructions>Positions 1–4 are top-left, top-right, bottom-left, bottom-right. Decode the four received Morse digits before solving. The generated Twitch sequence solves every micro-module in a valid order and submits the parent module. Micro-Modules is not a Souvenir candidate.</SolverInstructions>
  </SolverLayout>;
}
