import { useCallback, useMemo, useState } from "react";
import { MODULE_HOMEWORK_SUBJECTS, solveModuleHomework, type ModuleHomeworkOutput } from "../../services/moduleHomeworkService";
import { useRoundStore } from "../../store/useRoundStore";
import { ModuleType, type BombEntity } from "../../types";
import { generateTwitchCommand } from "../../utils/twitchCommands";
import { ErrorAlert, SolverControls, SolverInstructions, SolverLayout, SolverSection, TwitchCommandDisplay, useSolver, useSolverModulePersistence } from "../common";

export default function ModuleHomeworkSolver({ bomb }: { bomb: BombEntity | null | undefined }) {
  const [subject, setSubject] = useState<string>(MODULE_HOMEWORK_SUBJECTS[0]); const [result, setResult] = useState<ModuleHomeworkOutput | null>(null); const [twitchCommand, setTwitchCommand] = useState("");
  const { isLoading, error, isSolved, setIsLoading, setError, setIsSolved, clearError, reset: resetSolverState, currentModule, round, markModuleSolved } = useSolver(); const updateModuleAfterSolve = useRoundStore((state) => state.updateModuleAfterSolve);
  const state = useMemo(() => ({ subject, result, twitchCommand }), [subject, result, twitchCommand]);
  useSolverModulePersistence<typeof state, ModuleHomeworkOutput>({ state, onRestoreState: useCallback((saved) => { if (saved.subject) setSubject(saved.subject); if (saved.result) setResult(saved.result); if (saved.twitchCommand) setTwitchCommand(saved.twitchCommand); }, []), onRestoreSolution: useCallback((solution: ModuleHomeworkOutput) => { setResult(solution); setTwitchCommand(generateTwitchCommand({ moduleType: ModuleType.MODULE_HOMEWORK, result: solution })); }, []), currentModule, setIsSolved });
  const solve = async () => { if (!round?.id || !bomb?.id || !currentModule?.id) return setError("Missing required information"); clearError(); setIsLoading(true); try { const response = await solveModuleHomework(round.id, bomb.id, currentModule.id, subject); const command = generateTwitchCommand({ moduleType: ModuleType.MODULE_HOMEWORK, result: response.output }); setResult(response.output); setTwitchCommand(command); setIsSolved(response.solved); if (response.solved) markModuleSolved(bomb.id, currentModule.id); updateModuleAfterSolve(bomb.id, currentModule.id, { subject, result: response.output, twitchCommand: command }, response.output, response.solved); } catch (cause) { setError(cause instanceof Error ? cause.message : "Failed to solve Module Homework"); } finally { setIsLoading(false); } };
  const reset = () => { setSubject(MODULE_HOMEWORK_SUBJECTS[0]); setResult(null); setTwitchCommand(""); resetSolverState(); };
  return <SolverLayout><SolverSection title="Question subject" description="Start the class with the pencil, then select the module named by the displayed question."><select aria-label="Homework subject" value={subject} onChange={(event) => { setSubject(event.target.value); setResult(null); setTwitchCommand(""); clearError(); }} disabled={isLoading || isSolved} className="w-full rounded-md border border-input bg-background p-2">{MODULE_HOMEWORK_SUBJECTS.map((name) => <option key={name}>{name}</option>)}</select></SolverSection><SolverControls onSolve={solve} onReset={reset} isLoading={isLoading} isSolved={isSolved} solveText="Answer homework"/><ErrorAlert error={error}/>{result && <SolverSection title="Answer" className="border-emerald-500/40"><p className="text-2xl font-bold">Press button {result.button}</p><p>{result.subject}: {result.answer} is base answer {result.baseAnswer}.</p><p>Base number {result.baseNumber} → {result.school}.</p></SolverSection>}{twitchCommand && <TwitchCommandDisplay command={twitchCommand}/>}<SolverInstructions>The command starts the one-minute lesson and submits the shifted answer. A wrong answer generates a new random question, so select the newly displayed subject before retrying.</SolverInstructions></SolverLayout>;
}
