import { ModuleType } from "../../types";

export interface CardReference {
  moduleName: string;
  text: string;
  moduleType?: ModuleType;
}

// https://ktane.timwi.de/HTML/Modules%20Against%20Humanity%20card%20reference%20(SL7205,%20Lebossle).html
export const CARD_REFERENCES: CardReference[] = [
  { moduleName: "HTTP Response", text: "404. The bomb not found." },
  { moduleName: "Combination Lock", text: "Are you sure this is the combination you need?", moduleType: ModuleType.COMBINATION_LOCK },
  { moduleName: "Backgrounds", text: "Are you sure you want that background for your photo?" },
  { moduleName: "Orientation Cube", text: "Bad luck with your crush? Maybe it’s just their sexual orientation.", moduleType: ModuleType.ORIENTATION_CUBE },
  { moduleName: "Probing", text: "Bad news. You’re actually being probed by aliens.", moduleType: ModuleType.PROBING },
  { moduleName: "Wire Placement", text: "Be careful where you place those wires!", moduleType: ModuleType.WIRE_PLACEMENT },
  { moduleName: "Adjacent Letters", text: "Bomb exploded. I was adjacent to it.", moduleType: ModuleType.ADJACENT_LETTERS },
  { moduleName: "Connection Check", text: "Bomb exploded due to bad wifi connection.", moduleType: ModuleType.CONNECTION_CHECK },
  { moduleName: "Cheap Checkout", text: "Check out this bomb sale! It’s so cheap!", moduleType: ModuleType.CHEAP_CHECKOUT },
  { moduleName: "Symbolic Coordinates", text: "Coordination does not exist, it’s only symbolic." },
  { moduleName: "Wires", text: "Cut all the wires!", moduleType: ModuleType.WIRES },
  { moduleName: "Complicated Wires", text: "Cut all the wires! It’s not that complicated after all.", moduleType: ModuleType.COMPLICATED_WIRES },
  { moduleName: "Light Cycle", text: "Dark in the room? Just cycle through the lights.", moduleType: ModuleType.LIGHT_CYCLE },
  { moduleName: "The Moon", text: "Darkness all around, not even the moon is shining." },
  { moduleName: "Emoji Math", text: "Did you know your texts can include words, and not just emojis?", moduleType: ModuleType.EMOJI_MATH },
  { moduleName: "Logic", text: "Do you have at least a pinch of logic in that head of yours?", moduleType: ModuleType.LOGIC },
  { moduleName: "English Test", text: "Do you know the difference between your crap and you’re crap?", moduleType: ModuleType.ENGLISH_TEST },
  { moduleName: "Resistors", text: "Don’t resist the temptation. Just do it.", moduleType: ModuleType.RESISTORS },
  { moduleName: "Third Base", text: "Don’t tell me you’re already in third base with this bomb?", moduleType: ModuleType.THIRD_BASE },
  { moduleName: "European Travel", text: "Europe is a great destination for travels." },
  { moduleName: "Who’s That Monsplode?", text: "Fighting Monsplodes? Identify them first." },
  { moduleName: "Laundry", text: "Friends are coming over. Quick, hide all your dirty laundry!", moduleType: ModuleType.LAUNDRY },
  { moduleName: "Creation", text: "God created the world and you blew it up. Shame on you.", moduleType: ModuleType.CREATION },
  { moduleName: "Rotary Phone", text: "Here, phone a friend for help. Old school style." },
  { moduleName: "Two Bits", text: "Here’s my two bits of information: you’re gonna explode.", moduleType: ModuleType.TWO_BITS },
  { moduleName: "Maze", text: "I know you feel lost. Sadly, this is not a maze so there’s no way out.", moduleType: ModuleType.MAZES },
  { moduleName: "Answering Questions", text: "I know you hate answering questions, but we do have to test you." },
  { moduleName: "Ice Cream", text: "I scream, you scream, but only I love it.", moduleType: ModuleType.ICE_CREAM },
  { moduleName: "Game of Life Simple", text: "I want to play a game. A game of life and death." },
  { moduleName: "Chess", text: "I would play even Billy the Puppet if that game was chess.", moduleType: ModuleType.CHESS },
  { moduleName: "Follow the Leader", text: "If this bomb explodes, you’re following the wrong political leader.", moduleType: ModuleType.FOLLOW_THE_LEADER },
  { moduleName: "Murder", text: "If this doesn’t get you murdered, I don’t know what will.", moduleType: ModuleType.MURDER },
  { moduleName: "Perspective Pegs", text: "If you can’t do it, try to look from a different perspective.", moduleType: ModuleType.PERSPECTIVE_PEGS },
  { moduleName: "Plumbing", text: "If you don’t find a way out, try crawling through pipes.", moduleType: ModuleType.PLUMBING },
  { moduleName: "Hunting", text: "If you explode, I’m gonna hunt you down." },
  { moduleName: "Keypad", text: "If you recognize any of these symbols, you’re a smart fella.", moduleType: ModuleType.KEYPADS },
  { moduleName: "Morse Code", text: "If you’re bad with words, try Morse code instead.", moduleType: ModuleType.MORSE_CODE },
  { moduleName: "Morsematics", text: "If you’re bad with words, try Morsematics code instead.", moduleType: ModuleType.MORSEMATICS },
  { moduleName: "Tetris", text: "If you’re tired of bombs, you could always play Tetris instead." },
  { moduleName: "Colored Squares", text: "It’s cool to be square but only if your colored.", moduleType: ModuleType.COLORED_SQUARES },
  { moduleName: "The Sun", text: "It’s so bright! Who turned the sun on?" },
  { moduleName: "Switches", text: "It’s useless. Switch to another bomb.", moduleType: ModuleType.SWITCHES },
  { moduleName: "Semaphore", text: "Just as I expected, you’re waving a white flag already.", moduleType: ModuleType.SEMAPHORE },
  { moduleName: "Listening", text: "Just got a strike. You need to listen to your experts better.", moduleType: ModuleType.LISTENING },
  { moduleName: "Turn The Key", text: "Just turn the key and leave the room.", moduleType: ModuleType.TURN_THE_KEY },
  { moduleName: "Turn The Keys", text: "Just turn the keys and leave the room.", moduleType: ModuleType.TURN_THE_KEYS },
  { moduleName: "Number Pad", text: "Keypad here, keypad there. I want a keypad with numbers!", moduleType: ModuleType.NUMBER_PAD },
  { moduleName: "Colored Switches", text: "Let’s switch on these colours." },
  { moduleName: "Game of Life Cruel", text: "Life is cruel. So are games." },
  { moduleName: "Lights Out", text: "Lights are out. Bomb’s unavailable for 10 seconds." },
  { moduleName: "Bitmaps", text: "Lost in this bomb? Here’s a bit of a map.", moduleType: ModuleType.BITMAPS },
  { moduleName: "Tic Tac Toe", text: "Lots of love, XOXO, The Bomb.", moduleType: ModuleType.TIC_TAC_TOE },
  { moduleName: "Math", text: "Math is hard." },
  { moduleName: "Motion Sense", text: "Moves like Jagger? Not with that motion sense of yours." },
  { moduleName: "Piano Keys", text: "Musical instruments? I recommend trying piano.", moduleType: ModuleType.PIANO_KEYS },
  { moduleName: "Alphabet", text: "Never try tongue twisters before you learn alphabet.", moduleType: ModuleType.ALPHABET },
  { moduleName: "Foreign Exchange Rates", text: "No currency exchange point? You should’ve taken your card.", moduleType: ModuleType.FOREIGN_EXCHANGE_RATES },
  { moduleName: "Astrology", text: "No success? I guess your zodiac was under the wrong planet’s influence.", moduleType: ModuleType.ASTROLOGY },
  { moduleName: "Memory", text: "Nope, that doesn’t work. Try memorizing the manual next time.", moduleType: ModuleType.MEMORY },
  { moduleName: "Complicated Buttons", text: "Pressing buttons should be easy, not complicated.", moduleType: ModuleType.COMPLICATED_BUTTONS },
  { moduleName: "Broken Buttons", text: "Pressing these buttons is useless. They’re broken.", moduleType: ModuleType.BROKEN_BUTTONS },
  { moduleName: "The Button", text: "Push the button. Galvanize.", moduleType: ModuleType.BUTTON },
  { moduleName: "Square Button", text: "Push the square button. Galvanize.", moduleType: ModuleType.SQUARE_BUTTON },
  { moduleName: "The iPhone", text: "Put down your iPhone and solve this bomb!" },
  { moduleName: "Filibuster", text: "Remember the title and just keep talking." },
  { moduleName: "Simon Screams", text: "Simon screams at your incompetence.", moduleType: ModuleType.SIMON_SCREAMS },
  { moduleName: "Hexamaze", text: "Someone must have put a-maze-ing hex on you.", moduleType: ModuleType.HEXAMAZE },
  { moduleName: "The Stopwatch", text: "Stop the watch! Hammer time!" },
  { moduleName: "Venting Gas", text: "Stop venting your emotions. Vent gas instead.", moduleType: ModuleType.VENTING_GAS },
  { moduleName: "The Clock", text: "Tick tock, start the bomb clock.", moduleType: ModuleType.THE_CLOCK },
  { moduleName: "Colour Flash", text: "That almost got you dead. Your whole life flashed before your eyes.", moduleType: ModuleType.COLOR_FLASH },
  { moduleName: "Adventure Game", text: "That’s okay. There will be another adventure waiting for you soon.", moduleType: ModuleType.ADVENTURE_GAME },
  { moduleName: "Braille", text: "The bomb blew your eyes out. Start learning Braille." },
  { moduleName: "Anagrams", text: "The instructions were clear and not in anagrams; you’re an idiot.", moduleType: ModuleType.ANAGRAMS },
  { moduleName: "Mortal Kombat", text: "The kombat with this bomb is a mortal one." },
  { moduleName: "Friendship", text: "They say Monopoly ruins friendships. They have not tried KTANE.", moduleType: ModuleType.FRIENDSHIP },
  { moduleName: "Battleship", text: "This bomb is a true battle, just not on a ship.", moduleType: ModuleType.BATTLESHIP },
  { moduleName: "Safety Safe", text: "This bomb is so valuable it should be locked in a safe.", moduleType: ModuleType.SAFETY_SAFE },
  { moduleName: "Burglar Alarm", text: "This burglar alarm is distracting me from defusing." },
  { moduleName: "Souvenir", text: "This explosion will leave a few souvenirs on your body.", moduleType: ModuleType.SOUVENIR },
  { moduleName: "Simon Says", text: "Too late. simon says you should try again.", moduleType: ModuleType.SIMON_SAYS },
  { moduleName: "Simon States", text: "Too late. Simon states you should try again.", moduleType: ModuleType.SIMON_STATES },
  { moduleName: "Wire Sequence", text: "Trickier than it sounds; all the wires are hidden behind panels.", moduleType: ModuleType.WIRE_SEQUENCES },
  { moduleName: "Microcontroller", text: "Trust your experts, don’t micro control them.", moduleType: ModuleType.MICROCONTROLLER },
  { moduleName: "Mouse In The Maze", text: "Tsk. Poor little mouse, can’t do anything right.", moduleType: ModuleType.MOUSE_IN_THE_MAZE },
  { moduleName: "The Gamepad", text: "Two kinds of people: those who use gamepad and the boring ones.", moduleType: ModuleType.GAMEPAD },
  { moduleName: "Letter Keys", text: "Wait, now keys have letters on them? What is this sorcery?", moduleType: ModuleType.LETTER_KEYS },
  { moduleName: "3D Maze", text: "Want to see this in 3D? There are special glasses for it.", moduleType: ModuleType.THREE_D_MAZE },
  { moduleName: "Skewed Slots", text: "Well, that’s what happens when your world view is so skewed.", moduleType: ModuleType.SKEWED_SLOTS },
  { moduleName: "Forget Me Not", text: "Well done. You forgot it not.", moduleType: ModuleType.FORGET_ME_NOT },
  { moduleName: "Double-Oh", text: "Who cares about Double As or Double Ds when you can have Double Os?", moduleType: ModuleType.DOUBLE_OH },
  { moduleName: "Monsplode Trading Cards", text: "Who cares about Monsplodes? Trade them away!" },
  { moduleName: "Sea Shells", text: "Who cares what she sells? She’s not gonna sell it to you.", moduleType: ModuleType.SEA_SHELLS },
  { moduleName: "Text Field", text: "Who needs fields of gold when you have a field of text?", moduleType: ModuleType.TEXT_FIELD },
  { moduleName: "Shape Shift", text: "Why be a human when you can shapeshift into an owl?", moduleType: ModuleType.SHAPE_SHIFT },
  { moduleName: "Monsplode, Fight!", text: "Why fight your family when you can fight Monsplodes?", moduleType: ModuleType.MONSPLODE_FIGHT },
  { moduleName: "Modules Against Humanity", text: "Yes, this bomb is very inhumane. Deal with it.", moduleType: ModuleType.MODULES_AGAINST_HUMANITY },
  { moduleName: "Cooking", text: "You blew me up even though I cooked for you!" },
  { moduleName: "Big Circle", text: "You blow up, you die. The big circle of life." },
  { moduleName: "Faulty Backgrounds", text: "You bombed that selfie cause of faulty background." },
  { moduleName: "Knob", text: "You can play with this knob even when you’re done with the bomb.", moduleType: ModuleType.KNOBS },
  { moduleName: "Button Sequence", text: "You can’t just press all the buttons, it has to be the correct sequence." },
  { moduleName: "Caesar Cipher", text: "You dealt with it like a true Caesar.", moduleType: ModuleType.CAESAR_CIPHER },
  { moduleName: "Silly Slots", text: "You failed. What a silly slot you are.", moduleType: ModuleType.SILLY_SLOTS },
  { moduleName: "Word Scramble", text: "You got scrambled by your own sword.", moduleType: ModuleType.WORD_SCRAMBLE },
  { moduleName: "Mystic Square", text: "You need serious help. From a shaman or a mystic, nothing less.", moduleType: ModuleType.MYSTIC_SQUARE },
  { moduleName: "Password", text: "You need to know the secret password to defuse this bomb.", moduleType: ModuleType.PASSWORDS },
  { moduleName: "Round Keypad", text: "You spin my head right round with those fancy symbols.", moduleType: ModuleType.ROUND_KEYPAD },
  { moduleName: "Chord Qualities", text: "You struck the wrong chords. Kaboom.", moduleType: ModuleType.CHORD_QUALITIES },
  { moduleName: "The Bulb", text: "You think you have a great idea? Nah, that’s just a bulb above your head.", moduleType: ModuleType.THE_BULB },
  { moduleName: "Blind Maze", text: "You’ll feel like a blind man in this maze." },
  { moduleName: "Zoo", text: "You’re an animal. You should be in a zoo.", moduleType: ModuleType.ZOO },
  { moduleName: "Who’s on First", text: "You’re clearly the last, but who’s first?", moduleType: ModuleType.WHOS_ON_FIRST },
  { moduleName: "Blind Alley", text: "You’re done. No way out from this blind alley.", moduleType: ModuleType.BLIND_ALLEY },
  { moduleName: "Rock-Paper-Scissors-Lizard-Spock", text: "You’re fighting a lizard. But don’t use caber, use scissors.", moduleType: ModuleType.ROCK_PAPER_SCISSORS_LIZARD_SPOCK },
  { moduleName: "Capacitor Discharge", text: "You’re on the dishonorable discharge, Take your capacitor and leave.", moduleType: ModuleType.CAPACITOR_DISCHARGE },
  { moduleName: "Crazy Talk", text: "You’re talking crazy. Get out.", moduleType: ModuleType.CRAZY_TALK },
  { moduleName: "Word Search", text: "You’re searching for a word? It’s the bird.", moduleType: ModuleType.WORD_SEARCH },
  { moduleName: "Coordinates", text: "You’re walking funny. Have you lost your coordinates?", moduleType: ModuleType.COORDINATES },
  { moduleName: "Neutralization", text: "Your goal is to neutralize this bomb.", moduleType: ModuleType.NEUTRALIZATION },
  { moduleName: "Cryptography", text: "Your mind is so cryptic, I can’t read it.", moduleType: ModuleType.CRYPTOGRAPHY },
  { moduleName: "Symbolic Password", text: "Your password must be 6 symbols long.", moduleType: ModuleType.SYMBOLIC_PASSWORD },
  { moduleName: "The Swan", text: "Your serial number is 4815162342." },
];

const normalize = (value: string) => value
  .normalize("NFKD")
  .toLowerCase()
  .replace(/[‘’]/g, "'")
  .replace(/[^a-z0-9]+/g, " ")
  .trim();

export function findCardReference(value: string): CardReference | null {
  const query = normalize(value);
  if (!query) return null;
  const exact = CARD_REFERENCES.find((card) => normalize(card.text) === query);
  if (exact) return exact;
  const matches = CARD_REFERENCES.filter((card) => normalize(card.text).includes(query));
  return matches.length === 1 ? matches[0] : null;
}
