import{useState}from"react";
import{MRS_BOB_RESPONSES,solveNeedyMrsBob,type NeedyMrsBobOutput}from"../../services/needyMrsBobService";
import{ModuleType,type BombEntity}from"../../types";
import{generateTwitchCommand}from"../../utils/twitchCommands";
import{ErrorAlert,SolverControls,SolverInstructions,SolverLayout,SolverSection,TwitchCommandDisplay,useSolver}from"../common";

const MESSAGES=["Can you pick up milk please?x","Can you pick up some milk, dear?x","We need more milk, dear.x","Milk’s running low. Can you grab some?","The bins are full. Again…","You didn’t take the rubbish out! Tool!","You need to take the bins out.","The bin is full again.","Running late - can you put dinner on?","Running late - would you start dinner?","Running late - start dinner.","Running late - can you put the oven on?","What time are you back tonight?","When are you back tonight?","You said you’d be back by now…","What time are you home tonight?","Just texting to say hey.x","Just texting to say hi.x","Just texting to say I love you.x","Just thinking about you.x","You’re a jerk!","Your a jerk!","You jerk!","You. Are. A. Jerk!"];
const RECEIVED=[["🐄 Cow","❤️ Heart","😊 Happy","🥛 Milk","None"],["🤢 Nauseated","😠 Angry","😷 Mask","💩 Poo","None"],["❤️ Heart","🍽️ Place setting","😘 Kiss","🍳 Cooking","None"],["⌚ Watch","😕 Confused","😟 Worried","🤔 Thinking","None"],["❤️ Heart","😘 Kiss","🛏️ Bed","🤗 Hug","None"],["😡 Angry","😢 Crying","🔪 Knife","😾 Cat","None"]];
const label=(value:string)=>value.replaceAll("_"," ").toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());

export default function NeedyMrsBobSolver({bomb}:{bomb:BombEntity|null|undefined}){
 const[message,setMessage]=useState(1),[receivedEmoji,setReceived]=useState(1),[responseOrder,setOrder]=useState<string[]>([...MRS_BOB_RESPONSES]),[result,setResult]=useState<NeedyMrsBobOutput|null>(null),[twitchCommand,setTwitchCommand]=useState("");
 const{isLoading,error,setIsLoading,setError,clearError,reset:resetSolverState,currentModule,round}=useSolver();
 const changed=()=>{setResult(null);setTwitchCommand("");clearError();};
 const solve=async()=>{if(!round?.id||!bomb?.id||!currentModule?.id)return setError("Missing required information");clearError();setIsLoading(true);try{const response=await solveNeedyMrsBob(round.id,bomb.id,currentModule.id,message,receivedEmoji,responseOrder);setResult(response.output);setTwitchCommand(generateTwitchCommand({moduleType:ModuleType.NEEDY_MRS_BOB,result:response.output}));}catch(cause){setError(cause instanceof Error?cause.message:"Failed to solve Needy Mrs Bob");}finally{setIsLoading(false);}};
 const reset=()=>{setMessage(1);setReceived(1);setOrder([...MRS_BOB_RESPONSES]);setResult(null);setTwitchCommand("");resetSolverState();};
 const bank=Math.floor((message-1)/4);
 return<SolverLayout><SolverSection title="Active message"><label>Message<select aria-label="Mrs Bob message"value={message}onChange={e=>{setMessage(Number(e.target.value));setReceived(1);changed();}}className="mt-1 h-11 w-full rounded border bg-background px-3">{MESSAGES.map((text,index)=><option key={text}value={index+1}>{index+1}. {text}</option>)}</select></label><label className="mt-3 block">Received emoji<select aria-label="Received emoji"value={receivedEmoji}onChange={e=>{setReceived(Number(e.target.value));changed();}}className="mt-1 h-11 w-full rounded border bg-background px-3">{RECEIVED[bank].map((name,index)=><option key={name}value={index+1}>{name}</option>)}</select></label></SolverSection><SolverSection title="Response grid"description="Set positions 1–24 in reading order. Each response appears exactly once."><div className="grid grid-cols-4 gap-2 sm:grid-cols-6">{responseOrder.map((value,index)=><label key={index}className="text-xs">{index+1}<select aria-label={`Response ${index+1}`}value={value}onChange={e=>{setOrder(current=>current.map((old,i)=>i===index?e.target.value:old));changed();}}className="mt-1 h-9 w-full rounded border bg-background px-1 text-xs">{MRS_BOB_RESPONSES.map(name=><option key={name}value={name}>{label(name)}</option>)}</select></label>)}</div></SolverSection><SolverControls onSolve={solve}onReset={reset}isLoading={isLoading}isSolved={false}solveText="Find response"/><ErrorAlert error={error}/>{result&&<SolverSection title="Send now"className="border-emerald-500/40"><p className="text-2xl font-bold">Position {result.responsePosition}: {label(result.response)}</p></SolverSection>}{twitchCommand&&<TwitchCommandDisplay command={twitchCommand}/>}<SolverInstructions>Use this only while the needy is active. A correct response immediately deactivates it; a wrong response or timeout strikes and deactivates it. Every later activation randomizes the message and all response positions, so press Reset and replace the entire observation. Needy modules do not produce Souvenir questions.</SolverInstructions></SolverLayout>;
}
