import { useState } from "react";
import { PLANET_NAMES, PLANET_STRIP_COLORS, solvePlanets, type PlanetsOutput } from "../../services/planetsService";
import type { BombEntity } from "../../types";
import { ErrorAlert, SolverControls, SolverInstructions, SolverLayout, SolverSection, TwitchCommandDisplay, useSolver } from "../common";

export default function PlanetsSolver({ bomb }: { bomb: BombEntity | null | undefined }) {
  const [planet, setPlanet] = useState(PLANET_NAMES[0]), [strips, setStrips] = useState(Array(5).fill(PLANET_STRIP_COLORS[0]) as string[]);
  const [factorOne, setFactorOne] = useState(21), [factorTwo, setFactorTwo] = useState(22), [result, setResult] = useState<PlanetsOutput | null>(null);
  const { isLoading, error, isSolved, setIsLoading, setError, setIsSolved, clearError, reset: resetSolverState, currentModule, round, markModuleSolved } = useSolver();
  const solve = async () => { if (!round?.id || !bomb?.id || !currentModule?.id) return setError("Missing required information"); clearError(); setIsLoading(true); try { const response = await solvePlanets(round.id, bomb.id, currentModule.id, planet, strips, factorOne, factorTwo); setResult(response.output); setIsSolved(response.solved); if (response.solved) markModuleSolved(bomb.id, currentModule.id); } catch (cause) { setError(cause instanceof Error ? cause.message : "Failed to solve Planets"); } finally { setIsLoading(false); } };
  return <SolverLayout><SolverSection title="Planet and strips"><label>Planet<select aria-label="Planet" value={planet} onChange={event => { setPlanet(event.target.value); setResult(null); }} className="mt-1 h-11 w-full rounded border bg-background px-2">{PLANET_NAMES.map(value => <option key={value}>{value}</option>)}</select></label><div className="mt-3 grid grid-cols-2 gap-3">{strips.map((strip, index) => <label key={index}>Strip {index + 1}<select aria-label={`Strip ${index + 1}`} value={strip} onChange={event => { const next = [...strips]; next[index] = event.target.value; setStrips(next); setResult(null); }} className="mt-1 h-11 w-full rounded border bg-background px-2">{PLANET_STRIP_COLORS.map(value => <option key={value}>{value}</option>)}</select></label>)}</div></SolverSection><SolverSection title="Rule-seed phrase"><div className="grid grid-cols-2 gap-3"><label>First factor<input aria-label="First factor" type="number" value={factorOne} onChange={event => setFactorOne(Number(event.target.value))} className="mt-1 h-11 w-full rounded border bg-background px-2" /></label><label>Second factor<input aria-label="Second factor" type="number" value={factorTwo} onChange={event => setFactorTwo(Number(event.target.value))} className="mt-1 h-11 w-full rounded border bg-background px-2" /></label></div></SolverSection><SolverControls onSolve={solve} onReset={() => { setPlanet(PLANET_NAMES[0]); setStrips(Array(5).fill(PLANET_STRIP_COLORS[0])); setFactorOne(21); setFactorTwo(22); setResult(null); resetSolverState(); }} isLoading={isLoading} isSolved={isSolved} /><ErrorAlert error={error} />{result && <SolverSection title={`Enter ${result.code}`} className="border-emerald-500/40"><p>A={result.numberA}, B={result.numberB}, C={result.numberC}, D={result.numberD}</p></SolverSection>}{result && <TwitchCommandDisplay command={`!number press ${result.code} space`} />}<SolverInstructions>The factors are the two numbers printed in the manual sentence “Add × multiplied by ×”; defaults are rule seed 1.</SolverInstructions></SolverLayout>;
}
