import {useState} from "react";
import {solvePurgatory,type PurgatoryOutput} from "../../services/purgatoryService";
import type {BombEntity} from "../../types";
import {ErrorAlert,SolverControls,SolverInstructions,SolverLayout,SolverSection,TwitchCommandDisplay,useSolver} from "../common";
export default function PurgatorySolver({bomb}:{bomb:BombEntity|null|undefined}){
 const [stage,setStage]=useState(1),[color,setColor]=useState("RED"),[name,setName]=useState(""),[flicker,setFlicker]=useState(false),[result,setResult]=useState<PurgatoryOutput|null>(null);const {isLoading,error,isSolved,setIsLoading,setError,setIsSolved,clearError,reset:resetSolver,currentModule,round,markModuleSolved}=useSolver();
 const solve=async()=>{if(!round?.id||!bomb?.id||!currentModule?.id)return setError("Missing required information");clearError();setIsLoading(true);try{const r=await solvePurgatory(round.id,bomb.id,currentModule.id,stage,color,name,flicker);setResult(r.output);setIsSolved(r.solved);if(r.solved)markModuleSolved(bomb.id,currentModule.id);}catch(e){setError(e instanceof Error?e.message:"Failed to solve Purgatory")}finally{setIsLoading(false)}};const reset=()=>{setStage(1);setColor("RED");setName("");setFlicker(false);setResult(null);resetSolver()};
 const command=result?`press ${result.destination==="EITHER"?"heaven":result.destination.toLowerCase()}${result.timing==="ON_TWO"?" on 2":result.clickCount>1?` ${result.clickCount}`:""}`:"";
 return <SolverLayout><SolverSection title="Current person"><div className="grid gap-3 sm:grid-cols-3"><label>Stage<input type="number" min={1} max={5} value={stage} onChange={e=>setStage(Number(e.target.value))} className="mt-1 h-11 w-full rounded border bg-background px-2"/></label><label>LED<select value={color} onChange={e=>setColor(e.target.value)} className="mt-1 h-11 w-full rounded border bg-background px-2">{["RED","BLUE","GREEN","YELLOW"].map(x=><option key={x}>{x}</option>)}</select></label><label>Name<input value={name} onChange={e=>setName(e.target.value)} className="mt-1 h-11 w-full rounded border bg-background px-2"/></label></div><label className="mt-3 block"><input type="checkbox" checked={flicker} onChange={e=>setFlicker(e.target.checked)}/> LED is flickering</label></SolverSection><SolverControls onSolve={solve} onReset={reset} isLoading={isLoading} isSolved={isSolved}/><ErrorAlert error={error}/>{result&&<SolverSection title="Judgment"><p className="text-2xl font-semibold">{result.destination}</p><p>{result.timing==="AT_END"?"Wait until every other non-ignored module is solved.":result.timing==="ON_TWO"?"Press when the timer contains a 2.":result.clickCount>1?`Press the same side ${result.clickCount} times.`:"Press now."}</p></SolverSection>}{command&&<TwitchCommandDisplay command={command}/>}<SolverInstructions>Repeat for each person. A yellow stage becomes the last stage.</SolverInstructions></SolverLayout>}
