import { useState } from "react";
import { solvePurpleArrows, type PurpleArrowsOutput } from "../../services/purpleArrowsService";
import { ModuleType, type BombEntity } from "../../types";
import { generateTwitchCommand } from "../../utils/twitchCommands";
import { ErrorAlert, SolverControls, SolverLayout, SolverSection, TwitchCommandDisplay, useSolver } from "../common";
export default function PurpleArrowsSolver({ bomb }: { bomb: BombEntity | null | undefined }) {
  const [letter, setLetter] = useState(""), [scrambled, setScrambled] = useState(""), [restart, setRestart] = useState(true), [result, setResult] = useState<PurpleArrowsOutput | null>(null), [command, setCommand] = useState("");
  const { isLoading, error, isSolved, setIsLoading, setError, setIsSolved, clearError, currentModule, round, markModuleSolved } = useSolver();
  const solve = async () => { if (!round?.id || !bomb?.id || !currentModule?.id) return setError("Missing required information"); setIsLoading(true); clearError(); try { const response = await solvePurpleArrows(round.id, bomb.id, currentModule.id, { displayedLetter: letter, scrambledWord: scrambled, reset: restart }); setRestart(false); setResult(response.output); setCommand(generateTwitchCommand({ moduleType: ModuleType.PURPLE_ARROWS, result: response.output })); setIsSolved(response.solved); if (response.solved) markModuleSolved(bomb.id, currentModule.id); } catch (cause) { setError(cause instanceof Error ? cause.message : "Failed to solve Purple Arrows"); } finally { setIsLoading(false); } };
  const reset = () => { setResult(null); setCommand(""); setRestart(true); setIsSolved(false); };
  return <SolverLayout><SolverSection title="Current display"><div className="grid gap-3 sm:grid-cols-2"><label>Displayed letter<input value={letter} maxLength={1} onChange={(e) => setLetter(e.target.value.toUpperCase())} className="mt-1 block h-11 w-full rounded-md border bg-background px-3 uppercase" /></label><label>Scrambled word<input value={scrambled} maxLength={6} onChange={(e) => setScrambled(e.target.value.toUpperCase())} className="mt-1 block h-11 w-full rounded-md border bg-background px-3 uppercase" /></label></div><p className="mt-2 text-xs text-muted-foreground">Follow each movement, enter the new displayed letter, and solve again.</p></SolverSection><SolverControls onSolve={solve} onReset={reset} solveText="Get next action" isLoading={isLoading} isSolved={isSolved} /><ErrorAlert error={error} />{result && <SolverSection title={result.submit ? "Submit" : "Move"}><p className="text-center text-3xl font-bold uppercase">{result.action}</p><p className="text-center text-sm">Target: {result.targetWord}{result.identified ? " (position identified)" : ` · ${result.remainingCandidates} candidates`}</p></SolverSection>}{command && <TwitchCommandDisplay command={command} />}</SolverLayout>;
}
