import { lazy, type ComponentType, type LazyExoticComponent } from "react";
import { ModuleCategory, type ModuleCatalogItem, ModuleType } from "../../types";
import type { SolverProps } from "./types";

type SolverLoader = () => Promise<{ default: ComponentType<SolverProps> }>;
type SolverRegistryEntry = {
  load: SolverLoader;
  isNeedy?: boolean;
};

/**
 * Registry mapping module types with a frontend UI to lazy-loaded solver components.
 * Backend-only modules still appear in the catalog and fall back to "Coming soon".
 */
export const solverRegistry: Partial<Record<string, SolverRegistryEntry>> = {
  [ModuleType.LONDON_UNDERGROUND]: { load: () => import("./LondonUndergroundSolver") },
  [ModuleType.COOKING]: { load: () => import("./CookingSolver") },
  [ModuleType.THE_SUN]: { load: () => import("./TheSunSolver") },
  [ModuleType.THE_MOON]: { load: () => import("./TheMoonSolver") },
  [ModuleType.THE_NUMBER]: { load: () => import("./TheNumberSolver") },
  [ModuleType.RUBIKS_CLOCK]: { load: () => import("./RubiksClockSolver") },
  [ModuleType.ERROR_CODES]: { load: () => import("./ErrorCodesSolver") },
  [ModuleType.LEGOS]: { load: () => import("./LegosSolver") },
  [ModuleType.THE_CUBE]: { load: () => import("./TheCubeSolver") },
  [ModuleType.JEWEL_VAULT]: { load: () => import("./JewelVaultSolver") },
  [ModuleType.DR_DOCTOR]: { load: () => import("./DrDoctorSolver") },
  [ModuleType.TAX_RETURNS]: { load: () => import("./TaxReturnsSolver") },
  [ModuleType.MARBLE_TUMBLE]: { load: () => import("./MarbleTumbleSolver") },
  [ModuleType.SINK]: { load: () => import("./SinkSolver") },
  [ModuleType.IDENTITY_PARADE]: { load: () => import("./IdentityParadeSolver") },
  [ModuleType.MAFIA]: { load: () => import("./MafiaSolver") },
  [ModuleType.JUKEBOX]: { load: () => import("./JukeboxSolver") },
  [ModuleType.WIRES]: { load: () => import("./WireSolver") },
  [ModuleType.BUTTON]: { load: () => import("./ButtonSolver") },
  [ModuleType.KEYPADS]: { load: () => import("./KeypadsSolver") },
  [ModuleType.MAZES]: { load: () => import("./MazeSolver") },
  [ModuleType.MEMORY]: { load: () => import("./MemorySolver") },
  [ModuleType.MORSE_CODE]: { load: () => import("./MorseCodeSolver") },
  [ModuleType.PASSWORDS]: { load: () => import("./PasswordSolver") },
  [ModuleType.EXTENDED_PASSWORD]: { load: () => import("./ExtendedPasswordSolver") },
  [ModuleType.SIMON_SAYS]: { load: () => import("./SimonSolver") },
  [ModuleType.WHOS_ON_FIRST]: { load: () => import("./WhosOnFirstSolver") },
  [ModuleType.THIRD_BASE]: { load: () => import("./ThirdBaseSolver") },
  [ModuleType.COMPLICATED_WIRES]: { load: () => import("./ComplicatedWiresSolver") },
  [ModuleType.WIRE_SEQUENCES]: { load: () => import("./WireSequencesSolver") },
  [ModuleType.COLOR_FLASH]: { load: () => import("./ColorFlashSolver") },
  [ModuleType.COLOR_DECODING]: { load: () => import("./ColorDecodingSolver") },
  [ModuleType.PIANO_KEYS]: { load: () => import("./PianoKeysSolver") },
  [ModuleType.SEMAPHORE]: { load: () => import("./SemaphoreSolver") },
  [ModuleType.PERSPECTIVE_PEGS]: { load: () => import("./PerspectivePegsSolver") },
  [ModuleType.EMOJI_MATH]: { load: () => import("./EmojiMathSolver") },
  [ModuleType.SWITCHES]: { load: () => import("./SwitchesSolver") },
  [ModuleType.COLORED_SWITCHES]: { load: () => import("./ColoredSwitchesSolver") },
  [ModuleType.TWO_BITS]: { load: () => import("./TwoBitsSolver") },
  [ModuleType.WORD_SCRAMBLE]: { load: () => import("./WordScrambleSolver") },
  [ModuleType.FONT_SELECT]: { load: () => import("./FontSelectSolver") },
  [ModuleType.WORD_SEARCH]: { load: () => import("./WordSearchSolver") },
  [ModuleType.BROKEN_BUTTONS]: { load: () => import("./BrokenButtonsSolver") },
  [ModuleType.COMPLICATED_BUTTONS]: { load: () => import("./ComplicatedButtonsSolver") },
  [ModuleType.ANAGRAMS]: { load: () => import("./AnagramsSolver") },
  [ModuleType.COMBINATION_LOCK]: { load: () => import("./CombinationLockSolver") },
  [ModuleType.ROUND_KEYPAD]: { load: () => import("./RoundKeypadSolver") },
  [ModuleType.COMPLEX_KEYPAD]: { load: () => import("./ComplexKeypadSolver") },
  [ModuleType.NUMBER_PAD]: { load: () => import("./NumberPadSolver") },
  [ModuleType.LISTENING]: { load: () => import("./ListeningSolver") },
  [ModuleType.FOREIGN_EXCHANGE_RATES]: { load: () => import("./ForeignExchangeSolver") },
  [ModuleType.ORIENTATION_CUBE]: { load: () => import("./OrientationCubeSolver") },
  [ModuleType.MORSEMATICS]: { load: () => import("./MorsematicsSolver") },
  [ModuleType.CONNECTION_CHECK]: { load: () => import("./ConnectionCheckSolver") },
  [ModuleType.LETTER_KEYS]: { load: () => import("./LetterKeysSolver") },
  [ModuleType.LOGIC]: { load: () => import("./LogicSolver") },
  [ModuleType.SUPERLOGIC]: { load: () => import("./SuperlogicSolver") },
  [ModuleType.LOGIC_GATES]: { load: () => import("./LogicGatesSolver") },
  [ModuleType.FORGET_ME_NOT]: { load: () => import("./ForgetMeNotSolver") },
  [ModuleType.FORGET_EVERYTHING]: { load: () => import("./ForgetEverythingSolver") },
  [ModuleType.SOUVENIR]: { load: () => import("./SouvenirSolver") },
  [ModuleType.ICE_CREAM]: { load: () => import("./IceCreamSolver") },
  [ModuleType.THE_SCREW]: { load: () => import("./TheScrewSolver") },
  [ModuleType.YAHTZEE]: { load: () => import("./YahtzeeSolver") },
  [ModuleType.X_RAY]: { load: () => import("./XRaySolver") },
  [ModuleType.BATTLESHIP]: { load: () => import("./BattleshipSolver") },
  [ModuleType.MINESWEEPER]: { load: () => import("./MinesweeperSolver") },
  [ModuleType.VISUAL_IMPAIRMENT]: { load: () => import("./VisualImpairmentSolver") },
  [ModuleType.ASTROLOGY]: { load: () => import("./AstrologySolver") },
  [ModuleType.MYSTIC_SQUARE]: { load: () => import("./MysticSquareSolver") },
  [ModuleType.CRAZY_TALK]: { load: () => import("./CrazyTalkSolver") },
  [ModuleType.ADVENTURE_GAME]: { load: () => import("./AdventureGameSolver") },
  [ModuleType.PLUMBING]: { load: () => import("./PlumbingSolver") },
  [ModuleType.CRUEL_PIANO_KEYS]: { load: () => import("./CruelPianoKeysSolver") },
  [ModuleType.FESTIVE_PIANO_KEYS]: { load: () => import("./FestivePianoKeysSolver") },
  [ModuleType.FLAGS]: { load: () => import("./FlagsSolver") },
  [ModuleType.TIMEZONE]: { load: () => import("./TimezoneSolver") },
  [ModuleType.POLYHEDRAL_MAZE]: { load: () => import("./PolyhedralMazeSolver") },
  [ModuleType.SAFETY_SAFE]: { load: () => import("./SafetySafeSolver") },
  [ModuleType.CRYPTOGRAPHY]: { load: () => import("./CryptographySolver") },
  [ModuleType.CAESAR_CIPHER]: { load: () => import("./CaesarCipherSolver") },
  [ModuleType.MODERN_CIPHER]: { load: () => import("./ModernCipherSolver") },
  [ModuleType.PLAYFAIR_CIPHER]: { load: () => import("./PlayfairCipherSolver") },
  [ModuleType.TURN_THE_KEY]: { load: () => import("./TurnTheKeySolver") },
  [ModuleType.TURN_THE_KEYS]: { load: () => import("./TurnTheKeysSolver") },
  [ModuleType.CHESS]: { load: () => import("./ChessSolver") },
  [ModuleType.MOUSE_IN_THE_MAZE]: { load: () => import("./MouseInTheMazeSolver") },
  [ModuleType.MORSE_A_MAZE]: { load: () => import("./MorseAMazeSolver") },
  [ModuleType.HEXAMAZE]: { load: () => import("./HexamazeSolver") },
  [ModuleType.BLIND_MAZE]: { load: () => import("./BlindMazeSolver") },
  [ModuleType.BITMAPS]: { load: () => import("./BitmapsSolver") },
  [ModuleType.BRAILLE]: { load: () => import("./BrailleSolver") },
  [ModuleType.COLORED_SQUARES]: { load: () => import("./ColoredSquaresSolver") },
  [ModuleType.ADJACENT_LETTERS]: { load: () => import("./AdjacentLettersSolver") },
  [ModuleType.SILLY_SLOTS]: { load: () => import("./SillySlotsSolver") },
  [ModuleType.SKEWED_SLOTS]: { load: () => import("./SkewedSlotsSolver") },
  [ModuleType.THREE_D_MAZE]: { load: () => import("./ThreeDMazeSolver") },
  [ModuleType.SIMON_STATES]: { load: () => import("./SimonStatesSolver") },
  [ModuleType.SIMON_SCREAMS]: { load: () => import("./SimonScreamsSolver") },
  [ModuleType.SIMON_SINGS]: { load: () => import("./SimonSingsSolver") },
  [ModuleType.SIMON_SENDS]: { load: () => import("./SimonSendsSolver") },
  [ModuleType.SIMON_SHRIEKS]: { load: () => import("./SimonShrieksSolver") },
  [ModuleType.MODULES_AGAINST_HUMANITY]: { load: () => import("./ModulesAgainstHumanitySolver") },
  [ModuleType.LAUNDRY]: { load: () => import("./LaundrySolver") },
  [ModuleType.PROBING]: { load: () => import("./ProbingSolver") },
  [ModuleType.ALPHABET]: { load: () => import("./AlphabetSolver") },
  [ModuleType.MICROCONTROLLER]: { load: () => import("./MicrocontrollerSolver") },
  [ModuleType.MURDER]: { load: () => import("./MurderSolver") },
  [ModuleType.SUBWAYS]: { load: () => import("./SubwaysSolver") },
  [ModuleType.RESISTORS]: { load: () => import("./ResistorsSolver") },
  [ModuleType.GAMEPAD]: { load: () => import("./GamepadSolver") },
  [ModuleType.TIC_TAC_TOE]: { load: () => import("./TicTacToeSolver") },
  [ModuleType.MONSPLODE_FIGHT]: { load: () => import("./MonsplodeFightSolver") },
  [ModuleType.MONSPLODE_TRADING_CARDS]: { load: () => import("./MonsplodeTradingCardsSolver") },
  [ModuleType.GAME_OF_LIFE_SIMPLE]: { load: () => import("./GameOfLifeSolver").then((module) => ({ default: module.GameOfLifeSimpleSolver })) },
  [ModuleType.GAME_OF_LIFE_CRUEL]: { load: () => import("./GameOfLifeSolver").then((module) => ({ default: module.GameOfLifeCruelSolver })) },
  [ModuleType.SHAPE_SHIFT]: { load: () => import("./ShapeShiftSolver") },
  [ModuleType.FOLLOW_THE_LEADER]: { load: () => import("./FollowTheLeaderSolver") },
  [ModuleType.FRIENDSHIP]: { load: () => import("./FriendshipSolver") },
  [ModuleType.THE_BULB]: { load: () => import("./TheBulbSolver") },
  [ModuleType.BLIND_ALLEY]: { load: () => import("./BlindAlleySolver") },
  [ModuleType.SEA_SHELLS]: { load: () => import("./SeaShellsSolver") },
  [ModuleType.ENGLISH_TEST]: { load: () => import("./EnglishTestSolver") },
  [ModuleType.ROCK_PAPER_SCISSORS_LIZARD_SPOCK]: { load: () => import("./RockPaperScissorsLizardSpockSolver") },
  [ModuleType.SQUARE_BUTTON]: { load: () => import("./SquareButtonSolver") },
  [ModuleType.TEXT_FIELD]: { load: () => import("./TextFieldSolver") },
  [ModuleType.SYMBOLIC_PASSWORD]: { load: () => import("./SymbolicPasswordSolver") },
  [ModuleType.WIRE_PLACEMENT]: { load: () => import("./WirePlacementSolver") },
  [ModuleType.PERPLEXING_WIRES]: { load: () => import("./PerplexingWiresSolver") },
  [ModuleType.DOUBLE_OH]: { load: () => import("./DoubleOhSolver") },
  [ModuleType.CHEAP_CHECKOUT]: { load: () => import("./CheapCheckoutSolver") },
  [ModuleType.COORDINATES]: { load: () => import("./CoordinatesSolver") },
  [ModuleType.LIGHT_CYCLE]: { load: () => import("./LightCycleSolver") },
  [ModuleType.SYMBOL_CYCLE]: { load: () => import("./SymbolCycleSolver") },
  [ModuleType.BINARY_LEDS]: { load: () => import("./BinaryLedsSolver") },
  [ModuleType.RHYTHMS]: { load: () => import("./RhythmsSolver") },
  [ModuleType.COLOR_MATH]: { load: () => import("./ColorMathSolver") },
  [ModuleType.COLOR_MORSE]: { load: () => import("./ColorMorseSolver") },
  [ModuleType.COLOR_GENERATOR]: { load: () => import("./ColorGeneratorSolver") },
  [ModuleType.BIG_CIRCLE]: { load: () => import("./BigCircleSolver") },
  [ModuleType.MASTERMIND_SIMPLE]: { load: () => import("./MastermindSimpleSolver") },
  [ModuleType.MASTERMIND_CRUEL]: { load: () => import("./MastermindCruelSolver") },
  [ModuleType.GRIDLOCK]: { load: () => import("./GridlockSolver") },
  [ModuleType.ONLY_CONNECT]: { load: () => import("./OnlyConnectSolver") },
  [ModuleType.NEUTRALIZATION]: { load: () => import("./NeutralizationSolver") },
  [ModuleType.WEB_DESIGN]: { load: () => import("./WebDesignSolver") },
  [ModuleType.CHORD_QUALITIES]: { load: () => import("./ChordQualitiesSolver") },
  [ModuleType.CREATION]: { load: () => import("./CreationSolver") },
  [ModuleType.RUBIKS_CUBE]: { load: () => import("./RubiksCubeSolver") },
  [ModuleType.FIZZ_BUZZ]: { load: () => import("./FizzBuzzSolver") },
  [ModuleType.THE_CLOCK]: { load: () => import("./TheClockSolver") },
  [ModuleType.THE_STOPWATCH]: { load: () => import("./TheStopwatchSolver") },
  [ModuleType.PIE]: { load: () => import("./PieSolver") },
  [ModuleType.THE_WIRE]: { load: () => import("./TheWireSolver") },
  [ModuleType.LED_ENCRYPTION]: { load: () => import("./LedEncryptionSolver") },
  [ModuleType.LED_GRID]: { load: () => import("./LedGridSolver") },
  [ModuleType.GRAFFITI_NUMBERS]: { load: () => import("./GraffitiNumbersSolver") },
  [ModuleType.X01]: { load: () => import("./X01Solver") },
  [ModuleType.LOGICAL_BUTTONS]: { load: () => import("./LogicalButtonsSolver") },
  [ModuleType.GRID_MATCHING]: { load: () => import("./GridMatchingSolver") },
  [ModuleType.LASERS]: { load: () => import("./LasersSolver") },
  [ModuleType.TURTLE_ROBOT]: { load: () => import("./TurtleRobotSolver") },
  [ModuleType.GUITAR_CHORDS]: { load: () => import("./GuitarChordsSolver") },
  [ModuleType.CALENDAR]: { load: () => import("./CalendarSolver") },
  [ModuleType.USA_MAZE]: { load: () => import("./USAMazeSolver") },
  [ModuleType.BINARY_TREE]: { load: () => import("./BinaryTreeSolver") },
  [ModuleType.THE_TIME_KEEPER]: { load: () => import("./TimeKeeperSolver") },
  [ModuleType.LIGHTSPEED]: { load: () => import("./LightspeedSolver") },
  [ModuleType.BLACK_HOLE]: { load: () => import("./BlackHoleSolver") },
  [ModuleType.SIMONS_STAR]: { load: () => import("./SimonsStarSolver") },
  [ModuleType.MORSE_WAR]: { load: () => import("./MorseWarSolver") },
  [ModuleType.THE_STOCK_MARKET]: { load: () => import("./StockMarketSolver") },
  [ModuleType.MINESEEKER]: { load: () => import("./MineseekerSolver") },
  [ModuleType.MAZE_SCRAMBLER]: { load: () => import("./MazeScramblerSolver") },
  [ModuleType.THE_NUMBER_CIPHER]: { load: () => import("./NumberCipherSolver") },
  [ModuleType.ALPHABET_NUMBERS]: { load: () => import("./AlphabetNumbersSolver") },
  [ModuleType.BRITISH_SLANG]: { load: () => import("./BritishSlangSolver") },
  [ModuleType.DOUBLE_COLOR]: { load: () => import("./DoubleColorSolver") },
  [ModuleType.MARITIME_FLAGS]: { load: () => import("./MaritimeFlagsSolver") },
  [ModuleType.EQUATIONS]: { load: () => import("./EquationsSolver") },
  [ModuleType.DETERMINANTS]: { load: () => import("./DeterminantsSolver"), isNeedy: true },
  [ModuleType.PATTERN_CUBE]: { load: () => import("./PatternCubeSolver") },
  [ModuleType.KNOW_YOUR_WAY]: { load: () => import("./KnowYourWaySolver") },
  [ModuleType.SPLITTING_THE_LOOT]: { load: () => import("./SplittingTheLootSolver") },
  [ModuleType.CHARACTER_SHIFT]: { load: () => import("./CharacterShiftSolver") },
  [ModuleType.SIMON_SAMPLES]: { load: () => import("./SimonSamplesSolver") },
  [ModuleType.DRAGON_ENERGY]: { load: () => import("./DragonEnergySolver") },
  [ModuleType.UNCOLORED_SQUARES]: { load: () => import("./UncoloredSquaresSolver") },
  [ModuleType.FLASHING_LIGHTS]: { load: () => import("./FlashingLightsSolver") },
  [ModuleType.THREE_D_TUNNELS]: { load: () => import("./ThreeDTunnelsSolver") },
  [ModuleType.SYNCHRONIZATION]: { load: () => import("./SynchronizationSolver") },
  [ModuleType.THE_SWITCH]: { load: () => import("./TheSwitchSolver") },
  [ModuleType.REVERSE_MORSE]: { load: () => import("./ReverseMorseSolver") },
  [ModuleType.MANOMETERS]: { load: () => import("./ManometersSolver") },
  [ModuleType.SHIKAKU]: { load: () => import("./ShikakuSolver") },
  [ModuleType.WIRE_SPAGHETTI]: { load: () => import("./WireSpaghettiSolver") },
  [ModuleType.MODULE_HOMEWORK]: { load: () => import("./ModuleHomeworkSolver") },
  [ModuleType.TENNIS]: { load: () => import("./TennisSolver") },
  [ModuleType.BENEDICT_CUMBERBATCH]: { load: () => import("./BenedictCumberbatchSolver") },
  [ModuleType.BOGGLE]: { load: () => import("./BoggleSolver") },
  [ModuleType.HORRIBLE_MEMORY]: { load: () => import("./HorribleMemorySolver") },
  [ModuleType.SIGNALS]: { load: () => import("./SignalsSolver") },
  [ModuleType.BOOLEAN_MAZE]: { load: () => import("./BooleanMazeSolver") },
  [ModuleType.SONIC_KNUCKLES]: { load: () => import("./SonicKnucklesSolver") },
  [ModuleType.QUINTUPLES]: { load: () => import("./QuintuplesSolver") },
  [ModuleType.THE_SPHERE]: { load: () => import("./SphereSolver") },
  [ModuleType.COFFEEBUCKS]: { load: () => import("./CoffeebucksSolver") },
  [ModuleType.COLORFUL_MADNESS]: { load: () => import("./ColorfulMadnessSolver") },
  [ModuleType.BASES]: { load: () => import("./BasesSolver") },
  [ModuleType.LIONS_SHARE]: { load: () => import("./LionsShareSolver") },
  [ModuleType.SNOOKER]: { load: () => import("./SnookerSolver") },
  [ModuleType.BLACKJACK]: { load: () => import("./BlackjackSolver") },
  [ModuleType.PARTY_TIME]: { load: () => import("./PartyTimeSolver") },
  [ModuleType.ACCUMULATION]: { load: () => import("./AccumulationSolver") },
  [ModuleType.THE_PLUNGER_BUTTON]: { load: () => import("./PlungerButtonSolver") },
  [ModuleType.THE_DIGIT]: { load: () => import("./TheDigitSolver") },
  [ModuleType.THE_JACK_O_LANTERN]: { load: () => import("./JackOLanternSolver") },
  [ModuleType.T_WORDS]: { load: () => import("./TWordsSolver") },
  [ModuleType.DIVIDED_SQUARES]: { load: () => import("./DividedSquaresSolver") },
  [ModuleType.CONNECTION_DEVICE]: { load: () => import("./ConnectionDeviceSolver") },
  [ModuleType.INSTRUCTIONS]: { load: () => import("./InstructionsSolver") },
  [ModuleType.VALVES]: { load: () => import("./ValvesSolver") },
  [ModuleType.BLOCKBUSTERS]: { load: () => import("./BlockbustersSolver") },
  [ModuleType.CATCHPHRASE]: { load: () => import("./CatchphraseSolver") },
  [ModuleType.COUNTDOWN]: { load: () => import("./CountdownSolver") },
  [ModuleType.CRUEL_COUNTDOWN]: { load: () => import("./CruelCountdownSolver") },
  [ModuleType.ENCRYPTED_MORSE]: { load: () => import("./EncryptedMorseSolver") },
  [ModuleType.THE_CRYSTAL_MAZE]: { load: () => import("./TheCrystalMazeSolver") },
  [ModuleType.IKEA]: { load: () => import("./IkeaSolver") },
  [ModuleType.RETIREMENT]: { load: () => import("./RetirementSolver") },
  [ModuleType.ONE_HUNDRED_AND_ONE_DALMATIANS]: { load: () => import("./OneHundredAndOneDalmatiansSolver") },
  [ModuleType.PERIODIC_TABLE]: { load: () => import("./PeriodicTableSolver") },
  [ModuleType.SCHLAG_DEN_BOMB]: { load: () => import("./SchlagDenBombSolver") },
  [ModuleType.MAHJONG]: { load: () => import("./MahjongSolver") },
  [ModuleType.KUDOSUDOKU]: { load: () => import("./KudosudokuSolver") },
  [ModuleType.THE_RADIO]: { load: () => import("./TheRadioSolver") },
  [ModuleType.MODULO]: { load: () => import("./ModuloSolver") },
  [ModuleType.NUMBER_NIMBLENESS]: { load: () => import("./NumberNimblenessSolver") },
  [ModuleType.PAY_RESPECTS]: { load: () => import("./PayRespectsSolver") },
  [ModuleType.CHALLENGE_AND_CONTACT]: { load: () => import("./ChallengeAndContactSolver") },
  [ModuleType.THE_TRIANGLE]: { load: () => import("./TheTriangleSolver") },
  [ModuleType.SUEET_WALL]: { load: () => import("./SueetWallSolver") },
  [ModuleType.HOT_POTATO]: { load: () => import("./HotPotatoSolver") },
  [ModuleType.CHRISTMAS_PRESENTS]: { load: () => import("./ChristmasPresentsSolver") },
  [ModuleType.HIEROGLYPHICS]: { load: () => import("./HieroglyphicsSolver") },
  [ModuleType.FUNCTIONS]: { load: () => import("./FunctionsSolver") },
  [ModuleType.NEEDY_MRS_BOB]: { load: () => import("./NeedyMrsBobSolver") },
  [ModuleType.SCRIPTING]: { load: () => import("./ScriptingSolver") },
  [ModuleType.SIMON_SPINS]: { load: () => import("./SimonSpinsSolver") },
  [ModuleType.CURSED_DOUBLE_OH]: { load: () => import("./CursedDoubleOhSolver") },
  [ModuleType.TEN_BUTTON_COLOR_CODE]: { load: () => import("./TenButtonColorCodeSolver") },
  [ModuleType.CRACKBOX]: { load: () => import("./CrackboxSolver") },
  [ModuleType.STREET_FIGHTER]: { load: () => import("./StreetFighterSolver") },
  [ModuleType.IMBALANCE]: { load: () => import("./ImbalanceSolver") },
  [ModuleType.SEQUENCES]: { load: () => import("./SequencesSolver") },
  [ModuleType.FAULTY_DIGITAL_ROOT]: { load: () => import("./FaultyDigitalRootSolver") },
  [ModuleType.THREE_LEDS]: { load: () => import("./ThreeLedsSolver") },
  [ModuleType.SIMPLETON]: { load: () => import("./SimpletonSolver") },
  [ModuleType.THE_NEUTRAL_BUTTON]: { load: () => import("./TheNeutralButtonSolver") },
  [ModuleType.TANGRAMS]: { load: () => import("./TangramsSolver") },
  [ModuleType.BITWISE_OPERATIONS]: { load: () => import("./BitwiseOperationsSolver") },
  [ModuleType.FAST_MATH]: { load: () => import("./FastMathSolver") },
  [ModuleType.BOOLEAN_VENN_DIAGRAM]: { load: () => import("./BooleanVennDiagramSolver") },
  [ModuleType.ZOO]: { load: () => import("./ZooSolver") },
  [ModuleType.POINT_OF_ORDER]: { load: () => import("./PointOfOrderSolver") },
  [ModuleType.NONOGRAM]: { load: () => import("./NonogramSolver") },
  [ModuleType.SET]: { load: () => import("./SetSolver") },
  [ModuleType.HUNTING]: { load: () => import("./HuntingSolver") },
  [ModuleType.CURRICULUM]: { load: () => import("./CurriculumSolver") },
  [ModuleType.PAINTING]: { load: () => import("./PaintingSolver") },
  [ModuleType.MAINTENANCE]: { load: () => import("./MaintenanceSolver") },
  [ModuleType.BACKGROUNDS]: { load: () => import("./BackgroundsSolver") },
  [ModuleType.FAULTY_BACKGROUNDS]: { load: () => import("./FaultyBackgroundsSolver") },
  [ModuleType.MORTAL_KOMBAT]: { load: () => import("./MortalKombatSolver") },
  [ModuleType.MASHEMATICS]: { load: () => import("./MashematicsSolver") },
  [ModuleType.GREEK_CALCULUS]: { load: () => import("./GreekCalculusSolver") },
  [ModuleType.RADIATOR]: { load: () => import("./RadiatorSolver") },
  [ModuleType.THE_IPHONE]: { load: () => import("./TheIPhoneSolver") },
  [ModuleType.THE_SWAN]: { load: () => import("./TheSwanSolver") },
  [ModuleType.WASTE_MANAGEMENT]: { load: () => import("./WasteManagementSolver") },
  [ModuleType.HUMAN_RESOURCES]: { load: () => import("./HumanResourcesSolver") },
  [ModuleType.EUROPEAN_TRAVEL]: { load: () => import("./EuropeanTravelSolver") },
  [ModuleType.BURGLAR_ALARM]: { load: () => import("./BurglarAlarmSolver") },
  [ModuleType.PRESS_X]: { load: () => import("./PressXSolver") },
  [ModuleType.THE_CODE]: { load: () => import("./TheCodeSolver") },
  [ModuleType.TAP_CODE]: { load: () => import("./TapCodeSolver") },
  [ModuleType.SYNONYMS]: { load: () => import("./SynonymsSolver") },
  [ModuleType.DIGITAL_ROOT]: { load: () => import("./DigitalRootSolver") },
  [ModuleType.SKYRIM]: { load: () => import("./SkyrimSolver") },
  [ModuleType.KNOBS]: { load: () => import("./KnobsSolver"), isNeedy: true },
  [ModuleType.VENTING_GAS]: { load: () => import("./VentingGasSolver"), isNeedy: true },
  [ModuleType.CAPACITOR_DISCHARGE]: { load: () => import("./CapacitorDischargeSolver"), isNeedy: true },
};

/**
 * Stable map of pre-built React.lazy() references for registered solver UIs.
 * Built once at module load time so the same moduleType always returns the
 * identical lazy() reference, preventing unnecessary remounts.
 */
export const lazySolverRegistry = Object.fromEntries(
  Object.entries(solverRegistry).flatMap(([moduleType, entry]) =>
    entry ? [[moduleType, lazy(entry.load)] as const] : [],
  ),
) as Partial<Record<string, LazyExoticComponent<ComponentType<SolverProps>>>>;

function isNeedyCategory(category: ModuleCategory): boolean {
  return (
    category === ModuleCategory.VANILLA_NEEDY ||
    category === ModuleCategory.MODDED_NEEDY
  );
}

/**
 * Returns true if the given module type is a needy module, using the catalog
 * as the primary source of truth (category-based) and falling back to the
 * registry's isNeedy flag when the catalog entry is unavailable.
 */
export function isNeedyModuleType(
  moduleType: string,
  catalogByType: Record<string, ModuleCatalogItem | undefined>,
): boolean {
  const catalogEntry = catalogByType[moduleType];
  if (catalogEntry) {
    return isNeedyCategory(catalogEntry.category);
  }

  const registryEntry = solverRegistry[moduleType];
  return Boolean(registryEntry?.isNeedy);
}

/**
 * Returns a stable React.lazy component for the given module type, or null if
 * no solver is registered. Always returns the same reference for the same type.
 */
export function getLazySolver(moduleType?: string) {
  if (!moduleType) return null;
  return lazySolverRegistry[moduleType] ?? null;
}
