import { useState } from "react";
import { solveRiskyWires, type RiskyLedColor, type RiskyWireColor, type RiskyWiresOutput } from "../../services/riskyWiresService";
import { ModuleType, type BombEntity } from "../../types";
import { generateTwitchCommand } from "../../utils/twitchCommands";
import { ErrorAlert, SolverControls, SolverLayout, SolverSection, TwitchCommandDisplay, useSolver } from "../common";
const wireColors: RiskyWireColor[] = ["RED", "BLUE", "YELLOW", "GREEN", "PURPLE"], ledColors: RiskyLedColor[] = ["OFF", "RED", "GREEN"];
export default function RiskyWiresSolver({ bomb }: { bomb: BombEntity | null | undefined }) {
  const [count, setCount] = useState(6), [idNumber, setIdNumber] = useState("0000"), [topLed, setTopLed] = useState<RiskyLedColor>("OFF"), [bottomLed, setBottomLed] = useState<RiskyLedColor>("OFF"), [failed, setFailed] = useState(1), [wires, setWires] = useState<RiskyWireColor[]>(Array(8).fill("RED")), [result, setResult] = useState<RiskyWiresOutput | null>(null), [command, setCommand] = useState("");
  const { isLoading, error, isSolved, setIsLoading, setError, setIsSolved, clearError, currentModule, round, markModuleSolved } = useSolver();
  const solve = async () => { if (!round?.id || !bomb?.id || !currentModule?.id) return setError("Missing required information"); setIsLoading(true); clearError(); try { const response = await solveRiskyWires(round.id, bomb.id, currentModule.id, { idNumber, topLed, bottomLed, wireColors: wires.slice(0, count), failedGambleAttempt: failed }); setResult(response.output); setCommand(generateTwitchCommand({ moduleType: ModuleType.RISKY_WIRES, result: response.output })); setIsSolved(response.solved); if (response.solved) markModuleSolved(bomb.id, currentModule.id); } catch (cause) { setError(cause instanceof Error ? cause.message : "Failed to solve Risky Wires"); } finally { setIsLoading(false); } };
  return <SolverLayout><SolverSection title="Revealed module"><div className="grid gap-3 sm:grid-cols-4"><label>Wire count<select value={count} onChange={(e) => setCount(Number(e.target.value))} className="mt-1 block h-11 w-full rounded-md border bg-background px-3">{[1,2,3,4,5,6,8].map(n => <option key={n}>{n}</option>)}</select></label><label>ID number<input value={idNumber} maxLength={4} onChange={(e) => setIdNumber(e.target.value.replace(/\D/g, ""))} className="mt-1 block h-11 w-full rounded-md border bg-background px-3" /></label><label>Top LED<select value={topLed} onChange={(e) => setTopLed(e.target.value as RiskyLedColor)} className="mt-1 block h-11 w-full rounded-md border bg-background px-3">{ledColors.map(x => <option key={x}>{x}</option>)}</select></label><label>Bottom LED<select value={bottomLed} onChange={(e) => setBottomLed(e.target.value as RiskyLedColor)} className="mt-1 block h-11 w-full rounded-md border bg-background px-3">{ledColors.map(x => <option key={x}>{x}</option>)}</select></label></div>{count === 8 && <label className="mt-3 block">Failed gamble attempt<input type="number" min={1} max={6} value={failed} onChange={(e) => setFailed(Number(e.target.value))} className="mt-1 block h-11 w-full rounded-md border bg-background px-3" /></label>}<div className="mt-3 grid grid-cols-4 gap-2">{wires.slice(0,count).map((color,i) => <label key={i} className="text-center text-xs">Wire {i+1}<select value={color} onChange={(e) => setWires(wires.map((x,j) => j === i ? e.target.value as RiskyWireColor : x))} className="mt-1 block h-10 w-full rounded-md border bg-background px-1 text-xs">{wireColors.map(x => <option key={x}>{x}</option>)}</select></label>)}</div></SolverSection><SolverControls onSolve={solve} onReset={() => { setResult(null); setCommand(""); setIsSolved(false); }} isLoading={isLoading} isSolved={isSolved} /><ErrorAlert error={error} />{result && <SolverSection title="Cut and submit"><p className="text-center text-3xl font-bold">{result.cutPositions.length ? result.cutPositions.join(" ") : "No wires"}</p>{(result.reversedSixWireRules || result.shiftedEightWireRules) && <p className="text-center text-sm">Special rule applied.</p>}</SolverSection>}{command && <TwitchCommandDisplay command={command} />}</SolverLayout>;
}
