import{useCallback,useMemo,useState}from"react";
import{SCRIPTING_PROGRAMS,solveScripting,type ScriptingOutput}from"../../services/scriptingService";
import{useRoundStore}from"../../store/useRoundStore";
import{ModuleType,type BombEntity}from"../../types";
import{generateTwitchCommand}from"../../utils/twitchCommands";
import{ErrorAlert,SolverControls,SolverInstructions,SolverLayout,SolverSection,TwitchCommandDisplay,useSolver,useSolverModulePersistence}from"../common";
const actionLabel=(value:string)=>({HANDLE_SOLVE:"HandleSolve();",HANDLE_STRIKE:"HandleStrike();",SOLVE:"Solve();",STRIKE:"Strike();",ON_SOLVE:"OnSolve();",ON_STRIKE:"OnStrike();"}[value]??value);
export default function ScriptingSolver({bomb}:{bomb:BombEntity|null|undefined}){
 const[usingPrograms,setPrograms]=useState<string[]>(["KTaNE","KMAPI","BombGenerator"]),[intValue,setInt]=useState(1),[floatValue,setFloat]=useState(1),[boolValue,setBool]=useState(false),[result,setResult]=useState<ScriptingOutput|null>(null),[twitchCommand,setTwitchCommand]=useState("");
 const{isLoading,error,isSolved,setIsLoading,setError,setIsSolved,clearError,reset:resetSolverState,currentModule,round,markModuleSolved}=useSolver();const updateModuleAfterSolve=useRoundStore(s=>s.updateModuleAfterSolve);const state=useMemo(()=>({usingPrograms,intValue,floatValue,boolValue,result,twitchCommand}),[usingPrograms,intValue,floatValue,boolValue,result,twitchCommand]);
 useSolverModulePersistence<typeof state,ScriptingOutput>({state,onRestoreState:useCallback(s=>{if(s.usingPrograms)setPrograms(s.usingPrograms);if(s.intValue!==undefined)setInt(s.intValue);if(s.floatValue!==undefined)setFloat(s.floatValue);if(s.boolValue!==undefined)setBool(s.boolValue);if(s.result)setResult(s.result);if(s.twitchCommand)setTwitchCommand(s.twitchCommand);},[]),onRestoreSolution:useCallback((solution:ScriptingOutput)=>{setResult(solution);setTwitchCommand(generateTwitchCommand({moduleType:ModuleType.SCRIPTING,result:solution}));},[]),currentModule,setIsSolved});
 const changed=()=>{setResult(null);setTwitchCommand("");setIsSolved(false);clearError();};const solve=async()=>{if(!round?.id||!bomb?.id||!currentModule?.id)return setError("Missing required information");clearError();setIsLoading(true);try{const response=await solveScripting(round.id,bomb.id,currentModule.id,usingPrograms,intValue,floatValue,boolValue);const command=generateTwitchCommand({moduleType:ModuleType.SCRIPTING,result:response.output});setResult(response.output);setTwitchCommand(command);setIsSolved(response.solved);markModuleSolved(bomb.id,currentModule.id);updateModuleAfterSolve(bomb.id,currentModule.id,{usingPrograms,intValue,floatValue,boolValue,result:response.output,twitchCommand:command},response.output,true);}catch(cause){setError(cause instanceof Error?cause.message:"Failed to solve Scripting");}finally{setIsLoading(false);}};const reset=()=>{setPrograms(["KTaNE","KMAPI","BombGenerator"]);setInt(1);setFloat(1);setBool(false);setResult(null);setTwitchCommand("");resetSolverState();};
 return<SolverLayout><SolverSection title="Using directives"><div className="grid gap-3 sm:grid-cols-3">{usingPrograms.map((value,index)=><label key={index}>Using {index+1}<select aria-label={`Using ${index+1}`}value={value}onChange={e=>{setPrograms(current=>current.map((old,i)=>i===index?e.target.value:old));changed();}}className="mt-1 h-11 w-full rounded border bg-background px-3">{SCRIPTING_PROGRAMS.map(program=><option key={program}>{program}</option>)}</select></label>)}</div></SolverSection><SolverSection title="Variable cycle"description="Cycle through every type and record these three values."><div className="grid gap-3 sm:grid-cols-3"><label>int value<input aria-label="Int value"type="number"value={intValue}onChange={e=>{setInt(Number(e.target.value));changed();}}className="mt-1 h-11 w-full rounded border bg-background px-3"/></label><label>float value<input aria-label="Float value"type="number"step="any"value={floatValue}onChange={e=>{setFloat(Number(e.target.value));changed();}}className="mt-1 h-11 w-full rounded border bg-background px-3"/></label><label>bool value<select aria-label="Bool value"value={String(boolValue)}onChange={e=>{setBool(e.target.value==="true");changed();}}className="mt-1 h-11 w-full rounded border bg-background px-3"><option value="false">false</option><option value="true">true</option></select></label></div></SolverSection><SolverControls onSolve={solve}onReset={reset}isLoading={isLoading}isSolved={isSolved}/><ErrorAlert error={error}/>{result&&<SolverSection title="Correct script"className="border-emerald-500/40"><ul className="space-y-1">{result.usingNecessary.map((needed,index)=><li key={index}>Using {index+1}: <strong>{needed?"keep":"fade out"}</strong></li>)}<li>Variable: <strong>{result.variableType.toLowerCase()}</strong></li><li>Method: <strong>{result.methodType.toLowerCase()}</strong></li><li>Action: <strong>{actionLabel(result.action)}</strong></li></ul></SolverSection>}{twitchCommand&&<TwitchCommandDisplay command={twitchCommand}/>}<SolverInstructions>Press cyclevar or the variable text until you have seen int, float, bool, and char; only the first three values affect the rules. The method answer uses the solved-module parity at the moment Run is pressed. Wrong Run attempts strike but do not regenerate the script, and the generated Twitch sequence safely resets every editable field before running. Scripting is not a Souvenir candidate.</SolverInstructions></SolverLayout>;
}
