import { useCallback,useMemo,useState } from "react";
import { solveSignals,type SignalsOutput,type SignalsSwitchState,type SignalsSwitchWiring } from "../../services/signalsService";
import { useRoundStore } from "../../store/useRoundStore";import { ModuleType,type BombEntity } from "../../types";import { generateTwitchCommand } from "../../utils/twitchCommands";import { ErrorAlert,SolverControls,SolverInstructions,SolverLayout,SolverSection,TwitchCommandDisplay,useSolver,useSolverModulePersistence } from "../common";
const INITIAL:SignalsSwitchWiring[]=[1,2,3].map(coefficient=>({coefficient,upValue:1,centerValue:0,downValue:-1,currentState:"DOWN"}));
const STATES:SignalsSwitchState[]=["UP","CENTER_NEXT_DOWN","DOWN","CENTER_NEXT_UP"];
export default function SignalsSolver({bomb}:{bomb:BombEntity|null|undefined}){
 const [inputFigure,setInputFigure]=useState(1),[strikes,setStrikes]=useState(0),[switches,setSwitches]=useState<SignalsSwitchWiring[]>(INITIAL),[result,setResult]=useState<SignalsOutput|null>(null),[twitchCommand,setTwitchCommand]=useState("");
 const {isLoading,error,isSolved,setIsLoading,setError,setIsSolved,clearError,reset:resetSolverState,currentModule,round,markModuleSolved}=useSolver();const updateModuleAfterSolve=useRoundStore(s=>s.updateModuleAfterSolve);const state=useMemo(()=>({inputFigure,strikes,switches,result,twitchCommand}),[inputFigure,strikes,switches,result,twitchCommand]);
 useSolverModulePersistence<typeof state,SignalsOutput>({state,onRestoreState:useCallback(saved=>{if(saved.inputFigure)setInputFigure(saved.inputFigure);if(saved.strikes!==undefined)setStrikes(saved.strikes);if(saved.switches)setSwitches(saved.switches);if(saved.result)setResult(saved.result);if(saved.twitchCommand)setTwitchCommand(saved.twitchCommand);},[]),onRestoreSolution:useCallback((solution:SignalsOutput)=>{setResult(solution);setTwitchCommand(generateTwitchCommand({moduleType:ModuleType.SIGNALS,result:solution}));},[]),currentModule,setIsSolved});
 const update=(index:number,change:Partial<SignalsSwitchWiring>)=>{setSwitches(old=>old.map((item,i)=>i===index?{...item,...change}:item));setResult(null);setTwitchCommand("");clearError();};
 const solve=async()=>{if(!round?.id||!bomb?.id||!currentModule?.id)return setError("Missing required information");clearError();setIsLoading(true);try{const response=await solveSignals(round.id,bomb.id,currentModule.id,inputFigure,strikes,switches);const command=generateTwitchCommand({moduleType:ModuleType.SIGNALS,result:response.output});setResult(response.output);setTwitchCommand(command);setIsSolved(response.solved);if(response.solved)markModuleSolved(bomb.id,currentModule.id);updateModuleAfterSolve(bomb.id,currentModule.id,{inputFigure,strikes,switches,result:response.output,twitchCommand:command},response.output,response.solved);}catch(cause){setError(cause instanceof Error?cause.message:"Failed to solve Signals");}finally{setIsLoading(false);}};
 const reset=()=>{setInputFigure(1);setStrikes(0);setSwitches(INITIAL);setResult(null);setTwitchCommand("");resetSolverState();};const numberSelect=(value:number,onChange:(value:number)=>void)=><select value={value} onChange={event=>onChange(Number(event.target.value))} className="rounded-md border border-input bg-background p-2">{[-1,0,1].map(v=><option key={v}>{v}</option>)}</select>;
 return <SolverLayout><SolverSection title="Input signal and strikes"><div className="grid gap-3 sm:grid-cols-2"><label>Input figure (1–27)<input aria-label="Input figure" type="number" min={1} max={27} value={inputFigure} onChange={e=>setInputFigure(Number(e.target.value))} className="mt-1 w-full rounded-md border border-input bg-background p-2"/></label><label>Current strikes<input aria-label="Current strikes" type="number" min={0} value={strikes} onChange={e=>setStrikes(Number(e.target.value))} className="mt-1 w-full rounded-md border border-input bg-background p-2"/></label></div></SolverSection><SolverSection title="Decoded physical switch wiring" description="For each switch, enter its controlled coefficient, position values, and current four-state cycle state."><div className="space-y-3">{switches.map((w,index)=><div key={index} className="grid gap-2 rounded border p-3 sm:grid-cols-5"><strong>S{index+1}</strong><label>C<select aria-label={`S${index+1} coefficient`} value={w.coefficient} onChange={e=>update(index,{coefficient:Number(e.target.value)})} className="ml-1 rounded-md border border-input bg-background p-2">{[1,2,3].map(v=><option key={v}>{v}</option>)}</select></label><label>Up {numberSelect(w.upValue,value=>update(index,{upValue:value}))}</label><label>Center {numberSelect(w.centerValue,value=>update(index,{centerValue:value}))}</label><label>Down {numberSelect(w.downValue,value=>update(index,{downValue:value}))}</label><label className="sm:col-span-5">Current state <select aria-label={`S${index+1} current state`} value={w.currentState} onChange={e=>update(index,{currentState:e.target.value as SignalsSwitchState})} className="ml-1 rounded-md border border-input bg-background p-2">{STATES.map(v=><option key={v}>{v.toLowerCase().replaceAll("_"," ")}</option>)}</select></label></div>)}</div></SolverSection><SolverControls onSolve={solve} onReset={reset} isLoading={isLoading} isSolved={isSolved}/><ErrorAlert error={error}/>{result&&<SolverSection title="Generator setup" className="border-emerald-500/40"><p className="text-xl font-bold">C1,C2,C3 = {result.targetCoefficients.join(", ")}</p><p>S1,S2,S3: {result.targetPositions.join(", ")}</p><p>{result.clicks.length?`Click ${result.clicks.join(" ")}, then submit.`:"Submit without changing a switch."}</p></SolverSection>}{twitchCommand&&<TwitchCommandDisplay command={twitchCommand}/>}<SolverInstructions>A center position has two hidden cycle states; select the one implied by your tracked last movement. After a strike, keep the same wiring and current switch states, update the strike count, and solve again.</SolverInstructions></SolverLayout>;
}
