import { useState } from "react";
import { solveSimonStops, type SimonStopsColor, type SimonStopsOutput } from "../../services/simonStopsService";
import { ModuleType, type BombEntity } from "../../types";
import { generateTwitchCommand } from "../../utils/twitchCommands";
import { ErrorAlert, SolverControls, SolverLayout, SolverSection, TwitchCommandDisplay, useSolver } from "../common";
const colors: SimonStopsColor[] = ["RED", "ORANGE", "YELLOW", "GREEN", "BLUE", "VIOLET"];
export default function SimonStopsSolver({ bomb }: { bomb: BombEntity | null | undefined }) {
  const [stage, setStage] = useState(1), [flashes, setFlashes] = useState<SimonStopsColor[]>(Array(5).fill("RED")), [awaiting, setAwaiting] = useState(false), [completed, setCompleted] = useState(1), [result, setResult] = useState<SimonStopsOutput | null>(null), [command, setCommand] = useState("");
  const { isLoading, error, isSolved, setIsLoading, setError, setIsSolved, clearError, currentModule, round, markModuleSolved } = useSolver();
  const solve = async () => { if (!round?.id || !bomb?.id || !currentModule?.id) return setError("Missing required information"); setIsLoading(true); clearError(); try { const response = await solveSimonStops(round.id, bomb.id, currentModule.id, { flashedColors: flashes.slice(0, stage + 2), normalPressesCompleted: awaiting ? completed : null }); setResult(response.output); setCommand(generateTwitchCommand({ moduleType: ModuleType.SIMON_STOPS, result: response.output })); setIsSolved(response.solved); if (response.output.awaitingControlPosition) { setAwaiting(true); setCompleted(1); } else { setAwaiting(false); setStage(response.output.nextStage); } if (response.solved) markModuleSolved(bomb.id, currentModule.id); } catch (cause) { setError(cause instanceof Error ? cause.message : "Failed to solve Simon Stops"); } finally { setIsLoading(false); } };
  return <SolverLayout><SolverSection title={`Stage ${stage} flashes`} description={awaiting ? "Enter how many normal presses were accepted before the module stopped for Control Input." : "Enter the flashed colors in order."}>{awaiting ? <label className="block">Normal presses completed<input type="number" min={1} max={stage + 1} value={completed} onChange={(e) => setCompleted(Number(e.target.value))} className="mt-1 block h-11 w-full rounded-md border bg-background px-3" /></label> : <div className="grid grid-cols-3 gap-2">{flashes.slice(0, stage + 2).map((color, i) => <label key={i} className="text-xs">Flash {i + 1}<select value={color} onChange={(e) => setFlashes(flashes.map((x, j) => j === i ? e.target.value as SimonStopsColor : x))} className="mt-1 block h-10 w-full rounded-md border bg-background px-1">{colors.map(x => <option key={x}>{x}</option>)}</select></label>)}</div>}</SolverSection><SolverControls onSolve={solve} onReset={() => { setStage(1); setAwaiting(false); setResult(null); setCommand(""); setIsSolved(false); }} solveText={awaiting ? "Get control continuation" : "Get normal input"} isLoading={isLoading} isSolved={isSolved} /><ErrorAlert error={error} />{result && <SolverSection title={result.awaitingControlPosition ? "Normal input" : "Control input and remainder"}><p className="text-center text-2xl font-bold">{result.pressColors.join(" ")}</p>{result.awaitingControlPosition && <p className="text-center text-sm">Enter this command; Twitch will stop it when Control Input is required.</p>}</SolverSection>}{command && <TwitchCommandDisplay command={command} />}</SolverLayout>;
}
