import { useState } from "react";
import { solveStickyNotes, type StickyNotesOutput } from "../../services/stickyNotesService";
import type { BombEntity } from "../../types";
import { ErrorAlert, SolverControls, SolverInstructions, SolverLayout, SolverSection, TwitchCommandDisplay, useSolver } from "../common";

const days = ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"];
export default function StickyNotesSolver({ bomb }: { bomb: BombEntity | null | undefined }) {
  const [weekday,setWeekday]=useState(days[new Date().getDay() === 0 ? 6 : new Date().getDay()-1]), [notes,setNotes]=useState(Array(10).fill("") as string[]), [result,setResult]=useState<StickyNotesOutput|null>(null);
  const { isLoading,error,isSolved,setIsLoading,setError,setIsSolved,clearError,reset:resetSolverState,currentModule,round,markModuleSolved}=useSolver();
  const solve=async()=>{if(!round?.id||!bomb?.id||!currentModule?.id)return setError("Missing required information");clearError();setIsLoading(true);try{const response=await solveStickyNotes(round.id,bomb.id,currentModule.id,weekday,notes);setResult(response.output);setIsSolved(response.solved);if(response.solved)markModuleSolved(bomb.id,currentModule.id);}catch(cause){setError(cause instanceof Error?cause.message:"Failed to solve Sticky Notes");}finally{setIsLoading(false);}};
  return <SolverLayout><SolverSection title="Bomb start day"><select aria-label="Weekday" value={weekday} onChange={event=>{setWeekday(event.target.value);setResult(null);}} className="h-11 w-full rounded border bg-background px-2">{days.map(day=><option key={day}>{day}</option>)}</select></SolverSection><SolverSection title="Notes 1–10"><div className="grid gap-2">{notes.map((note,index)=><label key={index}>{index+1}<input aria-label={`Note ${index+1}`} value={note} onChange={event=>{const next=[...notes];next[index]=event.target.value;setNotes(next);setResult(null);}} className="ml-2 h-10 w-[calc(100%-2rem)] rounded border bg-background px-2" /></label>)}</div></SolverSection><SolverControls onSolve={solve} onReset={()=>{setNotes(Array(10).fill(""));setResult(null);resetSolverState();}} isLoading={isLoading} isSolved={isSolved}/><ErrorAlert error={error}/>{result&&<SolverSection title={`Select note ${result.notePosition}`} className="border-emerald-500/40"><p>{result.task}</p><p className="text-sm text-muted-foreground">{result.category}</p></SolverSection>}{result&&<TwitchCommandDisplay command={`!number select ${result.notePosition}`}/>}<SolverInstructions>Enter note text without line breaks. The parser ignores punctuation and capitalization.</SolverInstructions></SolverLayout>;
}
