import { useCallback, useMemo, useState } from "react";
import { solveTennis, type TennisInput, type TennisOutput } from "../../services/tennisService";
import { useRoundStore } from "../../store/useRoundStore";
import { ModuleType, type BombEntity } from "../../types";
import { generateTwitchCommand } from "../../utils/twitchCommands";
import { ErrorAlert, SolverControls, SolverInstructions, SolverLayout, SolverSection, TwitchCommandDisplay, useSolver, useSolverModulePersistence } from "../common";

const parseSets = (text: string) => text.split(/\r?\n/).map((line) => line.trim()).filter(Boolean).map((line) => { const match = /^(\d+)\s*[-:]\s*(\d+)$/.exec(line); if (!match) throw new Error(`Invalid set score: ${line}`); return { player1: Number(match[1]), player2: Number(match[2]) }; });
export default function TennisSolver({ bomb }: { bomb: BombEntity | null | undefined }) {
  const [tournament, setTournament] = useState<TennisInput["tournament"]>("US_OPEN"); const [mensPlay, setMensPlay] = useState(false); const [setsText, setSetsText] = useState("3-4"); const [mode, setMode] = useState<TennisInput["mode"]>("NORMAL"); const [p1, setP1] = useState(0); const [p2, setP2] = useState(0); const [result, setResult] = useState<TennisOutput | null>(null); const [twitchCommand, setTwitchCommand] = useState("");
  const { isLoading, error, isSolved, setIsLoading, setError, setIsSolved, clearError, reset: resetSolverState, currentModule, round, markModuleSolved } = useSolver(); const updateModuleAfterSolve = useRoundStore((state) => state.updateModuleAfterSolve);
  const state = useMemo(() => ({ tournament, mensPlay, setsText, mode, p1, p2, result, twitchCommand }), [tournament, mensPlay, setsText, mode, p1, p2, result, twitchCommand]);
  useSolverModulePersistence<typeof state, TennisOutput>({ state, onRestoreState: useCallback((saved) => { if (saved.tournament) setTournament(saved.tournament); if (saved.mensPlay !== undefined) setMensPlay(saved.mensPlay); if (saved.setsText) setSetsText(saved.setsText); if (saved.mode) setMode(saved.mode); if (saved.p1 !== undefined) setP1(saved.p1); if (saved.p2 !== undefined) setP2(saved.p2); if (saved.result) setResult(saved.result); if (saved.twitchCommand) setTwitchCommand(saved.twitchCommand); }, []), onRestoreSolution: useCallback((solution: TennisOutput) => { setResult(solution); setTwitchCommand(generateTwitchCommand({ moduleType: ModuleType.TENNIS, result: solution })); }, []), currentModule, setIsSolved });
  const solve = async () => { if (!round?.id || !bomb?.id || !currentModule?.id) return setError("Missing required information"); clearError(); setIsLoading(true); try { const response = await solveTennis(round.id, bomb.id, currentModule.id, { tournament, mensPlay, sets: parseSets(setsText), mode, player1Score: p1, player2Score: p2 }); const command = generateTwitchCommand({ moduleType: ModuleType.TENNIS, result: response.output }); setResult(response.output); setTwitchCommand(command); setIsSolved(response.solved); if (response.solved) markModuleSolved(bomb.id, currentModule.id); updateModuleAfterSolve(bomb.id, currentModule.id, { ...state, result: response.output, twitchCommand: command }, response.output, response.solved); } catch (cause) { setError(cause instanceof Error ? cause.message : "Failed to solve Tennis"); } finally { setIsLoading(false); } };
  const reset = () => { setSetsText(""); setResult(null); setTwitchCommand(""); resetSolverState(); };
  return <SolverLayout><SolverSection title="Match" description="Enter completed/current set scores from top to bottom, one player-1/player-2 pair per line."><div className="grid gap-3 sm:grid-cols-2"><select aria-label="Tournament" value={tournament} onChange={(e) => setTournament(e.target.value as TennisInput["tournament"])} className="rounded-md border border-input bg-background p-2"><option value="US_OPEN">US Open — blue</option><option value="WIMBLEDON">Wimbledon — green</option><option value="FRENCH_OPEN">French Open — orange</option></select><label className="flex items-center gap-2"><input type="checkbox" checked={mensPlay} onChange={(e) => setMensPlay(e.target.checked)}/>Men's match</label></div><textarea aria-label="Set scores" rows={5} value={setsText} onChange={(e) => setSetsText(e.target.value)} placeholder="6-4\n3-2" className="mt-3 w-full rounded-md border border-input bg-background p-3 font-mono"/></SolverSection><SolverSection title="Current game"><select aria-label="Score mode" value={mode} onChange={(e) => setMode(e.target.value as TennisInput["mode"])} className="w-full rounded-md border border-input bg-background p-2"><option value="NORMAL">Normal (0/15/30/40)</option><option value="DEUCE">Deuce / Égalité</option><option value="ADVANTAGE_P1">Advantage player 1</option><option value="ADVANTAGE_P2">Advantage player 2</option><option value="TIE_BREAK">Tie break</option></select>{(mode === "NORMAL" || mode === "TIE_BREAK") && <div className="mt-3 grid grid-cols-2 gap-3"><input aria-label="Player 1 game score" type="number" value={p1} onChange={(e) => setP1(Number(e.target.value))} className="rounded-md border border-input bg-background p-2"/><input aria-label="Player 2 game score" type="number" value={p2} onChange={(e) => setP2(Number(e.target.value))} className="rounded-md border border-input bg-background p-2"/></div>}</SolverSection><SolverControls onSolve={solve} onReset={reset} isLoading={isLoading} isSolved={isSolved} solveText="Play 30 rallies"/><ErrorAlert error={error}/>{result && <SolverSection title="Final score" className="border-emerald-500/40">{result.winner ? <p className="text-2xl font-bold">Click player {result.winner}</p> : <><p className="font-semibold">Sets: {result.sets.map((set) => `${set.player1}–${set.player2}`).join(", ")}</p><p>{result.mode.replaceAll("_", " ")}: {result.player1Score}–{result.player2Score}</p></>}</SolverSection>}{twitchCommand && <TwitchCommandDisplay command={twitchCommand}/>}<SolverInstructions>For normal scoring enter 0, 15, 30, or 40. For a tie break enter the displayed integers. Player 1 is the top-listed name; the module derives service from the full score.</SolverInstructions></SolverLayout>;
}
