import { useCallback, useMemo, useState } from "react";
import { solveTheSwitch, type SwitchColor, type SwitchPosition, type TheSwitchOutput } from "../../services/theSwitchService";
import { useRoundStore } from "../../store/useRoundStore";
import { ModuleType, type BombEntity } from "../../types";
import { generateTwitchCommand } from "../../utils/twitchCommands";
import { ErrorAlert, SolverControls, SolverInstructions, SolverLayout, SolverSection, TwitchCommandDisplay, useSolver, useSolverModulePersistence } from "../common";
const COLORS: SwitchColor[] = ["RED","ORANGE","YELLOW","GREEN","BLUE","PURPLE"];
export default function TheSwitchSolver({ bomb }: { bomb: BombEntity | null | undefined }) {
  const [position, setPosition] = useState<SwitchPosition>("DOWN"), [topColor, setTopColor] = useState<SwitchColor>("RED"), [bottomColor, setBottomColor] = useState<SwitchColor>("GREEN"), [restartAttempt, setRestartAttempt] = useState(true);
  const [result, setResult] = useState<TheSwitchOutput | null>(null), [twitchCommand, setTwitchCommand] = useState("");
  const { isLoading, error, isSolved, setIsLoading, setError, setIsSolved, clearError, reset: resetSolverState, currentModule, round, markModuleSolved } = useSolver();
  const updateModuleAfterSolve = useRoundStore((state) => state.updateModuleAfterSolve);
  const state = useMemo(() => ({ position, topColor, bottomColor, restartAttempt, result, twitchCommand }), [position, topColor, bottomColor, restartAttempt, result, twitchCommand]);
  useSolverModulePersistence<typeof state, TheSwitchOutput>({ state, onRestoreState: useCallback((saved) => { if (saved.position) setPosition(saved.position); if (saved.topColor) setTopColor(saved.topColor); if (saved.bottomColor) setBottomColor(saved.bottomColor); if (saved.restartAttempt !== undefined) setRestartAttempt(saved.restartAttempt); if (saved.result) setResult(saved.result); if (saved.twitchCommand) setTwitchCommand(saved.twitchCommand); }, []), onRestoreSolution: useCallback((solution: TheSwitchOutput) => { setResult(solution); setTwitchCommand(generateTwitchCommand({ moduleType: ModuleType.THE_SWITCH, result: solution })); }, []), currentModule, setIsSolved });
  const changed = () => { setResult(null); setTwitchCommand(""); clearError(); };
  const solve = async () => { if (!round?.id || !bomb?.id || !currentModule?.id) return setError("Missing required information"); clearError(); setIsLoading(true); try { const input = { position, topColor, bottomColor, restartAttempt }; const response = await solveTheSwitch(round.id, bomb.id, currentModule.id, input); const command = generateTwitchCommand({ moduleType: ModuleType.THE_SWITCH, result: response.output }); setResult(response.output); setTwitchCommand(command); setRestartAttempt(false); setIsSolved(response.solved); if (response.solved) markModuleSolved(bomb.id, currentModule.id); updateModuleAfterSolve(bomb.id, currentModule.id, { ...input, restartAttempt: false, result: response.output, twitchCommand: command }, response.output, response.solved); } catch (cause) { setError(cause instanceof Error ? cause.message : "Failed to solve The Switch"); } finally { setIsLoading(false); } };
  const reset = () => { setPosition("DOWN"); setTopColor("RED"); setBottomColor("GREEN"); setRestartAttempt(true); setResult(null); setTwitchCommand(""); resetSolverState(); };
  return <SolverLayout><SolverSection title="Current switch and LEDs"><div className="grid gap-3 sm:grid-cols-3"><label>Switch position<select aria-label="Switch position" value={position} onChange={(e) => { setPosition(e.target.value as SwitchPosition); changed(); }} className="mt-1 h-11 w-full rounded-md border bg-background px-3"><option>UP</option><option>DOWN</option></select></label>{[["Top LED",topColor,setTopColor],["Bottom LED",bottomColor,setBottomColor]].map(([label,value,setter]) => <label key={label as string}>{label as string}<select aria-label={`${label} color`} value={value as string} onChange={(e) => { (setter as (v: SwitchColor) => void)(e.target.value as SwitchColor); changed(); }} className="mt-1 h-11 w-full rounded-md border bg-background px-3">{COLORS.map((color) => <option key={color}>{color}</option>)}</select></label>)}</div></SolverSection><SolverControls onSolve={solve} onReset={reset} isLoading={isLoading} isSolved={isSolved} solveText="Find flip digit" /><ErrorAlert error={error} />{result && <SolverSection title={`Flip ${result.stage}`} className="border-emerald-500/40"><p className="text-2xl font-bold">Flip {result.flipTo} when either seconds digit is {result.timerDigit}</p></SolverSection>}{twitchCommand && <TwitchCommandDisplay command={twitchCommand} />}<SolverInstructions>After a successful first flip, replace both new LED colors and solve again. A strike resets progress and generates new colors; use Reset before entering that new first flip.</SolverInstructions></SolverLayout>;
}
