/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ktanesolver.ModdedRegular;

import javax.swing.JOptionPane;

/**
 *
 * @author Komp
 */
public class TheBulb extends javax.swing.JFrame {
    
    int stage=1;
    boolean state=false, seethrough=false, car=false, ind=false, msa=false, snd=false;
    String colour;
    String[] lit,unlit;
    public TheBulb(String[] l, String[] u) {
        lit=l;
        unlit=u;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgTrans = new javax.swing.ButtonGroup();
        bgState = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        cbColour = new javax.swing.JComboBox<>();
        rbSee = new javax.swing.JRadioButton();
        rbOp = new javax.swing.JRadioButton();
        rbOn = new javax.swing.JRadioButton();
        rbOff = new javax.swing.JRadioButton();
        bAccept = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Colour");

        cbColour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blue", "Green", "Purple", "Red", "White", "Yellow" }));

        bgTrans.add(rbSee);
        rbSee.setText("See-through");

        bgTrans.add(rbOp);
        rbOp.setText("Opaque");

        bgState.add(rbOn);
        rbOn.setText("On");

        bgState.add(rbOff);
        rbOff.setText("Off");

        bAccept.setText("OK");
        bAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAcceptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bAccept)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbColour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbOp)
                            .addComponent(rbSee))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbOff)
                            .addComponent(rbOn))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbOn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbOff))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(rbOp)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(rbSee))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cbColour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bAccept)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAcceptActionPerformed
        state = rbOn.isSelected();
        seethrough = rbSee.isSelected();
        colour=cbColour.getSelectedItem().toString().toLowerCase();
        if(stage==1){
            if(state==true){
                if(seethrough==true){
                    JOptionPane.showMessageDialog(this, "Press I");
                    stage=2;
                    return;
                }
                else{
                    JOptionPane.showMessageDialog(this, "Press O");
                    stage=3;
                    return;
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "Unscrew the bulb");
                stage=4;
                return;
            }
        }
        if(stage==2){
            if(colour.equals("red")){
                JOptionPane.showMessageDialog(this, "Press I, then unscrew the bulb");
                stage=5;
                return;
            }
            if(colour.equals("white")){
                JOptionPane.showMessageDialog(this, "Press O, then unscrew the bulb");
                stage=6;
                return;
            }
            JOptionPane.showMessageDialog(this, "Unscrew the bulb");
            stage=7;
            return;
        }
        if(stage==3){
            if(colour.equals("green")){
                JOptionPane.showMessageDialog(this, "Press I, then unscrew the bulb");
                stage=6;
                return;
            }
            if(colour.equals("purple")){
                JOptionPane.showMessageDialog(this, "Press O, then unscrew the bulb");
                stage=5;
                return;
            }
            JOptionPane.showMessageDialog(this, "Unscrew the bulb");
            stage=8;
            return;
        }
        if(stage==4){
            if(car||snd|msa||ind){
                JOptionPane.showMessageDialog(this, "Press I");
                stage=9;
                return;
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Press O");
                stage=10;
                return;
            }
        }
    }//GEN-LAST:event_bAcceptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TheBulb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TheBulb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TheBulb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TheBulb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new TheBulb().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAccept;
    private javax.swing.ButtonGroup bgState;
    private javax.swing.ButtonGroup bgTrans;
    private javax.swing.JComboBox<String> cbColour;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton rbOff;
    private javax.swing.JRadioButton rbOn;
    private javax.swing.JRadioButton rbOp;
    private javax.swing.JRadioButton rbSee;
    // End of variables declaration//GEN-END:variables
}
