package ktanesolver.module.modded.regular.booleanmaze;
import static org.assertj.core.api.Assertions.assertThat;import java.util.HashMap;import java.util.Map;import org.junit.jupiter.api.Test;import ktanesolver.entity.BombEntity;import ktanesolver.entity.ModuleEntity;import ktanesolver.entity.RoundEntity;import ktanesolver.logic.SolveSuccess;
class BooleanMazeSolverTest{
	private final BooleanMazeSolver solver=new BooleanMazeSolver();
	@Test void shiftsBadGoalWithWrapInAllFourInitialDirections(){assertThat(BooleanMazeSolver.goal("AA0000",0)).containsExactly(9,0);assertThat(BooleanMazeSolver.goal("AA0000",1)).containsExactly(0,1);assertThat(BooleanMazeSolver.goal("AA0000",2)).containsExactly(1,0);assertThat(BooleanMazeSolver.goal("AA0000",3)).containsExactly(0,9);}
	@Test void followsOfficialForcedSolvePolicyAndUsesStuckOnlyWithNoLegalMove(){BombEntity bomb=bomb("AA0055");ModuleEntity module=new ModuleEntity();var stuck=solve(bomb,module,new BooleanMazeInput(0,false));assertThat(stuck.action()).isEqualTo("STUCK");assertThat(stuck.from()).isEqualTo(stuck.to());var move=solve(bomb,module,new BooleanMazeInput(1,false));assertThat(move.action()).isEqualTo("D");assertThat(move.to()).containsExactly(1,0);}
	@Test void resetPositionReturnsToSerialStartWithoutChangingInitialGoal(){BombEntity bomb=bomb("AA0055");ModuleEntity module=new ModuleEntity();module.setState(new HashMap<>(Map.of("initialDisplay",1,"currentRow",8,"currentCol",8)));BooleanMazeOutput output=solve(bomb,module,new BooleanMazeInput(1,true));assertThat(output.from()).containsExactly(0,0);assertThat(output.goal()).containsExactly(5,5);}
	@Test void movingOntoGoalSolves(){BombEntity bomb=bomb("AA0000");ModuleEntity module=new ModuleEntity();var result=solver.solve(new RoundEntity(),bomb,module,new BooleanMazeInput(1,false));assertThat(result).isInstanceOf(SolveSuccess.class);assertThat(((SolveSuccess<BooleanMazeOutput>)result).output().action()).isEqualTo("R");assertThat(module.isSolved()).isTrue();}
	@Test void matchesEveryGateTruthTable(){boolean[][] expected={{true,false,false,false},{false,true,true,false},{false,true,true,true},{false,false,false,true}};for(int gate=0;gate<4;gate++)for(int display=0;display<4;display++)assertThat(BooleanMazeSolver.legal(gate,display)).isEqualTo(expected[gate][display]);}
	private BooleanMazeOutput solve(BombEntity bomb,ModuleEntity module,BooleanMazeInput input){return ((SolveSuccess<BooleanMazeOutput>)solver.solve(new RoundEntity(),bomb,module,input)).output();}private static BombEntity bomb(String serial){BombEntity bomb=new BombEntity();bomb.setSerialNumber(serial);return bomb;}
}
