package ktanesolver.module.modded.regular.westeros;

import java.util.*;import org.springframework.stereotype.Service;import ktanesolver.annotation.ModuleInfo;import ktanesolver.dto.ModuleCatalogDto;import ktanesolver.entity.*;import ktanesolver.enums.ModuleType;import ktanesolver.logic.*;

@Service @ModuleInfo(type=ModuleType.WESTEROS,id="westeros",name="Westeros",category=ModuleCatalogDto.ModuleCategory.MODDED_REGULAR,description="Identify the house from a clue and submit its sigil, member, words, and seat.",tags={"game of thrones","words","houses"})
public class WesterosSolver extends AbstractModuleSolver<WesterosSolver.Input,WesterosSolver.Output>{
 public record Input(String clue,List<String> availableForenames)implements ModuleInput{} public record Output(String sigil,String forename,String house,String words,String seat,String twitchCommand)implements ModuleOutput{} private record House(String name,String words,String seat,List<String> people){}
 private static final List<House> HOUSES=new ArrayList<>();static{String data="Arryn|As High as Honour|The Eyrie|Jon,Robin,Elbert,Rowena,Jasper;Baratheon|Ours is the Fury|Storm's End|Robert,Stannis,Renly,Joffrey,Shireen;Bolton|Our Blades are Sharp|The Dreadfort|Roose,Ramsay,Domeric,Bethany,Belthasar;Cerwyn|Honed and Ready|Castle Cerwyn|Medger,Jonelle,Cley,Robard,Vivian;Frey|We Stand Together|The Twins|Walder,Roslin,Walda,Lothar,Olyvar;Greyjoy|We Do Not Sow|Pyke|Theon,Victarion,Euron,Balon,Aeron;Hightower|We Light the Way|Hightower|Gerold,Leyton,Lynesse,Garth,Baelor;Hornwood|Righteous in Wrath|Hornwood|Halys,Berena,Daryn,Hallis,Donella;Karstark|The Sun of Winter|Karhold|Rickard,Harrion,Torrhen,Alys,Arnolf;Lannister|Hear Me Roar|Casterly Rock|Tyrion,Cersei,Jaime,Tywin,Kevan;Marbrand|Burning Bright|Ashemark|Damon,Addam,Darlessa,Lorent,Denys;Martell|Unbowed, Unbent, Unbroken|Sunspear|Oberyn,Doran,Arianne,Trystane,Elia;Mormont|Here We Stand|Bear Island|Jorah,Jeor,Lyanna,Maege,Alysane;Penrose|Set Down Our Deeds|Parchments|Lucinda,Ronnel,Laena,Jocelyn,Joy;Royce|We Remember|Runestone|Yohn,Andar,Robar,Waymar,Ysilla;Stark|Winter is Coming|Winterfell|Eddard,Arya,Robb,Brandon,Benjen;Targaryen|Fire and Blood|Dragonstone|Daenerys,Viserys,Rhaegar,Aerys,Aemon;Tarly|First in Battle|Horn Hill|Randyll,Samwell,Dickon,Talla,Sansara;Tully|Family, Duty, Honour|Riverrun|Hoster,Edmure,Lysa,Catelyn,Brynden;Tyrell|Growing Strong|Highgarden|Olenna,Loras,Mace,Luthor,Margaery";for(String row:data.split(";")){String[]p=row.split("\\|",-1);HOUSES.add(new House(p[0],p[1],p[2],List.of(p[3].split(","))));}}
 @Override protected SolveResult<Output> doSolve(RoundEntity r,BombEntity b,ModuleEntity m,Input in){if(in==null||in.clue()==null||in.availableForenames()==null||in.availableForenames().isEmpty())return failure("Enter the clue and the currently available forenames");House h=HOUSES.stream().filter(x->matches(x,in.clue().trim())).findFirst().orElse(null);if(h==null)return failure("Clue not found in the default Westeros table");String person=in.availableForenames().stream().filter(x->h.people().stream().anyMatch(p->p.equalsIgnoreCase(x.trim()))).findFirst().orElse(null);if(person==null)return failure("None of the available forenames belongs to House "+h.name());String cmd="submit %s %s %s %s %s".formatted(h.name(),person,h.name(),h.words().replace(" ",""),h.seat().replace(" ",""));return success(new Output(h.name(),person,h.name(),h.words(),h.seat(),cmd));}
 private static boolean matches(House h,String c){return h.name().equalsIgnoreCase(c)||h.words().equalsIgnoreCase(c)||h.seat().equalsIgnoreCase(c)||h.people().stream().anyMatch(x->x.equalsIgnoreCase(c));}
}
