package ktanesolver.module.modded.regular.sync1253;

import java.util.*;import org.springframework.stereotype.Service;import ktanesolver.annotation.ModuleInfo;import ktanesolver.dto.ModuleCatalogDto;import ktanesolver.entity.*;import ktanesolver.enums.ModuleType;import ktanesolver.logic.*;

@Service @ModuleInfo(type=ModuleType.SYNC_125_3,id="sync125_3",name="SYNC-125 [3]",category=ModuleCatalogDto.ModuleCategory.MODDED_REGULAR,description="Convert each decoded CMP word into the required base-4 value.",tags={"words","base 4","stages","souvenir"})
public class Sync1253Solver extends AbstractModuleSolver<Sync1253Solver.Input,Sync1253Solver.Output>{
 public record Input(String decodedWord,String displayedCmp)implements ModuleInput{} public record Output(int stage,int decimalValue,String base4)implements ModuleOutput{} public record State(List<String> displays){public State(){this(new ArrayList<>());}}
 private static final Map<String,Integer> FIXED=new HashMap<>();static{String[] rows={"bombs:0,calling:8,clay:15,club:7,color:1,column:9,course:14,crab:6,data:2,date:10,hacking:13,having:5,maid:3,main:11,maze:12,member:4,party:5,play:13,plot:10,pond:2,rhyme:6,selling:14,setting:9,shame:1,slay:7,wife:15,wine:8,wire:0"};for(String x:rows[0].split(",")){String[] p=x.split(":");FIXED.put(p[0],Integer.parseInt(p[1]));}}
 @Override protected SolveResult<Output> doSolve(RoundEntity r,BombEntity b,ModuleEntity m,Input in){if(in==null||in.decodedWord()==null)return failure("Enter the decoded English word and the exact displayed CMP text");String w=in.decodedWord().trim().toLowerCase();int v;if(FIXED.containsKey(w))v=FIXED.get(w);else v=switch(w){case"code"->16-b.getBatteryCount();case"crack","port"->16-(int)b.getModules().stream().filter(ModuleEntity::isSolved).count();case"horse","shape"->16-b.getModules().size();case"module","wrecking"->16-firstHex(b.getSerialNumber());case"panic"->16-b.getBatteryCount();default->-1;};if(v<0)return failure("Unknown decoded word");v=Math.floorMod(v,16);String base=Integer.toString(v,4);State s=m.getStateAs(State.class,State::new);List<String>d=new ArrayList<>(s.displays());d.add(in.displayedCmp()==null?"":in.displayedCmp());storeTypedState(m,new State(d));storeState(m,"sync1253Displays",d);return success(new Output(d.size(),v,base),d.size()>=4);}
 private static int firstHex(String s){for(char c:s.toUpperCase().toCharArray())if(Character.digit(c,16)>=0)return Character.digit(c,16);return 0;}
}
