/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ktanesolver.VanillaRegular;

/**
 *
 * @author Komp
 */
public class WhosFirstV1 extends javax.swing.JFrame {
    int row;
    String display, searched, result;
    String[] words=new String[6];
    String[][] wordslist=
        {
                                {"READY", "YES", "OKAY", "WHAT", "MIDDLE", "LEFT", "PRESS", "RIGHT", "BLANK", "READY"},
				{"FIRST", "LEFT", "OKAY", "YES", "MIDDLE", "NO", "RIGHT", "NOTHING", "UHHH", "WAIT", "READY", "BLANK", "WHAT", "PRESS", "FIRST"},
				{"NO", "BLANK", "UHHH", "WAIT", "FIRST", "WHAT", "READY", "RIGHT", "YES", "NOTHING", "LEFT", "PRESS", "OKAY", "NO"},
				{"BLANK", "WAIT", "RIGHT", "OKAY", "MIDDLE", "BLANK"},
				{"NOTHING", "UHHH", "RIGHT", "OKAY", "MIDDLE", "YES", "BLANK", "NO", "PRESS", "LEFT", "WHAT", "WAIT", "FIRST", "NOTHING"},
				{"YES", "OKAY", "RIGHT", "UHHH", "MIDDLE", "FIRST", "WHAT", "PRESS", "READY", "NOTHING", "YES"},
				{"WHAT", "UHHH", "WHAT"},
				{"UHHH", "READY", "NOTHING", "LEFT", "WHAT", "OKAY", "YES", "RIGHT", "NO", "PRESS", "BLANK", "UHHH"},
				{"LEFT", "RIGHT", "LEFT"},
				{"RIGHT", "YES", "NOTHING", "READY", "PRESS", "NO", "WAIT", "WHAT", "RIGHT"},
				{"MIDDLE", "BLANK", "READY", "OKAY", "WHAT", "NOTHING", "PRESS", "NO", "WAIT", "LEFT", "MIDDLE"},
				{"OKAY", "MIDDLE", "NO", "FIRST", "YES", "UHHH", "NOTHING", "WAIT", "OKAY"},
				{"WAIT", "UHHH", "NO", "BLANK", "OKAY", "YES", "LEFT", "FIRST", "PRESS", "WHAT", "WAIT"},
				{"PRESS", "RIGHT", "MIDDLE", "YES", "READY", "PRESS"},
				{"YOU", "SURE", "YOU ARE", "YOUR", "YOU'RE", "NEXT", "UH HUH", "UR", "HOLD", "WHAT?", "YOU"},
				{"YOU ARE", "YOUR", "NEXT", "LIKE", "UH HUH", "WHAT?", "DONE", "UH UH", "HOLD", "YOU", "U", "YOU'RE", "SURE", "UR", "YOU ARE"},
				{"YOUR", "UH UH", "YOU ARE", "UH HUH", "YOUR"},
				{"YOU'RE", "YOU", "YOU'RE"},
				{"UR", "DONE", "U", "UR"},
				{"U", "UH HUH", "SURE", "NEXT", "WHAT?", "YOU'RE", "UR", "UH UH", "DONE", "U"},
				{"UH HUH", "UH HUH"},
				{"UH UH", "UR", "U", "YOU ARE", "YOU'RE", "NEXT", "UH UH"},
				{"WHAT?", "YOU", "HOLD", "YOU'RE", "YOUR", "U", "DONE", "UH UH", "LIKE", "YOU ARE", "UH HUH", "UR", "NEXT", "WHAT?"},
				{"DONE", "SURE", "UH HUH", "NEXT", "WHAT?", "YOUR", "UR", "YOU'RE", "HOLD", "LIKE", "YOU", "U", "YOU ARE", "UH UH", "DONE"},
				{"NEXT", "WHAT?", "UH HUH", "UH UH", "YOUR", "HOLD", "SURE", "NEXT"},
				{"HOLD", "YOU ARE", "U", "DONE", "UH UH", "YOU", "UR", "SURE", "WHAT?", "YOU'RE", "NEXT", "HOLD"},
				{"SURE", "YOU ARE", "DONE", "LIKE", "YOU'RE", "YOU", "HOLD", "UH HUH", "UR", "SURE"},
				{"LIKE", "YOU'RE", "NEXT", "U", "UR", "HOLD", "DONE", "UH UH", "WHAT?", "UH HUH", "YOU", "LIKE"}
        };
    public WhosFirstV1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbUP = new javax.swing.JComboBox<>();
        cbUpLeft = new javax.swing.JComboBox<>();
        cbUpRight = new javax.swing.JComboBox<>();
        cbMidLeft = new javax.swing.JComboBox<>();
        cbMidRight = new javax.swing.JComboBox<>();
        cbBotLeft = new javax.swing.JComboBox<>();
        cbBotRight = new javax.swing.JComboBox<>();
        bAccept = new javax.swing.JButton();
        lResult = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cbUP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YES", "FIRST", "DISPLAY", "OKAY", "SAYS", "NOTHING", "", "BLANK", "NO", "LED", "LEAD", "READ", "RED", "REED", "LEED", "HOLD ON", "YOU", "YOU ARE", "YOUR", "YOU'RE", "UR", "THERE", "THEY'RE", "THEIR", "THEY ARE", "SEE", "C", "CEE" }));

        cbUpLeft.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "READY", "FIRST", "NO", "BLANK", "NOTHING", "YES", "WHAT", "UHHH", "LEFT", "RIGHT", "MIDDLE", "OKAY", "WAIT", "PRESS", "YOU", "YOU ARE", "YOUR", "YOU'RE", "UR", "U", "UH HUH", "UH UH", "WHAT?", "DONE", "NEXT", "HOLD", "SURE", "LIKE" }));

        cbUpRight.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "READY", "FIRST", "NO", "BLANK", "NOTHING", "YES", "WHAT", "UHHH", "LEFT", "RIGHT", "MIDDLE", "OKAY", "WAIT", "PRESS", "YOU", "YOU ARE", "YOUR", "YOU'RE", "UR", "U", "UH HUH", "UH UH", "WHAT?", "DONE", "NEXT", "HOLD", "SURE", "LIKE" }));

        cbMidLeft.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "READY", "FIRST", "NO", "BLANK", "NOTHING", "YES", "WHAT", "UHHH", "LEFT", "RIGHT", "MIDDLE", "OKAY", "WAIT", "PRESS", "YOU", "YOU ARE", "YOUR", "YOU'RE", "UR", "U", "UH HUH", "UH UH", "WHAT?", "DONE", "NEXT", "HOLD", "SURE", "LIKE" }));

        cbMidRight.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "READY", "FIRST", "NO", "BLANK", "NOTHING", "YES", "WHAT", "UHHH", "LEFT", "RIGHT", "MIDDLE", "OKAY", "WAIT", "PRESS", "YOU", "YOU ARE", "YOUR", "YOU'RE", "UR", "U", "UH HUH", "UH UH", "WHAT?", "DONE", "NEXT", "HOLD", "SURE", "LIKE" }));

        cbBotLeft.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "READY", "FIRST", "NO", "BLANK", "NOTHING", "YES", "WHAT", "UHHH", "LEFT", "RIGHT", "MIDDLE", "OKAY", "WAIT", "PRESS", "YOU", "YOU ARE", "YOUR", "YOU'RE", "UR", "U", "UH HUH", "UH UH", "WHAT?", "DONE", "NEXT", "HOLD", "SURE", "LIKE" }));

        cbBotRight.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "READY", "FIRST", "NO", "BLANK", "NOTHING", "YES", "WHAT", "UHHH", "LEFT", "RIGHT", "MIDDLE", "OKAY", "WAIT", "PRESS", "YOU", "YOU ARE", "YOUR", "YOU'RE", "UR", "U", "UH HUH", "UH UH", "WHAT?", "DONE", "NEXT", "HOLD", "SURE", "LIKE" }));

        bAccept.setText("OK");
        bAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAcceptActionPerformed(evt);
            }
        });

        jLabel2.setText("Result:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(cbUP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbMidLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(cbMidRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbUpLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(cbUpRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbBotLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(cbBotRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lResult)
                        .addGap(18, 18, 18)
                        .addComponent(bAccept)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbUP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbUpLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbUpRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMidLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMidRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbBotLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbBotRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAccept)
                    .addComponent(lResult)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAcceptActionPerformed
        display=cbUP.getSelectedItem().toString();
        words[0]=cbUpLeft.getSelectedItem().toString();
        words[1]=cbUpRight.getSelectedItem().toString();
        words[2]=cbMidLeft.getSelectedItem().toString();
        words[3]=cbMidRight.getSelectedItem().toString();
        words[4]=cbBotLeft.getSelectedItem().toString();
        words[5]=cbBotRight.getSelectedItem().toString();
        searchedWord();
        resultSelection();
    }//GEN-LAST:event_bAcceptActionPerformed

    private void searchedWord() {
        switch(display){
            case "YES":{
                searched=words[2];
                break;
            }
            case "FIRST":{
                searched=words[1];
                break;
            }
            case "DISPLAY":{
                searched=words[5];
                break;
            }
            case "OKAY":{
                searched=words[1];
                break;
            }
            case "SAYS":{
                searched=words[5];
                break;
            }
            case "NOTHING":{
                searched=words[2];
                break;
            }
            case "":{
                searched=words[4];
                break;
            }
            case "BLANK":{
                searched=words[3];
                break;
            }
            case "NO":{
                searched=words[5];
                break;
            }
            case "LED":{
                searched=words[2];
                break;
            }
            case "LEAD":{
                searched=words[5];
                break;
            }
            case "READ":{
                searched=words[3];
                break;
            }
            case "RED":{
                searched=words[3];
                break;
            }
            case "REED":{
                searched=words[4];
                break;
            }
            case "LEED":{
                searched=words[4];
                break;
            }
            case "HOLD ON":{
                searched=words[5];
                break;
            }
            case "YOU":{
                searched=words[3];
                break;
            }
            case "YOU ARE":{
                searched=words[5];
                break;
            }
            case "YOUR":{
                searched=words[3];
                break;
            }
            case "YOU'RE":{
                searched=words[3];
                break;
            }
            case "UR":{
                searched=words[0];
                break;
            }
            case "THERE":{
                searched=words[5];
                break;
            }
            case "THEY'RE":{
                searched=words[4];
                break;
            }
            case "THEIR":{
                searched=words[3];
                break;
            }
            case "THEY ARE":{
                searched=words[2];
                break;
            }
            case "SEE":{
                searched=words[5];
                break;
            }
            case "C":{
                searched=words[1];
                break;
            }
            case "CEE":{
                searched=words[5];
                break;
            }
        }
    }
    private void resultSelection(){
        for(int i=0;i<wordslist.length;i++){
            if(wordslist[i][0].equals(searched)){
                row=i;
                break;
            }
        }
        for (int i=1;i<wordslist[row].length;i++){
            if(wordslist[row][i].equals(words[0])||wordslist[row][i].equals(words[1])||wordslist[row][i].equals(words[2])||wordslist[row][i].equals(words[3])||wordslist[row][i].equals(words[4])||wordslist[row][i].equals(words[5])){
                result=wordslist[row][i];
                break;
            }
        }
        lResult.setText(result);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WhosFirstV1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WhosFirstV1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WhosFirstV1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WhosFirstV1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WhosFirstV1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAccept;
    private javax.swing.JComboBox<String> cbBotLeft;
    private javax.swing.JComboBox<String> cbBotRight;
    private javax.swing.JComboBox<String> cbMidLeft;
    private javax.swing.JComboBox<String> cbMidRight;
    private javax.swing.JComboBox<String> cbUP;
    private javax.swing.JComboBox<String> cbUpLeft;
    private javax.swing.JComboBox<String> cbUpRight;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lResult;
    // End of variables declaration//GEN-END:variables
}
