/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ktanesolver.VanillaRegular;

import javax.swing.JOptionPane;
import ktanesolver.Menu;

/**
 *
 * @author Komp
 */
public class Wires extends javax.swing.JFrame {
    Menu menu;
    int redC, blueC, yellowC, whiteC, blackC;
    String[] input, wires;
    char[] serial;
    int digit, wireC;
    public Wires(char[] s) {
        serial=s;
        initComponents();
    }
    void wires3(String[] w){
        if(redC==0){
            JOptionPane.showMessageDialog(rootPane, "Cut the second wire");
        }
        else{
        if(w[2].equals("white")){
            JOptionPane.showMessageDialog(rootPane, "Cut the last wire");
        }else{  
        if(blueC>1){
            JOptionPane.showMessageDialog(rootPane, "Cut the last blue wire");
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Cut the last wire");
            }
        }
    }
    void wires4(String[] w){
        if(redC>1&&digit%2==1){
            JOptionPane.showMessageDialog(rootPane, "Cut the last red wire");
        }
        else{
            if(w[3].equals("yellow")&&redC==0){
                JOptionPane.showMessageDialog(rootPane, "Cut the first wire");
            }
            else{
                if(blueC==1){
                    JOptionPane.showMessageDialog(rootPane, "Cut the first wire");
                }
                else{
                    if(yellowC>1)
                    {
                        JOptionPane.showMessageDialog(rootPane, "Cut the last wire");
                    }
                    else
                        JOptionPane.showMessageDialog(rootPane, "Cut the second wire");
                }
            }
        }
    }
    void wires5(String[] w){
        if(w[4].equals("black")&&digit%2==1){
            JOptionPane.showMessageDialog(rootPane, "Cut the fourth wire");
        }else{
            if(redC==1&&yellowC>1){
                JOptionPane.showMessageDialog(rootPane, "Cut the first wire");
            }
            else{
                if(blackC==0)
                {
                    JOptionPane.showMessageDialog(rootPane, "Cut the second wire");
                }
                else
                    JOptionPane.showMessageDialog(rootPane, "Cut the first wire");
            }
        }
    }
    void wires6(String[] w){
        if(yellowC==0&&digit%2==1){
            JOptionPane.showMessageDialog(rootPane, "Cut the third wire");
        }
        else{
            if(yellowC==1&&whiteC>1){
                JOptionPane.showMessageDialog(rootPane, "Cut the fourth wire");
            }
            else{
                if(redC==0){
                    JOptionPane.showMessageDialog(rootPane, "Cut the last wire");
                }
                else
                    JOptionPane.showMessageDialog(rootPane, "Cut the fourth wire");
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bAccept = new javax.swing.JButton();
        cbFirst = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbSecond = new javax.swing.JComboBox<>();
        cbThird = new javax.swing.JComboBox<>();
        cbFourth = new javax.swing.JComboBox<>();
        cbFifth = new javax.swing.JComboBox<>();
        cbSixth = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Wires");

        bAccept.setText("OK");
        bAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAcceptActionPerformed(evt);
            }
        });

        cbFirst.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blue", "Red", "Black", "Yellow", "White", "-" }));
        cbFirst.setSelectedIndex(5);

        jLabel2.setText("1st wire");

        jLabel3.setText("2nd wire");

        jLabel4.setText("3rd wire");

        jLabel5.setText("4th wire");

        jLabel6.setText("5th wire");

        jLabel7.setText("6th wire");

        cbSecond.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blue", "Red", "Black", "Yellow", "White", "-" }));
        cbSecond.setSelectedIndex(5);

        cbThird.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blue", "Red", "Black", "Yellow", "White", "-" }));
        cbThird.setSelectedIndex(5);

        cbFourth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blue", "Red", "Black", "Yellow", "White", "-" }));
        cbFourth.setSelectedIndex(5);

        cbFifth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blue", "Red", "Black", "Yellow", "White", "-" }));
        cbFifth.setSelectedIndex(5);

        cbSixth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blue", "Red", "Black", "Yellow", "White", "-" }));
        cbSixth.setSelectedIndex(5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(bAccept, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(2, 2, 2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbSixth, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbFifth, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbFourth, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(cbThird, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbSecond, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cbFirst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cbSecond, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cbThird, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cbFourth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cbFifth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cbSixth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bAccept, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAcceptActionPerformed
        redC=blueC=blackC=yellowC=whiteC=wireC=0;
        input = new String[6];
        for(int i=serial.length-1;i>=0;i--){
            if(Character.isDigit(serial[i]))
            {
                digit=Character.getNumericValue(serial[i]);
                break;
            }
        }
        input[0]=cbFirst.getSelectedItem().toString().toLowerCase();
        input[1]=cbSecond.getSelectedItem().toString().toLowerCase();
        input[2]=cbThird.getSelectedItem().toString().toLowerCase();
        input[3]=cbFourth.getSelectedItem().toString().toLowerCase();
        input[4]=cbFifth.getSelectedItem().toString().toLowerCase();
        input[5]=cbSixth.getSelectedItem().toString().toLowerCase();
        for (String input1 : input) {
            if (!input1.equals("-")) {
                wireC++;
            }
        }
        wires=new String[wireC];
            System.arraycopy(input, 0, wires, 0, wires.length);
        for (String input1 : wires) {
            if (input1.equals("red")) {
                redC++;
            }
            if (input1.equals("blue")) {
                blueC++;
            }
            if (input1.equals("black")) {
                blackC++;
            }
            if (input1.equals("yellow")) {
                yellowC++;
            }
            if (input1.equals("white")) {
                whiteC++;
            }
        }
        switch(wires.length)
        {
            case 3:
                    {
                        wires3(wires);
                        break;
                    }
            case 4:
                    {
                        wires4(wires);
                        break;
                    }
            case 5:
                    {
                        wires5(wires);
                        break;
                    }
            case 6:
                    {
                        wires6(wires);
                        break;
                    }
        }
        
    }//GEN-LAST:event_bAcceptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Wires.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Wires.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Wires.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Wires.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Wires().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAccept;
    private javax.swing.JComboBox<String> cbFifth;
    private javax.swing.JComboBox<String> cbFirst;
    private javax.swing.JComboBox<String> cbFourth;
    private javax.swing.JComboBox<String> cbSecond;
    private javax.swing.JComboBox<String> cbSixth;
    private javax.swing.JComboBox<String> cbThird;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
