package ktanesolver.module.modded.regular.dividedsquares;
import static org.assertj.core.api.Assertions.assertThat;import java.util.*;import org.junit.jupiter.api.Test;import ktanesolver.entity.*;import ktanesolver.enums.ModuleType;import ktanesolver.logic.*;import ktanesolver.module.modded.regular.dividedsquares.DividedSquaresInput.Color;
class DividedSquaresSolverTest{private final DividedSquaresSolver solver=new DividedSquaresSolver();
	@Test void tableUsesFirstColorAsAAndSecondAsB(){assertThat(DividedSquaresSolver.lookup(Color.RED,Color.YELLOW)).isEqualTo(20);assertThat(DividedSquaresSolver.lookup(Color.YELLOW,Color.RED)).isEqualTo(9);assertThat(DividedSquaresSolver.lookup(Color.BLUE,Color.GREEN)).isEqualTo(1);}
	@Test void findsUniqueSquareBelongingToTwoSerialPairsThenCalculatesTarget(){BombEntity bomb=bomb("TN1BC2",25);ModuleEntity module=new ModuleEntity();List<List<Color>>grid=List.of(List.of(Color.RED,Color.YELLOW),List.of(Color.BLUE,Color.GREEN));DividedSquaresOutput first=solve(bomb,module,new DividedSquaresInput(grid,null));assertThat(first).isEqualTo(new DividedSquaresOutput("A1","examine",null,false,2));DividedSquaresOutput second=solve(bomb,module,new DividedSquaresInput(grid,Color.BLUE));assertThat(second.square()).isEqualTo("A1");assertThat(second.targetSolvedModules()).isEqualTo(17);assertThat(second.anySolveCount()).isFalse();assertThat(module.getState()).containsEntry("dividedSquaresColorB","Blue").containsEntry("dividedSquaresSouvenirEligible",true);}
	@Test void oneSquareNeedsNoSerialPairSearch(){BombEntity bomb=bomb("AE1BC2",30);DividedSquaresOutput out=solve(bomb,new ModuleEntity(),new DividedSquaresInput(List.of(List.of(Color.BLUE)),Color.BLACK));assertThat(out.square()).isEqualTo("A1");assertThat(out.targetSolvedModules()).isEqualTo(23);}
	@Test void detectsAnyCountFallbackAndSuppressesSouvenir(){BombEntity bomb=bomb("AE1BC2",0);ModuleEntity module=new ModuleEntity();DividedSquaresOutput out=solve(bomb,module,new DividedSquaresInput(List.of(List.of(Color.RED)),Color.BLUE));assertThat(out.anySolveCount()).isTrue();assertThat(out.targetSolvedModules()).isNull();assertThat(module.getState()).containsEntry("dividedSquaresSouvenirEligible",false);}
	@Test void rejectsMalformedOrAmbiguousGrids(){BombEntity bomb=bomb("TN1BC2",20);assertThat(solver.solve(new RoundEntity(),bomb,new ModuleEntity(),new DividedSquaresInput(List.of(List.of(Color.RED),List.of(Color.BLUE)),null))).isInstanceOf(SolveFailure.class);List<List<Color>>none=List.of(List.of(Color.WHITE,Color.WHITE),List.of(Color.WHITE,Color.WHITE));assertThat(solver.solve(new RoundEntity(),bomb,new ModuleEntity(),new DividedSquaresInput(none,null))).isInstanceOf(SolveFailure.class);}
	@SuppressWarnings("unchecked")private DividedSquaresOutput solve(BombEntity b,ModuleEntity m,DividedSquaresInput i){return((SolveSuccess<DividedSquaresOutput>)solver.solve(new RoundEntity(),b,m,i)).output();}private static BombEntity bomb(String serial,int count){BombEntity b=new BombEntity();b.setSerialNumber(serial);List<ModuleEntity>modules=new ArrayList<>();for(int i=0;i<count;i++){ModuleEntity m=new ModuleEntity();m.setType(ModuleType.WIRES);modules.add(m);}b.setModules(modules);return b;}}
